<p>(Au d&eacute;but de la vid&eacute;o, on entend une musique celtique entra&icirc;nante avec du violon. Vid&eacute;o d&rsquo;un brick du XVIII<sup>e</sup> si&egrave;cle qui navigue en mer par une belle journ&eacute;e ensoleill&eacute;e.)</p>
<p>Narrateur&nbsp;: Embarquer &agrave; bord d&rsquo;un voilier pourrait vous laisser pantois devant le langage employ&eacute;.&nbsp;Les ordres donn&eacute;s par le capitaine &agrave; l&rsquo;&eacute;quipage, m&ecirc;me aujourd&rsquo;hui, peuvent parfois sonner comme une langue &eacute;trang&egrave;re. Voyons si vous pouvez apprendre quelques mots ou expressions. Cela vous aidera beaucoup &agrave; comprendre la fa&ccedil;on dont fonctionne la navigation sur un bateau. Peut-&ecirc;tre, un jour, pourriez-vous &ecirc;tre appel&eacute; &agrave; vous joindre &agrave; l&rsquo;&eacute;quipage!&nbsp;</p>
<p>(Vid&eacute;o du capitaine qui dirige le bateau et des marins qui tirent fort sur des cordes attach&eacute;es aux m&acirc;ts.)</p>
<p>Commen&ccedil;ons ici, sur ce brick &agrave; voiles carr&eacute;es, tr&egrave;s similaire &agrave; celui utilis&eacute; par le capitaine Vancouver il y a de cela quelques si&egrave;cles.</p>
<p>(Le brick est sur l&rsquo;eau. Il a deux m&acirc;ts, chacun gr&eacute;&eacute; de deux voiles carr&eacute;es. Deux voiles triangulaires se trouvent &agrave; l&rsquo;avant du bateau. L&rsquo;arri&egrave;re du bateau est dot&eacute; d&rsquo;une grand-voile.)</p>
<p>Tous les bateaux ont une proue, une poupe, un c&ocirc;t&eacute; b&acirc;bord et un c&ocirc;t&eacute; tribord. Les voiles sont attach&eacute;es aux m&acirc;ts et aux vergues et sont identifi&eacute;es selon leur position sur le bateau (voile de misaine et grand-voile) et selon leur position sur le m&acirc;t (huniers et perroquets).</p>
<p>(Le devant du bateau est d&eacute;sign&eacute; comme &laquo;&nbsp;proue&nbsp;&raquo;. L&rsquo;arri&egrave;re du bateau est d&eacute;sign&eacute; comme &laquo;&nbsp;poupe&nbsp;&raquo;. Le c&ocirc;t&eacute; gauche est d&eacute;sign&eacute; comme &laquo;&nbsp;b&acirc;bord&nbsp;&raquo; et le c&ocirc;t&eacute; droit comme &laquo;&nbsp;tribord&nbsp;&raquo;. Les m&acirc;ts sont les grands poteaux verticaux sur lesquels les voiles sont attach&eacute;es. Les vergues sont de longues poutres horizontales qui supportent le haut et le bas des voiles. Les voiles de misaine sont les voiles les plus pr&egrave;s de la proue et les grand-voiles sont au centre du bateau. Les huniers sont hauts sur les m&acirc;ts, et les perroquets sont les voiles au sommet des m&acirc;ts.)</p>
<p>Narrateur : Un capitaine pourrait ordonner&hellip;</p>
<p>Capitaine&nbsp;: &laquo;&nbsp;Aux m&acirc;ts matelots, abaissez huniers et perroquets!&nbsp;&raquo;&nbsp;</p>
<p>Narrateur : &laquo; Matelots &raquo; fait r&eacute;f&eacute;rence &agrave; l&rsquo;&eacute;quipage. &laquo; Aux m&acirc;ts &raquo; signifie de grimper sur le gr&eacute;ement. &nbsp;</p>
<p>(Vid&eacute;o de marins qui escaladent des &eacute;chelles de corde, appel&eacute;es gr&eacute;ement, jusqu&rsquo;en haut des m&acirc;ts.)</p>
<p>Narrateur&nbsp;: &laquo;&nbsp;Huniers<em>&nbsp;</em>&raquo; et &laquo;&nbsp;perroquets<em>&nbsp;</em>&raquo; sont des expressions de slang nautique pour d&eacute;signer les voiles sup&eacute;rieures de diff&eacute;rents m&acirc;ts. Donc, &laquo;&nbsp;Aux m&acirc;ts matelots, abaissez huniers et perroquets!&nbsp;&raquo; est l&rsquo;ordre du capitaine pour demander &agrave; l&rsquo;&eacute;quipage d&rsquo;escalader le m&acirc;t de misaine et le grand-m&acirc;t et d&rsquo;abaisser les huniers et les perroquets.</p>
<p>Capitaine&nbsp;: &laquo;&nbsp;Laissez tomber!&nbsp;&raquo;</p>
<p>(Les marins marchent ensuite sur des cordes horizontales pour d&eacute;rouler les huniers et les perroquets, d&eacute;ployant ainsi des voiles blanches.)</p>