<p>(Au début de la vidéo, on entend de la musique celtique rythmée jouée au violon.)</p>
<p>Un narrateur dit&nbsp; Comment le capitaine Vancouver s’orientait-il en mer?</p>
<p>Hé bien il utilisait une boussole magnétique pour connaître la direction empruntée par le bateau.</p>
<p>(Animation d’une boussole montrant le Nord.)</p>
<p>Narrateur&nbsp; Bien que le navigateur connaisse la direction empruntée par le bateau, le problème était de déterminer la distance parcourue à partir du moment où il avait perdu la terre de vue.</p>
<p>(Animation d’un bateau naviguant au milieu de l’océan Atlantique, loin de la Grande-Bretagne.)</p>
<p>Narrateur&nbsp; Le Nord et le Sud étaient faciles à déterminer en utilisant la latitude, une méthode mise au point par les navigateurs arabes au IXème siècle. Ceux-ci ont divisé la Terre en lignes imaginaires d’est en ouest, et les ont numérotées de zéro degré, à l’équateur, jusqu’à 90 degrés à chacun des pôles.</p>
<p>(Animation de la Terre avec des lignes de latitude dessinées horizontalement autour de la Terre à chaque dix degrés, au nord et au sud de l’équateur. L’équateur correspond à 0 degrés. L’Arctique est à 90 degrés Nord et l’Antarctique à 90 degrés Sud.)</p>
<p>Narrateur&nbsp; L’équipage utilisait ensuite des règles mathématiques de trigonométrie, c’est-à-dire associées aux triangles, afin de mesurer l’angle entre l’horizon et l’Étoile polaire. L’Étoile polaire - aussi appelée Polaris – est le point de départ parfait pour prendre une mesure puisqu’elle ne change presque pas de position et qu’elle est située directement au-dessus du pôle Nord.</p>
<p>(Animation d’un globe terrestre qui tourne sur lui-même. L’Étoile polaire est dessinée au-dessus de l’Arctique et ne bouge pas. Une formule trigonométrique est inscrite à gauche du globe terrestre.)</p>
<p>Narrateur&nbsp; À l’aide d’un instrument appelé sextant, l’équipage mesurait l’angle et, si le résultat était, par exemple, 50 degrés, cela signifiait que le bateau était situé à 50 degrés au nord de l’équateur. Cool, n’est-ce pas? À l’aide de cette méthode, l’équipage pouvait connaître la distance parcourue vers le nord ou vers le sud, et garder une position parfaite jusqu’à ce qu’ils revoient la terre. </p>
<p>(On voit un sextant. Il s’agit d’un instrument triangulaire composé de miroirs et d’un télescope. Une ligne relie le bateau à l’Étoile polaire. Une autre ligne est dessinée en s’éloignant du bateau et est identifiée comme la «&nbsp;ligne d’horizon&nbsp;». L’angle entre ces deux lignes, à partir du bateau est de 50 degrés. La ligne de latitude sur laquelle se trouve le bateau est identifiée 50 degrés Nord.) </p>
<p>Narrateur&nbsp; Il demeurait toutefois problématique de déterminer la distance parcourue par le bateau vers l’est ou vers l’ouest. Pour résoudre ce problème, le capitaine Vancouver a pu utiliser une nouvelle méthode innovante fraichement perfectionnée par son prédécesseur, le capitaine Cook. Cette solution reposait sur la régularité de la rotation de la Terre autour du Soleil et sur une horloge très précise.</p>
<p>Voici comment ça fonctionne. Nous savons que la Terre effectue une rotation d’Est en Ouest de 360 degrés en 24 heures. Il suffit de faire le calcul&nbsp; 360 divisés par 24 donne 15. </p>
<p>Ainsi, en une heure, la Terre bouge donc de 15 degrés par rapport au Soleil. Vous me suivez? Tout comme la latitude, des degrés de longitude ont été établis pour marquer de nouvelles lignes imaginaires autour de la Terre, mais cette fois les lignes couraient du Nord au Sud. Et puisque ce sont les Britanniques qui ont eu cette idée, ils ont décidé que le degré de longitude zéro - soit le premier méridien -, passerait par l’observatoire de Greenwich situé à Londres, en Angleterre.</p>
<p>(Des lignes de longitude sont dessinées verticalement sur le globe terrestre, reliant l’Arctique à l’Antarctique. Le premier méridien est identifié comme le degré 0 de longitude.)</p>
<p>Narrateur&nbsp; Si vous disposez d’une horloge précise à bord de votre bateau et que vous la réglez à l’heure de Greenwich (Temps moyen de Greenwich), vous pouvez comparer l’heure de Greenwich à l’heure locale du bateau, et ainsi déterminer la distance du bateau par rapport à Greenwich, vers l’est ou vers l’ouest.</p>
<p>Voici un exemple&nbsp; tout d’abord, le navigateur doit déterminer à quel moment il sera midi là où se trouve le bateau. Il peut le faire à l’aide d’un sextant afin de mesurer le moment où le soleil est à son plus haut dans le ciel. Si à midi, heure locale, notre horloge réglée sur l’heure moyenne de Greenwich indique qu’il est 16 heures à Greenwich, nous savons donc que nous sommes 4 heures plus tôt que l’heure de Greenwich. En sachant qu’une heure équivaut à 15 degrés, nous devons être à 4 heures fois 15 degrés de Greenwich, c’est-à-dire à 60 degrés à l’ouest de l’Angleterre. Simple, n’est-ce pas?</p>
<p>(On voit une carte du monde. L’heure au premier méridien, 16 h, est indiquée sur une horloge. Le premier méridien est identifié avec les lettres GMT, pour temps moyen de Greenwich. L’heure sur la ligne de longitude du bateau indique 12 h, marquée comme GMT-4, ou 60 degrés ouest.)</p>
<p>Narrateur&nbsp; Bien que cette méthode pour déterminer la longitude fut plutôt simple à comprendre, il fallait pouvoir compter sur une horloge très précise pour pouvoir l’utiliser. Et une horloge assez précise pour faire le travail n’existait pas encore. En 1714, le gouvernement britannique offre une prime de 20 000 livres à quiconque trouverait une solution, ce qui représente une somme d’environ 4 millions de dollars aujourd’hui! Hé bien c’est l’horloger John Harrison qui a finalement relevé le défi, en 1761, en inventant le chronomètre de marine.</p>
<p>(Une représentation historique de John Harrison assis sur une chaise. Il est vêtu avec classe et porte notamment un manteau à bouton et une perruque blanche. On voit une animation du chronomètre de marine H4. On dirait une montre de poche avec un cadran d’horloge à l’avant.)</p>
<p>Narrateur&nbsp; Le chronomètre d’Harrison a été testé pour la première fois sur le long terme par le capitaine James Cook qui l’a utilisé lors de ses deuxième et troisième voyages d’exploration de l’océan Pacifique qui ont duré plusieurs années.</p>
<p>Cook a été enchanté par l’instrument.</p>
<p>Puisque les explorateurs pouvaient désormais déterminer facilement leur position exacte en termes de latitude et de longitude, il est devenu possible pour Cook, et plus tard pour le capitaine Vancouver, de dessiner des cartes très précises. </p>
<p>(On voit le globe terrestre. Les lignes de latitude sont identifiées par (y). Les lignes de longitudes sont identifiées par (x)).</p>
<p>Narrateur&nbsp; Les tentatives précédentes de création de cartes sans connaître la position exacte des bateaux se révélaient être essentiellement un travail d’estimation. Regardez cette ancienne carte russe de la côte Nord-Ouest, et comparez-là maintenant avec celle-ci créée par le capitaine Vancouver.</p>
<p>(La carte russe montre une carte de l’Amérique du Nord avec très peu de détails et une zone côtières imprécise. La carte du capitaine Vancouver est très détaillée et inclue les différentes îles.)</p>
<p>Narrateur&nbsp; Les amers et les profondeurs océaniques le long de la côte pouvaient donc être enregistrés plus précisément que jamais auparavant en relevant leur position exacte selon une longitude x et une latitude y. Voici donc comment le capitaine Vancouver s’orientait en mer il y a de cela quelques centaines d’années!</p>