<p>Un navire européen du XVIIIe siècle était fait de différents types de bois.</p>
<p>La couple du vaisseau était faite de chêne blanc dû à sa solidité et à sa résistance à la moisissure.</p>
<p>Les ponts et la bordaille étaient faits de cèdre ou de sapin.</p>
<p>Quant à l’épinette de Sitka, elle était privilégiée pour les mâts et les espars puisqu’elle était plus susceptible de plier sans se briser dans les grands vents.</p>
<p>Un mât était «&nbsp;inséré&nbsp;» dans la quille, puis maintenu en place par des haubans et des étais faits de cordes de chanvre recouvertes de goudron.</p>
<p>Des vaisseaux du genre nécessitaient beaucoup d’entretien; l’équipage comptait donc un certain nombre de charpentiers. Les mâts et les espars devaient être remplacés régulièrement et les fuites étaient une préoccupation de tous les instants.</p>
<p>À l’époque de Vancouver, le fond du navire était gainé de cuivre afin de le protéger contre le taret commun, une espèce de bivalve d’eau salée qui creuse le bois. Le fond en cuivre permettait aussi au bateau de glisser plus vite sur l’eau.</p>
<p>Les vaisseaux européens étaient propulsés par le vent à l’aide d’une combinaison de voiles «&nbsp;carrées&nbsp;» à quatre côtés et de voiles «&nbsp;latines&nbsp;» triangulaires en toile.</p>
<p>Le design de ces vaisseaux était inspiré des bateaux vénitiens, romains et vikings qui naviguaient jadis le long des côtes européennes.</p>
<p>À partir du XVIe siècle, on a conçu de plus gros navires dotés de ponts fermés pour traverser l’océan. On préférait l’utilisation des voiles carrées pour les longues traversées car elles capturaient davantage de vent.</p>
<p>En contrepartie, un navire gréé de voiles carrées devaient idéalement naviguer par vent arrière ou latéral.</p>
<p>Comme les marins devaient s’aventurer dans les hauteurs pour changer les voiles, on avait besoin, dans ces navires, de gros équipages. Les chances étaient fortes de perdre un marin en mer après qu’il eût chuté du gréement. Malheureusement, il n’était pas toujours possible de faire demi-tour pour aller le chercher.</p>
<p>Le capitaine Vancouver avait à sa disposition deux navires pour son expédition : le navire de Sa Majesté Discovery (NSM Discovery pour faire court), ainsi que le NSM Chatham. Les deux navires étaient idéaux pour l’exploration; ils avaient un faible tirant d’eau, ce qui leur permettait de s’approcher du rivage. Ils disposaient également d’un fond légèrement arrondi, presque plat, ce qui faisait en sorte qu’ils étaient moins sujets à chavirer s’ils touchaient le fond, ce qui est très pratique pour naviguer dans des eaux inconnues!</p>
<p>Le Discovery mesurait environ 100 pieds de long par 28 pieds de large. Il était très similaire au bateau du capitaine Cook, le NSM Endeavour, et était conçu sur le modèle d’un charbonnier – un cargo destiné au transport du charbon. Ainsi, la coque était très solide et il y avait beaucoup d’espace sous le pont. Quant au Chatham, il faisait la moitié du Discovery et mesurait 53 pieds de long par 22 pieds de large.</p>
<p>En règle générale, plus la surface de la voilure est grande et plus le navire est long, plus il peut se déplacer rapidement. Le Discovery pouvait atteindre une vitesse maximale de 8 miles nautiques en une heure, ce qui équivaut à environ 15 km heure.</p>
<p>Le Chatham était un «&nbsp;brick&nbsp;», ce qui signifie qu’il était surtout gréé de voiles carrées sur deux mâts. Le Discovery était quand à lui un «&nbsp;navire à gréement complet&nbsp;», c’est-à-dire qu’il était surtout gréé de voiles carrées sur trois mâts.</p>
<p>Pour la marine britannique, ces navires étaient des «&nbsp;sloops de guerre&nbsp;», ce qui signifiait qu’ils étaient équipés de moins de 20 gros canons.</p>
<p>Le Discovery possédait 10 canons et le Chatham 4. En comparaison, un navire de guerre de premier ordre de la marine britannique possédait, à l’époque, plus de 100 gros canons et faisait plus ou moins le double de la longueur du Discovery.</p>
<p>Le Discovery disposait d’un équipage de 100 hommes dont 9 officiers de marine, 38 marins capables de naviguer, une force militaire composée de 16 fusiliers de la Marine, ainsi que des gens de métier tels des charpentiers, des voiliers, des cuisiniers, des serviteurs, des canonniers et un chirurgien. Le Chatham comptait avec un équipage de 45 hommes de composition similaire dont des officiers, des marins, des fusiliers et des gens de métier. On devait vivre très à l’étroit sur ces bateaux.</p>
<p>Pourquoi les voiles carrées sont-elles peu communes aujourd’hui?</p>
<p>À partir du XIXe siècle, les schooners à plusieurs mâts sont devenus de plus en plus populaires, surtout en tant que navires commerciaux et de pêche. Ils utilisaient des voiles auriques, c’est-à-dire que plutôt que d’avoir des voiles perpendiculaires au navire et fixées à des vergues, celles-ci étaient parallèles au bateau et fixées à une bôme.</p>
<p>Un équipage réduit pouvait manœuvrer un schooner puisque les voilent pouvaient être changées depuis le pont et qu’il n’était donc plus nécessaire de se hasarder dans les hauteurs. Les voiles auriques permettaient aussi au navire de naviguer au prêt, c’est-à-dire avec le vent frappant le bateau plus prêt de la proue, ce qui, ultimement, réduisait la durée du voyage.</p>
<p>Les voiliers modernes utilisent toujours une voile aurique. Ils disposent également de mâts de métal et de quilles plus longues, ce qui leur permet de supporter des mâts beaucoup plus gros.</p>
<p>Et contrairement aux vaisseaux du temps du capitaine Vancouver, les bateaux d’aujourd’hui sont habituellement équipés de beaucoup moins de canons.</p>