<p>&nbsp;(Au début de la vidéo, on entend une musique celtique entrainante avec du violon. On entend aussi le fracassement des vagues comme bruit de fond.)</p>
<p>Un narrateur dit : Dans quels types de vaisseaux naviguait le capitaine Vancouver?</p>
<p>(On voit une animation d’une coupe en trois dimensions d’un côté du NSM<em> Discovery. </em>Il s’agit d’un navire du XVIII<sup>è</sup> siècle avec 3 mâts et plusieurs voiles. La moitié inférieure du bateau est formée d’une coque brune arrondie. Une carène gris-brun longe l’avant et le fond de la coque, et le rectangle gris-brun sur le fond arrière est appelé gouvernail. Au-dessus de la coque se trouve le pont plat fait d’un bois d’un brun plus clair. Attaché à la coque, sous le pont, se trouvent des pièces de bois horizontales d’un brun clair appelées «&nbsp;espars&nbsp;». Plusieurs cordes verticales ainsi que des échelles de corde relient les espars aux mâts et aux voiles. À l’arrière du bateau se trouve une cabine fermées avec les seules fenêtres du navire.</p>
<p>Le navire compte trois mâts perpendiculaires au pont avec des voiles.</p>
<p>À l’avant du bateau, il y a une longue pièce de bois qui ressemble à un mât, mais qui sort du nez du navire dans un angle de 45 degrés par rapport au pont. Ceci est appelé un beaupré auquel sont attachées des voiles triangulaires.&nbsp;</p>
<p>Un grand drapeau, le <em>Red Ensign, </em>un pavillon arboré par la Marine britannique, flotte à l’arrière du bateau. Le drapeau est rouge avec un petit <em>Union Jack</em> dans le coin supérieur gauche.)</p>
<p>Narrateur&nbsp;: Un navire européen du XVIIIe siècle était fait de différents types de bois.</p>
<p>La couple du vaisseau était faite de chêne blanc dû à sa solidité et à sa résistance à la moisissure.</p>
<p>(L’image du bateau devient semi-transparente. La carène gris-brun, le gouvernail et la charpente du bateau sont opaques et mis en évidence pour montrer que ces éléments sont faits de chêne blanc.)&nbsp;</p>
<p>Narrateur&nbsp;: Les ponts et la bordaille étaient faits de cèdre ou de sapin.</p>
<p>(Le bateau devient de nouveau semi-transparent. Cette fois, la coque brune et le pont d’un brun plus clair sont opaques et mis en évidence pour montrer qu’ils sont faits de cèdre ou de sapin.)</p>
<p>Narrateur&nbsp;: Quant à l’épinette de Sitka, elle était privilégiée pour les mâts et les espars puisqu’elle était plus susceptible de plier sans se briser dans les grands vents.</p>
<p>(Le bateau devient de nouveau semi-transparent. Cette fois, les mâts, les espars et le beaupré à l’avant du navire sont opaques.)</p>
<p>Narrateur&nbsp;: Un mât était «&nbsp;inséré&nbsp;» dans la quille, puis maintenu en place par des haubans et des étais faits de cordes de chanvre recouvertes de goudron.</p>
<p>(Les planches latérales de la coque disparaissent, laissant voir la charpente du navire. Les mâts verticaux passent à travers le pont jusqu’à rejoindre le fond de la quille. La position des haubans n’est pas claire, mais un rouleau de corde de chanvre recouverte de goudron est montré comme exemple du matériel.)</p>
<p>Narrateur&nbsp;: Des vaisseaux du genre nécessitaient beaucoup d’entretien; l’équipage comptait donc un certain nombre de charpentiers.&nbsp;</p>
<p>(Un dessin en noir et blanc de cinq charpentiers apparait à l’écran.)</p>
<p>Narrateur&nbsp;: Les mâts et les espars devaient être remplacés régulièrement et les fuites étaient une préoccupation de tous les instants.</p>
<p>À l’époque de Vancouver, le fond du navire était gainé de cuivre afin de le protéger contre le taret commun, une espèce de bivalve d’eau salée qui creuse le bois. Le fond en cuivre permettait aussi au bateau de glisser plus vite sur l’eau.</p>
<p>(On voit une gaine de cuivre recouvrant la moitié inférieure de la coque. Le taret commun est un petit ver blanc et une photo montre les trous qu’il fait dans une pièce de bois.)&nbsp;</p>
<p>Narrateur&nbsp;: Les vaisseaux européens étaient propulsés par le vent à l’aide d’une combinaison de voiles «&nbsp;carrées&nbsp;» à quatre côtés et de voiles «&nbsp;latines&nbsp;» triangulaires en toile.</p>
<p>(Les voiles carrées sont attachées aux trois mâts verticaux (3 au mât avant, 3 au mât du milieu, 2 au mât arrière), et deux en bas du beaupré. Il y a 10 voiles carrées au total. Il y a quatre voiles latines triangulaires au total. Deux sont situées entre le beaupré et le mât avant et les deux autres entre les mâts avant et du milieu.)</p>
<p>Narrateur&nbsp;: Le design de ces vaisseaux était inspiré des bateaux vénitiens, romains et vikings qui naviguaient jadis le long des côtes européennes.</p>
<p>(Une ligne du temps des bateaux apparaît à l’écran. Elle inclut un knarr qui a un mât et une voile. Les bateaux suivants sur la ligne du temps sont&nbsp;: le koh (1180 EC), le kog (1250 EC), le caraque (1450 EC), le nao (1490 EC), le caraque vénitien (1500 EC), le galion anglais (1550 EC), et le galion espagnol (1550 EC). Avec le temps, les bateaux avaient de plus en plus de voiles, de mâts, et des coques plus creuses. Les galions rappellent le brick.)&nbsp;</p>
<p>Narrateur&nbsp;: À partir du XVIe siècle, on a conçu de plus gros navires dotés de ponts fermés pour traverser l’océan. On préférait l’utilisation des voiles carrées pour les longues traversées car elles capturaient davantage de vent.</p>
<p>En contrepartie, un navire gréé de voiles carrées devait idéalement naviguer par vent arrière ou latéral.</p>
<p>(Un graphique montre la façon dont le vent, selon sa direction, gonfle les voiles rectangulaires pour faire avancer le bateau. Les voiles rectangulaires peuvent être tournées légèrement vers la gauche ou vers la droite afin de mieux attraper le vent. Par exemple, si le vent venait de l’arrière du bateau, les voiles étaient tournées légèrement vers la gauche afin qu’une plus grande surface de l’arrière de la voile soit exposée au vent.)</p>
<p>Narrateur&nbsp;: Comme les marins devaient s’aventurer dans les hauteurs pour changer les voiles, on avait besoin, dans ces navires, de gros équipages. Les chances étaient fortes de perdre un marin en mer après qu’il eût chuté du gréement. Malheureusement, il n’était pas toujours possible de faire demi-tour pour aller le chercher.</p>
<p>(Il y a une animation montrant des marins grimpant dans une échelle de corde jusqu’au nid-de-pie tout en haut des mâts. Un marin tombe à l’eau.)</p>
<p>Narrateur&nbsp;: Le capitaine Vancouver avait à sa disposition deux navires pour son expédition;&nbsp;le navire de Sa Majesté <em>Discovery</em> (NSM <em>Discovery</em> pour faire court), ainsi que le NSM <em>Chatham</em>.&nbsp;</p>
<p>(On voit un bateau animé semblable au NSM <em>Chatham</em> à côté du NSM <em>Discovery</em>. Le NSM <em>Chatham</em> est deux fois plus petit, est plus court et a deux mâts plutôt que trois. Les voiles du <em>Chatham</em> sont aussi moitié moins grandes que celles du NSM <em>Discovery</em>).</p>
<p>Narrateur&nbsp;: Les deux navires étaient idéaux pour l’exploration; ils avaient un faible tirant d’eau, ce qui leur permettait de s’approcher du rivage.&nbsp;</p>
<p>(Le tirant d’eau est indiqué comme étant la distance verticale entre le fond de la coque et la surface de l’eau).&nbsp;</p>
<p>Narrateur&nbsp;: Ils disposaient également d’un fond légèrement arrondi, presque plat, ce qui faisait en sorte qu’ils étaient moins sujets à chavirer s’ils touchaient le fond, ce qui est très pratique pour naviguer dans des eaux inconnues!</p>
<p>Le <em>Discovery</em> mesurait environ 100 pieds de long par 28 pieds de large. Il était très similaire au bateau du capitaine Cook, le NSM <em>Endeavour</em>, et était conçu sur le modèle d’un charbonnier – un cargo destiné au transport du charbon. Ainsi, la coque était très solide et il y avait beaucoup d’espace sous le pont.&nbsp;</p>
<p>(Un dessin de l’intérieur de la coque montre les différents niveaux et de grands espaces ouverts.)</p>
<p>Narrateur&nbsp;: Quant au <em>Chatham</em>, il faisait la moitié du <em>Discovery</em> et mesurait 53 pieds de long par 22 pieds de large.</p>
<p>En règle générale, plus la surface de la voilure est grande et plus le navire est long, plus il peut se déplacer rapidement. Le <em>Discovery</em> pouvait atteindre une vitesse maximale de 8 miles nautiques en une heure, ce qui équivaut à environ 15 km heure.</p>
<p>Le <em>Chatham</em> était un «&nbsp;brick&nbsp;», ce qui signifie qu’il était surtout gréé de voiles carrées sur deux mâts. Le <em>Discovery</em> était quant à lui un «&nbsp;navire à gréement complet&nbsp;», c’est-à-dire qu’il était surtout gréé de voiles carrées sur trois mâts.</p>
<p>Pour la marine britannique, ces navires étaient des «&nbsp;sloops de guerre&nbsp;», ce qui signifiait qu’ils étaient équipés de moins de 20 gros canons.</p>
<p>Le <em>Discovery</em> possédait 10 canons et le <em>Chatham</em> 4. En comparaison, un navire de guerre de premier ordre de la marine britannique possédait, à l’époque, plus de 100 gros canons et faisait plus ou moins le double de la longueur du <em>Discovery</em>.</p>
<p>Narrateur&nbsp;: Le <em>Discovery</em> disposait d’un équipage de 100 hommes dont 9 officiers de marine, 38 marins capables de naviguer, une force militaire composée de 16 fusiliers de la Marine, ainsi que des gens de métier tels des charpentiers, des voiliers, des cuisiniers, des serviteurs, des canonniers et un chirurgien.&nbsp;</p>
<p>(Une infographie montre des figures de 8 charpentiers, 6 cuisiniers, 6 serviteurs et 10 canonniers. On voit aussi l’arrière du NSM <em>Discovery</em> avec le mot «&nbsp;Discovery&nbsp;» écrit en lettres dorées à l’arrière.)</p>
<p>Narrateur&nbsp;: Le <em>Chatham</em> comptait avec un équipage de 45 hommes de composition similaire dont des officiers, des marins, des fusiliers et des gens de métier. On devait vivre très à l’étroit sur ces bateaux.</p>
<p>(Une infographie adjacente au NSM <em>Chatham</em> montre les figures de 4 officiers, 18 marins, 6 fusiliers, 3 charpentiers, 3 voiliers, 3 cuisiniers, 3 serviteurs, 4 canonniers et 1 chirurgien. Le mot «&nbsp;Chatham&nbsp;» est aussi écrit en lettres dorées à l’arrière du bateau.)</p>
<p>Narrateur&nbsp;: Pourquoi les voiles carrées sont-elles peu communes aujourd’hui?</p>
<p>À partir du XIXe siècle, les schooners à plusieurs mâts sont devenus de plus en plus populaires, surtout en tant que navires commerciaux et de pêche. Ils utilisaient des voiles auriques, c’est-à-dire que plutôt que d’avoir des voiles perpendiculaires au navire et fixées à des vergues, celles-ci étaient parallèles au bateau et fixées à une bôme.</p>
<p>(On voit apparaître un schooner animé. Il semble très moderne comparé au NSM <em>Discovery</em>. La coque noire est longue et mince, et le pont est près de l’eau. Il y a quatre mâts, tous de la même hauteur. Chaque mât est gréé d’une grande voile blanche rectangulaire et d’une voile triangulaire plus petite près du sommet. Cinq voiles triangulaires sont attachées entre le beaupré et le premier mât. Il y a une autre voile blanche entre chaque set de mâts. Une bôme est identifiée comme une longue barre de bois perpendiculaire au bas du mât. Elle est le point d’ancrage du bas des grandes voiles rectangulaires.)</p>
<p>Narrateur&nbsp;: Un équipage réduit pouvait manœuvrer un schooner puisque les voilent pouvaient être changées depuis le pont et qu’il n’était donc plus nécessaire de se hasarder dans les hauteurs. Les voiles auriques permettaient aussi au navire de naviguer au prêt, c’est-à-dire avec le vent frappant le bateau plus prêt de la proue, ce qui, ultimement, réduisait la durée du voyage.</p>
<p>(Les voiles auriques sont les 5 voiles triangulaires à l’avant du bateau. Un graphique montre le vent venant de la direction opposée à la direction du bateau. Le vent atteint les voiles triangulaires en premier.)</p>
<p>Narrateur&nbsp;: Les voiliers modernes utilisent toujours une voile aurique. Ils disposent également de mâts de métal et de quilles plus longues, ce qui leur permet de supporter des voiles beaucoup plus grosses.</p>
<p>(Une animation d’un voilier moderne apparait à l’écran. Il a une longue coque avec une hauteur verticale très courte. Le pont est encore plus près de l’eau que celui du schooner. Il y a un mât central avec deux grandes voiles triangulaires droites qui y sont fixées. Il y a des cordes diagonales reliant le mât au pont.)</p>
<p>Le narrateur dit en rigolant&nbsp;: Et contrairement aux vaisseaux du temps du capitaine Vancouver, les bateaux d’aujourd’hui sont habituellement équipés de beaucoup moins de canons.</p>