<p>(As the video begins, there is gentle music, On-screen text appears: European Global Trade)</p>
<p>A narrator reads out a journal entry: “The evening of April the 29th brought us to an anchor in very thick rainy weather, about eight miles within the entrance on the southern shore of the supposed Straits of De Fuca. The following morning…a gentle breeze sprang up from the North West…which presented to our view this renowned inlet.” End of journal entry.</p>
<p>(The journal entry appears in cursive, overtop a painting of a ship.)</p>
<p>Narrator: Captain Vancouver came to the Pacific North West Coast in 1792 to complete the last in a series of European expeditions. Why were the Europeans undertaking these journeys? To understand that, we need to wind the clock back 400 years. For centuries trade with Asia for spices and cloth had gone along the Silk Road.</p>
<p>(The route of the Silk Road is drawn on a map of Eurasia, from China, over the north of India, into Europe.)</p>
<p>Narrator: To increase their profits, the Europeans began looking for a sea route.</p>
<p>(Map of the world shows arrows extending from Europe into the Atlantic Ocean with question marks around them.)</p>
<p>Narrator: Christopher Columbus thought he had found it when he sailed west in 1492 – although unknowingly, he had only reached the Caribbean. Vasco da Gama did make it to Asia when he sailed east around Africa to reach India in 1498. These explorers were willing to trade with the people they encountered but took what they wanted by force if necessary.</p>
<p>(Historical drawings and paintings depict European explorers with flags and heavily-armed crew members meeting Indigenous peoples.)</p>
<p>Narrator: Pope Alexander VI gave the Portuguese and Spanish the “God Given Right” to claim ownership of the new lands. At the Treaty of Tordesillas in 1494, they agreed to divide the new world between themselves. Portugal would have all lands East of the Cape Verde Islands and Spain all lands to the West.</p>
<p>(There is a map of the world south of Spain and Portugal. A white line vertically divides the world at 46 degrees latitude, cutting through the Atlantic Ocean and what is now Brazil. To the right of this line, Africa, Indonesia, Brazil, and a majority of Antarctica are shaded in green to represent the Pope’s 1494 declaration that these lands were claimed by Portugal. The southern USA, Central America, and the rest of South America and Antarctica are shaded in red for Spain.)</p>
<p>Narrator: With the Pope’s blessing, the Spanish and Portuguese explorers saw themselves as bringing the Christian religion to the people they encountered, whether they wanted it or not.</p>
<p>(Historical paintings and drawings of Spanish and Portuguese armies battling Indigenous communities. There are sounds of gunshots.)</p>
<p>Narrator: In Central and South America, the Spanish conquistadores conspired with rival indigenous groups to overwhelm the Aztec and Incan civilizations. The Spanish plundered gold and silver from these communities estimated at 11 billion dollars in today’s money. The Portuguese and Spanish also established sugar plantations in Brazil and in the Caribbean.</p>
<p>(A map shows what is now Brazil in green, representing what land was claimed by Portugal. Western and southern USA, Central America, the Caribbean, and the rest of South America are in red to represent what was claimed by Spain.)</p>
<p>Narrator: They enslaved the Indigenous populations to work in these plantations and sold the sugar at a huge profit in Europe.</p>
<p>(Graphic historical drawings of Indigenous peoples being tortured and enslaved and performing hard labour on sugar plantations.)</p>
<p>Narrator: Once the Indigenous populations were decimated, they traded with African Coastal tribes for enslaved African men, women and children to provide the labour they needed.</p>
<p>(An animated map of the lands around the Atlantic Ocean. The map first focuses on the west coast of Africa. The map shows icons of people near Liberia and down in Angola. Cape Coast, Ghana is labelled as “Gold Coast”. Red and green slave ship routes are drawn from the Gold Coast, across the Atlantic Ocean, to Spain and Portugal’s claimed lands in North and South America. Multiple historical drawings depicting the torture and living conditions on the slave ships are shown.)</p>
<p>Narrator: In the 17th century, Holland, Britain and France began to challenge Spain and Portugal’s control over trade with the New World. The Dutch took over the spice trade in the East Indies. The British established plantations and colonies in the Caribbean and along the east coast of North America.</p>
<p>(A map of North America highlights Britain’s land claims in purple. Belize, Jamaica, the Bahamas, the east coast of Nicaragua, the east coast of the USA, Nova Scotia, Newfoundland, and the lands surrounding the Hudson’s Bay are all highlighted purple.)</p>
<p>Narrator: In 1670 they established the Hudson’s Bay Fur Trading monopoly. France began trading in India, established plantations in the Caribbean, and the territory of New France with Quebec City at the centre.</p>
<p>(A map of North America highlights France’s land claims in blue. French Guiana, St. Lucia, Haiti, Quebec, New Brunswick, and most of Ontario, Manitoba, and central USA down to New Orleans are all highlighted blue. Much of western Canada and the USA remains grey, un-highlighted, representing no European claims yet.)</p>
<p>Narrator: By 1730, the European trading networks had become truly global, concentrating on an Atlantic trading triangle. Enslaved people became the core source of profit for all the European powers.</p>
<p>(On-screen text appears. The words “Manufactured goods” are in a text box centred at the top of the screen. The words “Plantation products” are in a text box at the bottom left of the screen. The words “Slaves” are in a text box at the bottom right of the screen. Lines connect these text boxes, creating the shape of a triangle. The words disappear, replaced by a map of the lands around the Atlantic Ocean. An arrow from Africa to South and North America is labelled “slaves”. A second arrow from North America to Europe is labelled “sugar, coffee, hides”. A third arrow from Europe to Africa is labelled “cloth, guns, cowries, rum”. The arrows create a triangular shape, reminiscent of the connected textboxes previously.)</p>
<p>Narrator: By the 18th century over 6.5 million Africans had been captured and transported. Life expectancy on the plantations was low. In the sugar plantations of Saint-Domingue, 30,000 enslaved Africans arrived annually; half of them would die within 3 to 8 years.</p>
<p>(Historical drawings of crowded living conditions on plantations, the brutal punishment of slaves, and slaves working on plantations surrounded.)</p>
<p>Narrator: The European powers fought over each other’s colonies in the 7 Years' War – the world’s first truly global conflict.</p>
<p>(Sounds of canons firing. Historical painting of large sailing ships battling at sea. One ship has all its masts and sails broken.)</p>
<p>Narrator: France lost Quebec City to the British in 1759 at the Battle of the Plains of Abraham. And consequently, gave up its North American territory to Britain and Spain in a peace treaty signed in Paris in 1763.</p>
<p>(A map of North America and Central America. All of Canada and the USA east of Saskatchewan is highlighted in purple, representing Britain. Central and southern USA, Mexico, and Central America are highlighted in red, representing Spain. The rest of North America remains grey, un-highlighted.)</p>
<p>Narrator: With their imperial dominance secure, the British commissioned the first of three expeditions to complete the mapping of the Pacific.</p>
<p>(A map of the world is shown. A white sailing route begins in Britain, sails south through the Atlantic Ocean, circumnavigating the southern hemisphere before returning north to Britain. The sailing route sails around New Zealand and along the east coast of Australia. This route is very jagged. This route represents Captain Cook’s circumnavigation around the world.)</p>
<p>Narrator: And ideally find a faster sea route to Asia through North America – the Northwest Passage.</p>
<p>(On the same map, a number of routes appear across North America, dotted by question marks and the on-screen text “The Northwest Passage”.)</p>
<p>Narrator: The expedition was led by Captain James Cook, a skilled mapmaker and navigator. Over seven years and two expeditions, Cook drew the first maps of Australia, New Zealand and the Pacific Islands. He also confirmed that, other than Antarctica, there were no other southern continents.</p>
<p>(A painting of Captain Cook shows him with grey hair, in a blue and white buttoned navy uniform, and holding a telescope and tricorn triangular hat. Overtop Captain Cook’s white sailing route, a red sailing route is drawn to represent Cook’s second voyage. The red route begins again in Britain, sails closer to Antarctica travelling east. It passes around New Zealand, and circles the Pacific Ocean a couple of times before returning to Britain.)</p>
<p>Narrator: In the age of colonial conquest, maps were an important source of wealth. Indigenous territories became unrecorded blank spaces which the Europeans would claim as their own.</p>
<p>(A map shows Australia, New Zealand, Vanuatu, and New Caledonia highlighted in purple, representing that they were claimed by the British.)</p>
<p>Narrator: Cook’s expeditions were sponsored by the Royal Society – a British Scientific Academy. In addition to maps, these expeditions returned with carefully documented information provided by scientists and artists about the people they met and the plants and animals they encountered.</p>
<p>(A book with the ornate Royal Society logo as the cover, opens to show drawings of animals, such as a penguin and kangaroo, of Indigenous peoples with face tattoos, and of fruit trees.)</p>
<p>Narrator: Official journals were published and widely read by the general public. Cook became a national hero. With mapping of the Southern Pacific complete, would Cook now complete his mission and return to find the Northwest Passage?</p>
