<?php
$content = [
    [
        "front-text" => "What did Vancouver's expedition actually achieve?",
        "back-text" => "",
        "content" => '<iframe id="vimeo1" class="no-js-hide vimeo" title="European Navigation Video" src="https://player.vimeo.com/video/356042135?color=ee314a&title=0&byline=0&portrait=0&speed=1&playsinline=true" allow="autoplay; fullscreen" allowfullscreen></iframe>',
        "no-js" => '<video preload="none" src="/videos/placeholder-example.mp4">
                        <track kind="captions" src="/videos/placeholder-example.vtt" srclang="en" label="English">
                        <track kind="captions" src="/videos/placeholder-example.vtt" srclang="fr" label="French">
                    </video>
                    <a class="download_video" href="/videos/placeholder-example.mp4" download="/videos/placeholder-example.mp4">Download Video</a>',
        "transcript" => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Bibendum arcu vitae elementum curabitur. Vitae proin sagittis nisl rhoncus mattis. Est pellentesque elit ullamcorper dignissim cras tincidunt. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Pharetra et ultrices neque ornare aenean euismod. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Faucibus ornare suspendisse sed nisi lacus sed viverra. Potenti nullam ac tortor vitae purus. Felis eget nunc lobortis mattis. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Sem et tortor consequat id porta nibh. Potenti nullam ac tortor vitae purus. Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Etiam non quam lacus suspendisse.</p>
        <p>Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Dictumst quisque sagittis purus sit amet volutpat. Quis imperdiet massa tincidunt nunc pulvinar. Ut lectus arcu bibendum at varius vel pharetra. Non nisi est sit amet. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Sem viverra aliquet eget sit. Nunc sed id semper risus in hendrerit gravida rutrum. Ut aliquam purus sit amet luctus venenatis lectus. Senectus et netus et malesuada fames ac turpis egestas. Ut venenatis tellus in metus vulputate. Amet volutpat consequat mauris nunc. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Lacus viverra vitae congue eu consequat ac felis donec. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Sit amet commodo nulla facilisi nullam vehicula.</p>
        <p>In aliquam sem fringilla ut morbi tincidunt augue interdum. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Quis varius quam quisque id diam vel quam elementum. Sed risus pretium quam vulputate dignissim suspendisse in est. Faucibus turpis in eu mi bibendum neque egestas congue quisque. In fermentum posuere urna nec tincidunt praesent semper. Duis at consectetur lorem donec massa sapien faucibus et molestie. Nisl pretium fusce id velit ut tortor pretium viverra. Tellus orci ac auctor augue mauris augue neque gravida in. Lectus urna duis convallis convallis tellus id interdum. Pharetra pharetra massa massa ultricies. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. Mauris augue neque gravida in fermentum.</p>
        <p>Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Ut sem viverra aliquet eget sit amet. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Adipiscing tristique risus nec feugiat in fermentum posuere urna. Sit amet purus gravida quis blandit turpis cursus in. Turpis in eu mi bibendum neque egestas. Eleifend mi in nulla posuere sollicitudin aliquam. Nulla facilisi cras fermentum odio eu feugiat pretium. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Purus gravida quis blandit turpis cursus in hac habitasse platea. Et malesuada fames ac turpis egestas maecenas. Quis risus sed vulputate odio ut.</p>
        <p>Vulputate mi sit amet mauris commodo. Vivamus arcu felis bibendum ut tristique. Tortor pretium viverra suspendisse potenti nullam. Sed libero enim sed faucibus turpis in eu mi. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Sed id semper risus in hendrerit gravida rutrum quisque non. Felis eget velit aliquet sagittis id consectetur purus ut. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Nunc pulvinar sapien et ligula. Sed elementum tempus egestas sed sed risus pretium. Lobortis scelerisque fermentum dui faucibus in ornare quam. Hendrerit gravida rutrum quisque non. Pharetra convallis posuere morbi leo urna. Nunc sed augue lacus viverra vitae congue eu consequat. Pellentesque habitant morbi tristique senectus et netus. Ultrices eros in cursus turpis massa tincidunt dui. Mus mauris vitae ultricies leo integer malesuada nunc vel. Scelerisque eu ultrices vitae auctor eu augue ut.</p>'
    ],
    [
        "front-text" => "What was it like to be a member of Vancouver's crew?",
        "back-text" => "",
        "content" => '<iframe id="vimeo2" class="no-js-hide vimeo" title="European Navigation Video" src="https://player.vimeo.com/video/356042135?color=ee314a&title=0&byline=0&portrait=0&speed=1&playsinline=true" allow="autoplay; fullscreen" allowfullscreen></iframe>',
        "transcript" => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Bibendum arcu vitae elementum curabitur. Vitae proin sagittis nisl rhoncus mattis. Est pellentesque elit ullamcorper dignissim cras tincidunt. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Pharetra et ultrices neque ornare aenean euismod. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Faucibus ornare suspendisse sed nisi lacus sed viverra. Potenti nullam ac tortor vitae purus. Felis eget nunc lobortis mattis. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Sem et tortor consequat id porta nibh. Potenti nullam ac tortor vitae purus. Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Etiam non quam lacus suspendisse.</p>
        <p>Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Dictumst quisque sagittis purus sit amet volutpat. Quis imperdiet massa tincidunt nunc pulvinar. Ut lectus arcu bibendum at varius vel pharetra. Non nisi est sit amet. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Sem viverra aliquet eget sit. Nunc sed id semper risus in hendrerit gravida rutrum. Ut aliquam purus sit amet luctus venenatis lectus. Senectus et netus et malesuada fames ac turpis egestas. Ut venenatis tellus in metus vulputate. Amet volutpat consequat mauris nunc. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Lacus viverra vitae congue eu consequat ac felis donec. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Sit amet commodo nulla facilisi nullam vehicula.</p>
        <p>In aliquam sem fringilla ut morbi tincidunt augue interdum. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Quis varius quam quisque id diam vel quam elementum. Sed risus pretium quam vulputate dignissim suspendisse in est. Faucibus turpis in eu mi bibendum neque egestas congue quisque. In fermentum posuere urna nec tincidunt praesent semper. Duis at consectetur lorem donec massa sapien faucibus et molestie. Nisl pretium fusce id velit ut tortor pretium viverra. Tellus orci ac auctor augue mauris augue neque gravida in. Lectus urna duis convallis convallis tellus id interdum. Pharetra pharetra massa massa ultricies. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. Mauris augue neque gravida in fermentum.</p>
        <p>Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Ut sem viverra aliquet eget sit amet. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Adipiscing tristique risus nec feugiat in fermentum posuere urna. Sit amet purus gravida quis blandit turpis cursus in. Turpis in eu mi bibendum neque egestas. Eleifend mi in nulla posuere sollicitudin aliquam. Nulla facilisi cras fermentum odio eu feugiat pretium. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Purus gravida quis blandit turpis cursus in hac habitasse platea. Et malesuada fames ac turpis egestas maecenas. Quis risus sed vulputate odio ut.</p>
        <p>Vulputate mi sit amet mauris commodo. Vivamus arcu felis bibendum ut tristique. Tortor pretium viverra suspendisse potenti nullam. Sed libero enim sed faucibus turpis in eu mi. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Sed id semper risus in hendrerit gravida rutrum quisque non. Felis eget velit aliquet sagittis id consectetur purus ut. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Nunc pulvinar sapien et ligula. Sed elementum tempus egestas sed sed risus pretium. Lobortis scelerisque fermentum dui faucibus in ornare quam. Hendrerit gravida rutrum quisque non. Pharetra convallis posuere morbi leo urna. Nunc sed augue lacus viverra vitae congue eu consequat. Pellentesque habitant morbi tristique senectus et netus. Ultrices eros in cursus turpis massa tincidunt dui. Mus mauris vitae ultricies leo integer malesuada nunc vel. Scelerisque eu ultrices vitae auctor eu augue ut.</p>'
    ],
    [
        "front-text" => "What were the Indigenous people and the Europeans first meetings like?",
        "back-text" => "",
        "content" => '<iframe id="vimeo3" class="no-js-hide vimeo" title="European Navigation Video" src="https://player.vimeo.com/video/356042135?color=ee314a&title=0&byline=0&portrait=0&speed=1&playsinline=true" allow="autoplay; fullscreen" allowfullscreen></iframe>',
        "transcript" => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Bibendum arcu vitae elementum curabitur. Vitae proin sagittis nisl rhoncus mattis. Est pellentesque elit ullamcorper dignissim cras tincidunt. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Pharetra et ultrices neque ornare aenean euismod. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Faucibus ornare suspendisse sed nisi lacus sed viverra. Potenti nullam ac tortor vitae purus. Felis eget nunc lobortis mattis. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Sem et tortor consequat id porta nibh. Potenti nullam ac tortor vitae purus. Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Etiam non quam lacus suspendisse.</p>
        <p>Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Dictumst quisque sagittis purus sit amet volutpat. Quis imperdiet massa tincidunt nunc pulvinar. Ut lectus arcu bibendum at varius vel pharetra. Non nisi est sit amet. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Sem viverra aliquet eget sit. Nunc sed id semper risus in hendrerit gravida rutrum. Ut aliquam purus sit amet luctus venenatis lectus. Senectus et netus et malesuada fames ac turpis egestas. Ut venenatis tellus in metus vulputate. Amet volutpat consequat mauris nunc. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Lacus viverra vitae congue eu consequat ac felis donec. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Sit amet commodo nulla facilisi nullam vehicula.</p>
        <p>In aliquam sem fringilla ut morbi tincidunt augue interdum. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Quis varius quam quisque id diam vel quam elementum. Sed risus pretium quam vulputate dignissim suspendisse in est. Faucibus turpis in eu mi bibendum neque egestas congue quisque. In fermentum posuere urna nec tincidunt praesent semper. Duis at consectetur lorem donec massa sapien faucibus et molestie. Nisl pretium fusce id velit ut tortor pretium viverra. Tellus orci ac auctor augue mauris augue neque gravida in. Lectus urna duis convallis convallis tellus id interdum. Pharetra pharetra massa massa ultricies. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. Mauris augue neque gravida in fermentum.</p>
        <p>Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Ut sem viverra aliquet eget sit amet. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Adipiscing tristique risus nec feugiat in fermentum posuere urna. Sit amet purus gravida quis blandit turpis cursus in. Turpis in eu mi bibendum neque egestas. Eleifend mi in nulla posuere sollicitudin aliquam. Nulla facilisi cras fermentum odio eu feugiat pretium. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Purus gravida quis blandit turpis cursus in hac habitasse platea. Et malesuada fames ac turpis egestas maecenas. Quis risus sed vulputate odio ut.</p>
        <p>Vulputate mi sit amet mauris commodo. Vivamus arcu felis bibendum ut tristique. Tortor pretium viverra suspendisse potenti nullam. Sed libero enim sed faucibus turpis in eu mi. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Sed id semper risus in hendrerit gravida rutrum quisque non. Felis eget velit aliquet sagittis id consectetur purus ut. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Nunc pulvinar sapien et ligula. Sed elementum tempus egestas sed sed risus pretium. Lobortis scelerisque fermentum dui faucibus in ornare quam. Hendrerit gravida rutrum quisque non. Pharetra convallis posuere morbi leo urna. Nunc sed augue lacus viverra vitae congue eu consequat. Pellentesque habitant morbi tristique senectus et netus. Ultrices eros in cursus turpis massa tincidunt dui. Mus mauris vitae ultricies leo integer malesuada nunc vel. Scelerisque eu ultrices vitae auctor eu augue ut.</p>'
    ]
];
