<p>(Au d&eacute;but de la vid&eacute;o on entend une musique douce, et le texte suivant appara&icirc;t &agrave; l&rsquo;&eacute;cran : <em>Le commerce international europ&eacute;en</em>)</p>
<p>Un narrateur lit une inscription dans un journal de bord&nbsp;: &laquo;&nbsp;Le soir du 29 avril, nous avons jet&eacute; l&rsquo;ancre &agrave; environ huit miles de l&rsquo;entr&eacute;e, sur la rive sud de ce que nous supposions &ecirc;tre le d&eacute;troit de Fuca, sous une pluie tr&egrave;s dense. Le lendemain matin&hellip; une faible brise soufflait du nord-ouest&hellip; et ce fameux bras de mer s&rsquo;&eacute;talait &agrave; notre vue.&nbsp;&raquo; Fin de l&rsquo;entr&eacute;e du journal.</p>
<p>(L&rsquo;inscription du journal appara&icirc;t en &eacute;criture cursive, superpos&eacute;e au tableau d&rsquo;un bateau.)</p>
<p>Narrateur&nbsp;: Le capitaine Vancouver est arriv&eacute; sur la c&ocirc;te nord-ouest du Pacifique en 1792 afin de compl&eacute;ter la derni&egrave;re d&rsquo;une s&eacute;rie d&rsquo;exp&eacute;ditions europ&eacute;ennes. Pour quelles raisons est-ce que les Europ&eacute;ens entreprenaient-ils de tels voyages? Afin de le savoir, il faut remonter 400 ans en arri&egrave;re. Pendant des si&egrave;cles, le commerce avec l&rsquo;Asie pour se procurer des &eacute;pices et des tissus empruntait la route de la soie.</p>
<p>(Le trajet de la route de la soie se dessine sur une carte de l&rsquo;Eurasie &agrave; partir de la Chine, en passant par le nord de l&rsquo;Inde, pour arriver en Europe.)</p>
<p>Narrateur&nbsp;: Afin d&rsquo;accro&icirc;tre leurs profits, les Europ&eacute;ens se sont mis &agrave; chercher un passage maritime.&nbsp;</p>
<p>(Carte du monde montrant des fl&egrave;ches partant de l&rsquo;Europe et prenant diff&eacute;rentes directions dans l&rsquo;oc&eacute;an Atlantique, entour&eacute;es de points d&rsquo;interrogation.)</p>
<p>Narrateur&nbsp;: Christophe Colomb a cru qu&rsquo;il avait trouv&eacute; la voie lorsqu&rsquo;il navigua vers l&rsquo;ouest en 1492 &ndash; bien que sans le savoir, il n&rsquo;avait fait que rejoindre les Cara&iuml;bes. Vasco de Gama, quant &agrave; lui, s&rsquo;est bien rendu en Asie en naviguant vers l&rsquo;est, en contournant l&rsquo;Afrique pour rejoindre l&rsquo;Inde, en 1498. Ces explorateurs faisaient volontiers du commerce avec les gens qu&rsquo;ils rencontraient, mais prenaient aussi ce qu&rsquo;ils d&eacute;siraient de force, si n&eacute;cessaire.</p>
<p>(Des dessins et des peintures d&rsquo;&eacute;poque montrent des explorateurs europ&eacute;ens tenant des drapeaux et accompagn&eacute;s de soldats lourdement arm&eacute;s, allant &agrave; la rencontre de peuples autochtones.)</p>
<p>Narrateur&nbsp;: Le pape Alexandre VI accorda au Portugal et &agrave; l&rsquo;Espagne le &laquo;&nbsp;droit divin&nbsp;&raquo; de prendre possession des nouveaux territoires. Lors de la signature du trait&eacute; de Tordesillas, en 1494, ils se sont entendus pour diviser le Nouveau Monde entre eux. Le Portugal avait toutes les terres &agrave; l&rsquo;est des &icirc;les du Cap-Vert tandis que l&rsquo;Espagne se r&eacute;servait celles &agrave; l&rsquo;ouest de celles-ci.</p>
<p>(On voit une carte du monde au sud de l&rsquo;Espagne et du Portugal. Une ligne verticale blanche divise le monde au 46<sup>&egrave;me</sup> degr&eacute; de latitude, traversant l&rsquo;oc&eacute;an Atlantique et ce qui est aujourd&rsquo;hui le Br&eacute;sil. &Agrave; droite de cette ligne, l&rsquo;Afrique, l&rsquo;Indon&eacute;sie, le Br&eacute;sil et la majorit&eacute; de l&rsquo;Antarctique sont color&eacute;s en vert pour repr&eacute;senter la d&eacute;claration papale de 1494 attribuant ces terres au Portugal. Le sud des &Eacute;tats-Unis, l&rsquo;Am&eacute;rique centrale et le reste de l&rsquo;Am&eacute;rique du Sud et de l&rsquo;Antarctique sont color&eacute;s en rouge pour l&rsquo;Espagne.)</p>
<p>Narrateur&nbsp;: Avec la b&eacute;n&eacute;diction du pape, les explorateurs espagnols et portugais se voyaient comme des &eacute;missaires envoy&eacute;s pour convertir les gens qu&rsquo;ils rencontraient &agrave; la religion catholique, qu&rsquo;ils le veuillent ou non.&nbsp;</p>
<p>(Peintures et dessins d&rsquo;&eacute;poque repr&eacute;sentant des arm&eacute;es espagnoles et portugaises en guerre contre les communaut&eacute;s autochtones. On entend des coups de feu.)</p>
<p>Narrateur&nbsp;: En Am&eacute;rique centrale et du Sud, les conquistadores espagnols ont conspir&eacute; avec des groupes autochtones rivaux pour d&eacute;truire les civilisations azt&egrave;ques et incas. Les Espagnols ont vol&eacute; de l&rsquo;or et de l&rsquo;argent &agrave; ces communaut&eacute;s pour une valeur estim&eacute;e &agrave; 11 milliards de dollars en argent d&rsquo;aujourd&rsquo;hui. Les Portugais et les Espagnols ont aussi &eacute;tabli des plantations de canne &agrave; sucre au Br&eacute;sil et dans les Cara&iuml;bes.</p>
<p>(Une carte montre, en vert, ce qui est aujourd&rsquo;hui le Br&eacute;sil, repr&eacute;sentant les terres revendiqu&eacute;es par le Portugal, alors que l&rsquo;ouest et le sud des &Eacute;tats-Unis, l&rsquo;Am&eacute;rique centrale, les Cara&iuml;bes et le reste de l&rsquo;Am&eacute;rique du Sud sont en rouge, pour repr&eacute;senter ce que revendiquait l&rsquo;Espagne.)</p>
<p>Narrateur&nbsp;: Ils ont r&eacute;duit les populations autochtones &agrave; l&rsquo;esclavage dans ces plantations et vendu le sucre avec d&rsquo;&eacute;norme profits en Europe.</p>
<p>(Dessins graphiques d&rsquo;&eacute;poque d&rsquo;Autochtones se faisant torturer, r&eacute;duits &agrave; l&rsquo;esclavage et travaillant dans des conditions difficiles dans des plantations de canne &agrave; sucre.)</p>
<p>Narrateur&nbsp;: Quand les populations autochtones ont &eacute;t&eacute; d&eacute;cim&eacute;es, ils ont fait le commerce d&rsquo;esclaves avec des tribus c&ocirc;ti&egrave;res africaines afin de se procurer les esclaves, hommes, femmes et enfants, dont ils avaient besoin pour combler le besoin en main d&rsquo;&oelig;uvre.</p>
<p>(Une carte anim&eacute;e des terres autour de l&rsquo;oc&eacute;an Atlantique. La carte fait d&rsquo;abord un zoom sur la c&ocirc;te ouest de l&rsquo;Afrique. On y voit des ic&ocirc;nes repr&eacute;sentant plusieurs personnes pr&egrave;s du Lib&eacute;ria et plus au sud jusqu&rsquo;en Angola. Cape Coast, au Ghana, est identifi&eacute;e comme &laquo;&nbsp;c&ocirc;te de l&rsquo;Or&nbsp;&raquo;. Des routes de navigation de bateaux n&eacute;griers sont dessin&eacute;es en rouge et en vert &agrave; partir de la c&ocirc;te de l&rsquo;Or, puis traversant l&rsquo;oc&eacute;an Atlantique jusqu&rsquo;aux terres revendiqu&eacute;es par l&rsquo;Espagne et le Portugal en Am&eacute;rique du Nord et du Sud. On voit diff&eacute;rents dessins d&rsquo;&eacute;poque repr&eacute;sentant la torture et les conditions de vie sur les bateaux n&eacute;griers.)</p>
<p>Narrateur&nbsp;: Au XVII<sup>&egrave;me</sup> si&egrave;cle, la Hollande, la Grande-Bretagne et la France ont commenc&eacute; &agrave; remettre en question le contr&ocirc;le par l&rsquo;Espagne et le Portugal du commerce avec le Nouveau Monde. Les Hollandais ont mis la main sur le commerce des &eacute;pices avec les Indes orientales, tandis que les Britanniques ont &eacute;tabli des plantations et des colonies dans les Cara&iuml;bes et le long de la c&ocirc;te est de l&rsquo;Am&eacute;rique du Nord.</p>
<p>(Une carte de l&rsquo;Am&eacute;rique du Nord montre les terres revendiqu&eacute;es par les Britanniques en mauve. Le B&eacute;lize, la Jama&iuml;que, les Bahamas, la c&ocirc;te est du Nicaragua, la c&ocirc;te est des &Eacute;tats-Unis, la Nouvelle-&Eacute;cosse, Terre-Neuve ainsi que les terres autour de la baie d&rsquo;Hudson sont toutes color&eacute;es en mauve.)</p>
<p>Narrateur&nbsp;: En 1670, ils &eacute;tablirent le monopole de la traite des fourrures de la Compagnie de la Baie d&rsquo;Hudson. La France se mit &agrave; faire du commerce en Inde, a &eacute;tabli des plantations dans les Cara&iuml;bes ainsi que le territoire de la Nouvelle-France avec en son centre la ville de Qu&eacute;bec.</p>
<p>(Une carte de l&rsquo;Am&eacute;rique du Nord montre les revendications territoriales de la France en bleu. La Guyane fran&ccedil;aise, Sainte-Lucie, Ha&iuml;ti, Qu&eacute;bec, le Nouveau-Brunswick, presque tout l&rsquo;Ontario, le Manitoba et le centre des &Eacute;tats-Unis jusqu&rsquo;&agrave; la Nouvelle-Orl&eacute;ans sont color&eacute;s en bleu. Une grande partie de l&rsquo;ouest du Canada et des &Eacute;tats-Unis sont en gris, sans couleur, ce qui signifie qu&rsquo;il n&rsquo;y a toujours pas de revendications territoriales europ&eacute;ennes.)</p>
<p>Narrateur&nbsp;: En 1730, les r&eacute;seaux commerciaux europ&eacute;ens &eacute;taient vraiment devenus mondiaux, et se concentraient sur un triangle commercial dans l&rsquo;Atlantique. Les esclaves &eacute;taient la principale source de profits pour toutes les puissances europ&eacute;ennes.&nbsp;</p>
<p>(Du texte appara&icirc;t &agrave; l&rsquo;&eacute;cran. Les mots &laquo;&nbsp;Biens manufactur&eacute;s&nbsp;&raquo; apparaissent dans une bo&icirc;te au centre en haut de l&rsquo;&eacute;cran. Les mots &laquo;&nbsp;Produits des plantations&nbsp;&raquo; apparaissent dans une bo&icirc;te en bas &agrave; gauche de l&rsquo;&eacute;cran. Les mots &laquo;&nbsp;Esclaves&nbsp;&raquo; sont dans une bo&icirc;te en bas &agrave; droite de l&rsquo;&eacute;cran. Des lignes relient ces bo&icirc;tes de texte, cr&eacute;ant la forme d&rsquo;un triangle. Les mots disparaissent, remplac&eacute;s par une carte des terres autour de l&rsquo;oc&eacute;an Atlantique. Une fl&egrave;che partant de l&rsquo;Afrique et allant jusqu&rsquo;en Am&eacute;rique du Sud et du Nord est identifi&eacute;e par le mot &laquo;&nbsp;esclaves&nbsp;&raquo;. Une seconde fl&egrave;che partant de l&rsquo;Am&eacute;rique du Nord et allant jusqu&rsquo;en Europe est identifi&eacute;e par les mots &laquo;&nbsp;sucre, caf&eacute;, peaux&nbsp;&raquo;. Une troisi&egrave;me fl&egrave;che partant de l&rsquo;Europe et allant en Afrique est identifi&eacute;e par les mots &laquo;&nbsp;v&ecirc;tements, fusils, cauris et rhum&nbsp;&raquo;. Les fl&egrave;ches forment un triangle rappelant les bo&icirc;tes de texte interreli&eacute;es pr&eacute;c&eacute;dentes.)</p>
<p>Narrateur&nbsp;: Au XVIII<sup>&egrave;me</sup> si&egrave;cle, plus de 6,5 millions d&rsquo;Africains avaient &eacute;t&eacute; captur&eacute;s et transport&eacute;s. L&rsquo;esp&eacute;rance de vie sur les plantations &eacute;tait courte. Sur les plantations de canne &agrave; sucre de Saint-Domingue, 30 000 esclaves africains arrivaient chaque ann&eacute;e; la moiti&eacute; d&rsquo;entre eux mouraient &agrave; l&rsquo;int&eacute;rieur de trois &agrave; huit ans.</p>
<p>(Des dessins d&rsquo;&eacute;poque des conditions de vie dans des structures surpeupl&eacute;es sur les plantations, de punitions brutales des esclaves et d&rsquo;esclaves travaillant dans des plantations.)</p>
<p>Narrateur&nbsp;: Les puissances europ&eacute;ennes se sont disput&eacute;es leurs colonies respectives pendant la guerre de Sept Ans, premier conflit pouvant &ecirc;tre qualifi&eacute; de guerre mondiale.</p>
<p>(Bruits de coups de canon. Peintures d&rsquo;&eacute;poque de gros bateaux &agrave; voile livrant bataille en mer. Un des bateaux a toutes ses voiles et ses m&acirc;ts bris&eacute;s.)</p>
<p>Narrateur&nbsp;: La France perdit la ville de Qu&eacute;bec aux mains des Britanniques en 1759 lors de la bataille des plaines d&rsquo;Abraham. Elle a cons&eacute;quemment c&eacute;d&eacute; son territoire nord-am&eacute;ricain &agrave; la Grande-Bretagne et &agrave; l&rsquo;Espagne lors d&rsquo;un trait&eacute; de paix sign&eacute; &agrave; Paris en 1763.&nbsp;</p>
<p>(Carte de l&rsquo;Am&eacute;rique du Nord et de l&rsquo;Am&eacute;rique centrale. Tout le Canada et les &Eacute;tats-Unis &agrave; l&rsquo;est de la Saskatchewan est color&eacute; en mauve, repr&eacute;sentant les territoires britanniques. Le centre et le sud des &Eacute;tats-Unis, le Mexique et l&rsquo;Am&eacute;rique centrale sont en rouge, pour l&rsquo;Espagne. Le reste de l&rsquo;Am&eacute;rique du Nord est toujours en gris, donc sans couleur.)</p>
<p>Narrateur&nbsp;: Avec leur domination imp&eacute;riale ainsi s&eacute;curis&eacute;e, les Britanniques financ&egrave;rent la premi&egrave;re des trois exp&eacute;ditions d&eacute;di&eacute;es &agrave; la cartographie du Pacifique.&nbsp;</p>
<p>(On voit une carte du monde. Une route de navigation dessin&eacute;e en blanc part de la Grande-Bretagne, navigue &agrave; travers l&rsquo;oc&eacute;an Atlantique, contourne l&rsquo;h&eacute;misph&egrave;re sud avant de retourner vers le nord jusqu&rsquo;en Grande-Bretagne. La route de navigation fait le tour de la Nouvelle-Z&eacute;lande et longe la c&ocirc;te est de l&rsquo;Australie. Cet itin&eacute;raire est tr&egrave;s irr&eacute;gulier. Il s&rsquo;agit du tour du monde en bateau effectu&eacute; par le capitaine Cook.)</p>
<p>Narrateur&nbsp;: Et id&eacute;alement trouver une route de navigation plus rapide vers l&rsquo;Asie &agrave; travers l&rsquo;Am&eacute;rique du Nord; le passage du Nord-Ouest.</p>
<p>(Sur la m&ecirc;me carte, plusieurs trajets apparaissent &agrave; travers l&rsquo;Am&eacute;rique du Nord, marqu&eacute;s de points d&rsquo;interrogation et par le texte &laquo;&nbsp;Passage du Nord-Ouest&nbsp;&raquo;.)</p>
<p>Narrateur&nbsp;: L&rsquo;exp&eacute;dition &eacute;tait men&eacute;e par le capitaine James Cook, cartographe et navigateur exp&eacute;riment&eacute;. En sept ans et deux exp&eacute;ditions, Cook dessina les premi&egrave;res cartes de l&rsquo;Australie, de la Nouvelle-Z&eacute;lande et des &icirc;les du Pacifique. Il confirma &eacute;galement qu&rsquo;il n&rsquo;existait pas d&rsquo;autre continent plus au sud, outre l&rsquo;Antarctique.&nbsp;</p>
<p>(Une peinture du capitaine Cook le montre avec des cheveux gris et v&ecirc;tu d&rsquo;un uniforme de marine bleu et blanc &agrave; boutonni&egrave;re, tenant un t&eacute;lescope dans une main et un tricorne dans l&rsquo;autre. Au-dessus la route de navigation du capitaine Cook dessin&eacute;e en blanc, une route de navigation marqu&eacute;e d&rsquo;un trait rouge se dessine pour repr&eacute;senter le second voyage de Cook. Le trajet en rouge part encore de la Grande-Bretagne, et navigue vers l&rsquo;est, plus pr&egrave;s de l&rsquo;Antarctique. Il passe autour de la Nouvelle-Z&eacute;lande et fait le tour de l&rsquo;oc&eacute;an Pacifique &agrave; deux reprises avant de retourner en Grande-Bretagne.)</p>
<p>Narrateur&nbsp;: &Agrave; l&rsquo;&egrave;re des conqu&ecirc;tes coloniales, les cartes &eacute;taient une importante source de richesse. Les territoires autochtones devenaient des espaces vides non-r&eacute;pertori&eacute;s que les Europ&eacute;ens revendiqueraient comme les leurs.</p>
<p>(Une carte montre l&rsquo;Australie, la Nouvelle-Z&eacute;lande, le Vanuatu et la Nouvelle-Cal&eacute;donie en mauve, montrant ainsi que ces territoires &eacute;taient revendiqu&eacute;s par les Britanniques.)</p>
<p>Narrateur&nbsp;: Les exp&eacute;ditions de Cook &eacute;taient financ&eacute;es par The Royal Society, une acad&eacute;mie scientifique britannique. En plus des cartes, ces exp&eacute;ditions revenaient riches d&rsquo;informations d&eacute;taill&eacute;es document&eacute;es par des scientifiques et des artistes &agrave; propos des peuples qu&rsquo;ils rencontraient et des plantes et des animaux qu&rsquo;ils voyaient.</p>
<p>(Un livre dont la couverture est orn&eacute;e du logo de la Royal Society s&rsquo;ouvre pour montrer des dessins d&rsquo;animaux comme un pingouin et un kangourou, d&rsquo;Autochtones au visage tatou&eacute;, et d&rsquo;arbres fruitiers.)</p>
<p>Narrateur : Des journaux officiels &eacute;taient publi&eacute;s et lus &agrave; grande &eacute;chelle par le public en g&eacute;n&eacute;ral. Cook est ainsi devenu un h&eacute;ros national. Apr&egrave;s avoir compl&eacute;t&eacute; la cartographie du Pacifique sud, Cook allait-il terminer sa mission et retourner trouver le passage du Nord-Ouest?</p>