<p>(Au début de la vidéo on entend une musique douce, et le texte suivant apparaît à l’écran : Le commerce international européen)</p>
<p>Un narrateur lit une inscription dans un journal de bord : «&nbsp;Le soir du 29 avril, nous avons jeté l’ancre à environ huit miles de l’entrée, sur la rive sud de ce que nous supposions être le détroit de Fuca, sous une pluie très dense. Le lendemain matin… une faible brise soufflait du nord-ouest… et ce fameux bras de mer s’étalait à notre vue.&nbsp;» Fin de l’entrée du journal.</p>
<p>(L’inscription du journal apparaît en écriture cursive, superposée au tableau d’un bateau.)</p>
<p>Narrateur : Le capitaine Vancouver est arrivé sur la côte nord-ouest du Pacifique en 1792 afin de compléter la dernière d’une série d’expéditions européennes. Pour quelles raisons est-ce que les Européens entreprenaient-ils de tels voyages? Afin de le savoir, il faut remonter 400 ans en arrière. Pendant des siècles, le commerce avec l’Asie pour se procurer des épices et des tissus empruntait la route de la soie.</p>
<p>(Le trajet de la route de la soie se dessine sur une carte de l’Eurasie à partir de la Chine, en passant par le nord de l’Inde, pour arriver en Europe.)</p>
<p>Narrateur : Afin d’accroître leurs profits, les Européens se sont mis à chercher un passage maritime. </p>
<p>(Carte du monde montrant des flèches partant de l’Europe et prenant différentes directions dans l’océan Atlantique, entourées de points d’interrogation.)</p>
<p>Narrateur : Christophe Colomb a cru qu’il avait trouvé la voie lorsqu’il navigua vers l’ouest en 1492 – bien que sans le savoir, il n’avait fait que rejoindre les Caraïbes. Vasco de Gama, quant à lui, s’est bien rendu en Asie en naviguant vers l’est, en contournant l’Afrique pour rejoindre l’Inde, en 1498. Ces explorateurs faisaient volontiers du commerce avec les gens qu’ils rencontraient, mais prenaient aussi ce qu’ils désiraient de force, si nécessaire.</p>
<p>(Des dessins et des peintures d’époque montrent des explorateurs européens tenant des drapeaux et accompagnés de soldats lourdement armés, allant à la rencontre de peuples autochtones.)</p>
<p>Narrateur : Le pape Alexandre VI accorda au Portugal et à l’Espagne le «&nbsp;droit divin&nbsp;» de prendre possession des nouveaux territoires. Lors de la signature du traité de Tordesillas, en 1494, ils se sont entendus pour diviser le Nouveau Monde entre eux. Le Portugal avait toutes les terres à l’est des îles du Cap-Vert tandis que l’Espagne se réservait celles à l’ouest de celles-ci.</p>
<p>(On voit une carte du monde au sud de l’Espagne et du Portugal. Une ligne verticale blanche divise le monde au 46ème degré de latitude, traversant l’océan Atlantique et ce qui est aujourd’hui le Brésil. À droite de cette ligne, l’Afrique, l’Indonésie, le Brésil et la majorité de l’Antarctique sont colorés en vert pour représenter la déclaration papale de 1494 attribuant ces terres au Portugal. Le sud des États-Unis, l’Amérique centrale et le reste de l’Amérique du Sud et de l’Antarctique sont colorés en rouge pour l’Espagne.)</p>
<p>Narrateur : Avec la bénédiction du pape, les explorateurs espagnols et portugais se voyaient comme des émissaires envoyés pour convertir les gens qu’ils rencontraient à la religion catholique, qu’ils le veuillent ou non. </p>
<p>(Peintures et dessins d’époque représentant des armées espagnoles et portugaises en guerre contre les communautés autochtones. On entend des coups de feu.)</p>
<p>Narrateur : En Amérique centrale et du Sud, les conquistadores espagnols ont conspiré avec des groupes autochtones rivaux pour détruire les civilisations aztèques et incas. Les Espagnols ont volé de l’or et de l’argent à ces communautés pour une valeur estimée à 11 milliards de dollars en argent d’aujourd’hui. Les Portugais et les Espagnols ont aussi établi des plantations de canne à sucre au Brésil et dans les Caraïbes.</p>
<p>(Une carte montre, en vert, ce qui est aujourd’hui le Brésil, représentant les terres revendiquées par le Portugal, alors que l’ouest et le sud des États-Unis, l’Amérique centrale, les Caraïbes et le reste de l’Amérique du Sud sont en rouge, pour représenter ce que revendiquait l’Espagne.)</p>
<p>Narrateur : Ils ont réduit les populations autochtones à l’esclavage dans ces plantations et vendu le sucre avec d’énorme profits en Europe.</p>
<p>(Dessins graphiques d’époque d’Autochtones se faisant torturer, réduits à l’esclavage et travaillant dans des conditions difficiles dans des plantations de canne à sucre.)</p>
<p>Narrateur : Quand les populations autochtones ont été décimées, ils ont fait le commerce d’esclaves avec des tribus côtières africaines afin de se procurer les esclaves, hommes, femmes et enfants, dont ils avaient besoin pour combler le besoin en main d’œuvre.</p>
<p>(Une carte animée des terres autour de l’océan Atlantique. La carte fait d’abord un zoom sur la côte ouest de l’Afrique. On y voit des icônes représentant plusieurs personnes près du Libéria et plus au sud jusqu’en Angola. Cape Coast, au Ghana, est identifiée comme «&nbsp;côte de l’Or&nbsp;». Des routes de navigation de bateaux négriers sont dessinées en rouge et en vert à partir de la côte de l’Or, puis traversant l’océan Atlantique jusqu’aux terres revendiquées par l’Espagne et le Portugal en Amérique du Nord et du Sud. On voit différents dessins d’époque représentant la torture et les conditions de vie sur les bateaux négriers.)</p>
<p>Narrateur : Au XVIIème siècle, la Hollande, la Bretagne et la France ont commencé à remettre en question le contrôle par l’Espagne et le Portugal du commerce avec le Nouveau Monde. Les Hollandais ont mis la main sur le commerce des épices avec les Indes orientales, tandis que les Britanniques ont établi des plantations et des colonies dans les Caraïbes et le long de la côte est de l’Amérique du Nord.</p>
<p>(Une carte de l’Amérique du Nord montre les terres revendiquées par les Britanniques en mauve. Le Bélize, la Jamaïque, les Bahamas, la côte est du Nicaragua, la côte est des États-Unis, la Nouvelle-Écosse, Terre-Neuve ainsi que les terres autour de la baie d’Hudson sont toutes colorées en mauve.)</p>
<p>Narrateur : En 1670, ils établirent le monopole de la traite des fourrures de la Compagnie de la Baie d’Hudson. La France se mit à faire du commerce en Inde, a établi des plantations dans les Caraïbes ainsi que le territoire de la Nouvelle-France avec en son centre la ville de Québec.</p>
<p>(Une carte de l’Amérique du Nord montre les revendications territoriales de la France en bleu. La Guyane française, Sainte-Lucie, Haïti, Québec, le Nouveau-Brunswick, presque tout l’Ontario, le Manitoba et le centre des États-Unis jusqu’à la Nouvelle-Orléans sont colorés en bleu. Une grande partie de l’ouest du Canada et des États-Unis sont en gris, sans couleur, ce qui signifie qu’il n’y a toujours pas de revendications territoriales européennes.)</p>
<p>Narrateur : En 1730, les réseaux commerciaux européens étaient vraiment devenus mondiaux, et se concentraient sur un triangle commercial dans l’Atlantique. Les esclaves étaient la principale source de profits pour toutes les puissances européennes. </p>
<p>(Du texte apparaît à l’écran. Les mots «&nbsp;Biens manufacturés&nbsp;» apparaissent dans une boîte au centre en haut de l’écran. Les mots «&nbsp;Produits des plantations&nbsp;» apparaissent dans une boîte en bas à gauche de l’écran. Les mots «&nbsp;Esclaves&nbsp;» sont dans une boîte en bas à droite de l’écran. Des lignes relient ces boîtes de texte, créant la forme d’un triangle. Les mots disparaissent, remplacés par une carte des terres autour de l’océan Atlantique. Une flèche partant de l’Afrique et allant jusqu’en Amérique du Sud et du Nord est identifiée par le mot «&nbsp;esclaves&nbsp;». Une seconde flèche partant de l’Amérique du Nord et allant jusqu’en Europe est identifiée par les mots «&nbsp;sucre, café, peaux&nbsp;». Une troisième flèche partant de l’Europe et allant en Afrique est identifiée par les mots «&nbsp;vêtements, fusils, cauris et rhum&nbsp;». Les flèches forment un triangle rappelant les boîtes de texte interreliées précédentes.)</p>
<p>Narrateur : Au XVIIIème siècle, plus de 6,5 millions d’Africains avaient été capturés et transportés. L’espérance de vie sur les plantations était courte. Sur les plantations de canne à sucre de Saint-Domingue, 30 000 esclaves africains arrivaient chaque année; la moitié d’entre eux mouraient à l’intérieur de trois à huit ans.</p>
<p>(Des dessins d’époque des conditions de vie dans des structures surpeuplées sur les plantations, de punitions brutales des esclaves et d’esclaves travaillant dans des plantations.)</p>
<p>Narrateur : Les puissances européennes se sont disputées leurs colonies respectives pendant la guerre de Sept Ans, premier conflit pouvant être qualifié de guerre mondiale.</p>
<p>(Bruits de coups de canon. Peintures d’époque de gros bateaux à voile livrant bataille en mer. Un des bateaux a toutes ses voiles et ses mâts brisés.)</p>
<p>Narrateur : La France perdit la ville de Québec aux mains des Britanniques en 1759 lors de la bataille des plaines d’Abraham. Elle a conséquemment cédé son territoire nord-américain à la Bretagne et à l’Espagne lors d’un traité de paix signé à Paris en 1763. </p>
<p>(Carte de l’Amérique du Nord et de l’Amérique centrale. Tout le Canada et les États-Unis à l’est de la Saskatchewan est coloré en mauve, représentant les territoires britanniques. Le centre et le sud des États-Unis, le Mexique et l’Amérique centrale sont en rouge, pour l’Espagne. Le reste de l’Amérique du Nord est toujours en gris, donc sans couleur.)</p>
<p>Narrateur : Avec leur domination impériale ainsi sécurisée, les Britanniques financèrent la première des trois expéditions dédiées à la cartographie du Pacifique. </p>
<p>(On voit une carte du monde. Une route de navigation dessinée en blanc part de la Bretagne, navigue à travers l’océan Atlantique, contourne l’hémisphère sud avant de retourner vers le nord jusqu’en Bretagne. La route de navigation fait le tour de la Nouvelle-Zélande et longe la côte est de l’Australie. Cet itinéraire est très irrégulier. Il s’agit du tour du monde en bateau effectué par le capitaine Cook.)</p>
<p>Narrateur : Et idéalement trouver une route de navigation plus rapide vers l’Asie à travers l’Amérique du Nord; le passage du Nord-Ouest.</p>
<p>(Sur la même carte, plusieurs trajets apparaissent à travers l’Amérique du Nord, marqués de points d’interrogation et par le texte «&nbsp;Passage du Nord-Ouest&nbsp;».)</p>
<p>Narrateur : L’expédition était menée par le capitaine James Cook, cartographe et navigateur expérimenté. En sept ans et deux expéditions, Cook dessina les premières cartes de l’Australie, de la Nouvelle-Zélande et des îles du Pacifique. Il confirma également qu’il n’existait pas d’autre continent plus au sud, outre l’Antarctique. </p>
<p>(Une peinture du capitaine Cook le montre avec des cheveux gris et vêtu d’un uniforme de marine bleu et blanc à boutonnière, tenant un télescope dans une main et un tricorne dans l’autre. Au-dessus la route de navigation du capitaine Cook dessinée en blanc, une route de navigation marquée d’un trait rouge se dessine pour représenter le second voyage de Cook. Le trajet en rouge part encore de la Bretagne, et navigue vers l’est, plus près de l’Antarctique. Il passe autour de la Nouvelle-Zélande et fait le tour de l’océan Pacifique à deux reprises avant de retourner en Bretagne.)</p>
<p>Narrateur : À l’ère des conquêtes coloniales, les cartes étaient une importante source de richesse. Les territoires autochtones devenaient des espaces vides non-répertoriés que les Européens revendiqueraient comme les leurs.</p>
<p>(Une carte montre l’Australie, la Nouvelle-Zélande, le Vanuatu et la Nouvelle-Calédonie en mauve, montrant ainsi que ces territoires étaient revendiqués par les Britanniques.)</p>
<p>Narrateur : Les expéditions de Cook étaient financées par The Royal Society, une académie scientifique britannique. En plus des cartes, ces expéditions revenaient riches d’informations détaillées documentées par des scientifiques et des artistes à propos des peuples qu’ils rencontraient et des plantes et des animaux qu’ils voyaient.</p>
<p>(Un livre dont la couverture est ornée du logo de la Royal Society s’ouvre pour montrer des dessins d’animaux comme un pingouin et un kangourou, d’Autochtones au visage tatoué, et d’arbres fruitiers.)</p>
<p>Narrateur : Des journaux officiels étaient publiés et lus à grande échelle par le public en général. Cook est ainsi devenu un héros national. Après avoir complété la cartographie du Pacifique sud, Cook allait-il terminer sa mission et retourner trouver le passage du Nord-Ouest?</p>
