<p>(Au d&eacute;but de la vid&eacute;o, on entend une musique m&eacute;ditative. Le texte&nbsp;: &laquo;&nbsp;Passage du Nord-Ouest&nbsp;&raquo; apparait &agrave; l&rsquo;&eacute;cran.)&nbsp;</p>
<p>Un narrateur lit une inscription dans un journal de bord&nbsp;: &laquo;&nbsp;Il fait peu de doutes qu&rsquo;il existe une voie de communication nordique, par la mer, entre l&rsquo;Ouest et l&rsquo;Est de l&rsquo;Am&eacute;rique, en passant par la baie de Baffin.&nbsp;&raquo; Capitaine James Cook, &icirc;les Al&eacute;outiennes, Octobre 1778.</p>
<p>(L&rsquo;inscription du journal apparait en &eacute;criture cursive, superpos&eacute;e au dessin d&rsquo;un bateau.)</p>
<p>Le narrateur dit&nbsp;: La Grande-Bretagne rivalisait avec l&rsquo;Espagne pour revendiquer la souverainet&eacute; de cette r&eacute;gion &agrave; travers ses tentatives de trouver le passage du Nord-Ouest. D&egrave;s 1592, Juan de Fuca, un marin exp&eacute;riment&eacute; &agrave; la solde de l&rsquo;Espagne, croyait avoir trouv&eacute; une voie, ici.</p>
<p>(Une carte historique apparait. On y voit l&rsquo;Asie, cartographi&eacute;e en d&eacute;tails, mais l&rsquo;Am&eacute;rique du Nord est quant &agrave; elle grossi&egrave;rement cartographi&eacute;e, avec peu de d&eacute;tails. La carte montre le trajet de navigation emprunt&eacute; par Juan de Fuca autour du 49<sup>&egrave;me</sup> parall&egrave;le.)&nbsp;</p>
<p>Narrateur&nbsp;: Des rumeurs circulaient aussi selon lesquelles l&rsquo;amiral espagnol Bartholomew de Fonte aurait trouv&eacute; une route possible, ici, en 1640.&nbsp;</p>
<p>(Sur la m&ecirc;me carte, un second trajet se dessine &agrave; environ 53&deg; Nord.)</p>
<p>Narrateur&nbsp;: La Compagnie de la Baie d&rsquo;Hudson employa Samuel Hearne et Matonabbee, un guide D&eacute;n&eacute;, afin d&rsquo;explorer les routes terrestres. Ils atteignirent l&rsquo;oc&eacute;an Arctique, &agrave; l&rsquo;embouchure de la rivi&egrave;re Coppermine, en 1771.</p>
<p>(Une carte anim&eacute;e montre un trajet en boucle que Samuel Hearne et Matonabbee ont emprunt&eacute;, faisant un aller-retour &agrave; partir du fort Prince-de-Galles sur la c&ocirc;te ouest de la baie d&rsquo;Hudson. Ensuite, un second trajet se dessine, partant du fort Prince-de-Galles et allant vers le nord jusqu&rsquo;&agrave; l&rsquo;oc&eacute;an Arctique, pour ensuite revenir &agrave; la baie d&rsquo;Hudson.)</p>
<p>Narrateur&nbsp;: Vers la m&ecirc;me &eacute;poque, des cartes illustrant les d&eacute;couvertes russes font jaillir l&rsquo;id&eacute;e d&rsquo;un possible passage maritime par le nord, puis vers l&rsquo;est, qui passerait au-dessus de l&rsquo;Am&eacute;rique. Existerait-il vraiment un passage aussi loin au nord?</p>
<p>(Sur la m&ecirc;me carte, un trajet se dessine vers le nord, entre la Russie et ce qui est aujourd&rsquo;hui l&rsquo;Alaska, jusqu&rsquo;&agrave; l&rsquo;oc&eacute;an Arctique.</p>
<p>Narrateur&nbsp;: Les Britanniques crurent en cette possibilit&eacute; et envoy&egrave;rent le capitaine James Cook v&eacute;rifier cette hypoth&egrave;se. En janvier 1778, l&rsquo;exp&eacute;dition atteignait Hawa&iuml;.</p>
<p>(Une carte anim&eacute;e du monde montre le trajet emprunt&eacute; par le capitaine Cook, de la Nouvelle-Z&eacute;lande vers le nord, jusqu&rsquo;&agrave; Hawa&iuml; (connue sous le nom d&rsquo;&icirc;les Sandwich par les Britanniques &agrave; l&rsquo;&eacute;poque).)</p>
<p>Narrateur&nbsp;: Ils &eacute;taient les premiers Europ&eacute;ens &agrave; visiter et &agrave; cartographier l&rsquo;archipel.&nbsp;</p>
<p>(On voit un dessin des bateaux au large d&rsquo;Hawa&iuml; et quelques cartes dessin&eacute;es lors de ce voyage.)</p>
<p>Narrateur&nbsp;: Cook fut accueilli comme un invit&eacute; d&rsquo;honneur par des centaines d&rsquo;insulaires.</p>
<p>(Un dessin en noir et blanc d&rsquo;Hawa&iuml;ens ramant vers le bateau du capitaine Cook avec les montagnes hawa&iuml;ennes &agrave; l&rsquo;arri&egrave;re-plan.)</p>
<p>Narrateur&nbsp;: Certains croient que les Hawa&iuml;ens auraient pris Cook pour une incarnation du dieu polyn&eacute;sien Lono.&nbsp;</p>
<p>(Un dessin du capitaine Cook et d&rsquo;une partie de son &eacute;quipage entour&eacute;s par des Hawa&iuml;ens assis sur le sol.)</p>
<p>Narrateur&nbsp;: En mars, l&rsquo;exp&eacute;dition approchait de la c&ocirc;te du Nord-Ouest lorsqu&rsquo;elle fut frapp&eacute;e par des temp&ecirc;tes.</p>
<p>(Une carte anim&eacute;e montre le trajet emprunt&eacute; par le capitaine Cook &agrave; partir d&rsquo;Hawa&iuml;, puis &agrave; travers l&rsquo;oc&eacute;an Pacifique vers la c&ocirc;te du Nord-Ouest de l&rsquo;Am&eacute;rique du Nord.)</p>
<p>Narrateur&nbsp;: Ils rat&egrave;rent donc le d&eacute;troit de Juan de Fuca et avaient d&eacute;riv&eacute;s trop loin pour chercher le passage de l&rsquo;amiral Fonte. Le journal de Cook r&eacute;v&egrave;le qu&rsquo;il &eacute;tait septique &agrave; propos de ces voies.</p>
<p>Le narrateur lit une inscription du journal&nbsp;: &laquo;&nbsp;quant &agrave; moi, je ne donne aucun cr&eacute;dit &agrave; ces vagues et improbables histoires.&nbsp;&raquo; Capitaine James Cook, mai 1778.</p>
<p>(Derri&egrave;re la citation du journal en &eacute;criture cursive, une carte de la c&ocirc;te du Nord-Ouest reproduit le trajet zigzagant emprunt&eacute; par Cook le long de la c&ocirc;te.)</p>
<p>Narrateur&nbsp;: Les bateaux jet&egrave;rent l&rsquo;ancre pr&egrave;s du village de Yuquot. Cook appela erron&eacute;ment le village Nootka, ayant mal compris le peuple Mowachaht &agrave; son arriv&eacute;.&nbsp;</p>
<p>Le narrateur lit une inscription du journal&nbsp;: &laquo;&nbsp;Ils ramaient&hellip; autour des deux bateaux. Un chef ou autre personne importante se tenant debout avec une lance &agrave; la main&hellip; ils nous ont accost&eacute;s et ont commenc&eacute; &agrave; n&eacute;gocier des &eacute;changes, sans plus de c&eacute;r&eacute;monie&hellip; leurs articles consistaient en des peaux d&rsquo;animaux, en particulier des castors de mer [loutre]&hellip;&nbsp;&raquo; Capitaine James Cook, avril 1778, Ship Cove.</p>
<p>(Derri&egrave;re la citation en &eacute;criture cursive du journal il y a l&rsquo;esquisse d&rsquo;une loutre de mer dessin&eacute;e lors du voyage de Cook.)</p>
<p>Narrateur&nbsp;: Les marins et les Mowachaht &eacute;chang&egrave;rent du bois, de l&rsquo;eau, de l&rsquo;huile, du poisson et des fourrures contre, principalement, des objets de m&eacute;tal, un mat&eacute;riau rare &agrave; Yuquot.</p>
<p>(Une s&eacute;rie d&rsquo;esquisses et de peintures des bateaux du capitaine Cook &agrave; l&rsquo;ancre &agrave; Yuquot, entour&eacute;s de montagnes recouvertes de for&ecirc;t et des canots des Mowachaht.)</p>
<p>Narrateur&nbsp;: Lors de leur s&eacute;jour, John Webber et d&rsquo;autres artistes pr&eacute;sents &agrave; bord du bateau ont r&eacute;alis&eacute; des dessins d&eacute;taill&eacute;s de la vie dans la communaut&eacute;. Ceux-ci ont par la suite &eacute;t&eacute; publi&eacute;s sous la forme de gravures dans le journal de l&rsquo;exp&eacute;dition, qui devint de facto le livre de r&eacute;f&eacute;rence dans la r&eacute;gion.&nbsp;</p>
<p>(Une s&eacute;rie d&rsquo;esquisses par John Webber et d&rsquo;autres des tenues c&eacute;r&eacute;monielles et des villages des Mowachaht.)</p>
<p>Narrateur&nbsp;: Apr&egrave;s pr&egrave;s d&rsquo;un mois &agrave; Yuquot, Cook avait termin&eacute; son exploration ainsi que l&rsquo;attribution d&rsquo;une nouvelle toponymie de la c&ocirc;te du Nord-Ouest. Ils se trouvaient ainsi dans le golfe du Prince William en mai, dans le golfe de Cook en juin, et au cap des Glaces en ao&ucirc;t.</p>
<p>(Une carte de la c&ocirc;te du Nord-Ouest montre le trajet emprunt&eacute; par Cook le long de la c&ocirc;te. Les golfes du Prince William et de Cook sont tous les deux au sud de l&rsquo;Alaska, tandis que le cap des Glaces se trouve dans l&rsquo;Arctique &agrave; 70 degr&eacute;s Nord.)</p>
<p>Narrateur&nbsp;: Cook &eacute;tait convaincu que le passage se trouvait &agrave; 71 degr&eacute;s Nord, mais la prise des glaces les emp&ecirc;cha d&rsquo;aller plus loin. L&rsquo;exp&eacute;dition est donc retourn&eacute;e &agrave; Hawa&iuml; en janvier 1779 pour effectuer des r&eacute;parations et faire le plein de provisions. Bien qu&rsquo;ils aient au d&eacute;part &eacute;t&eacute; bien accueillis, un conflit &eacute;clata par la suite et Cook fut tu&eacute; par les Hawa&iuml;ens le 14 f&eacute;vrier.</p>
<p>(Une peinture de la bataille entre l&rsquo;&eacute;quipage de Cook et les Hawa&iuml;ens. On entend des coups de feu.)</p>
<p>Narrateur&nbsp;: L&rsquo;&eacute;quipage continua la mission. Sur le chemin du retour &agrave; la maison, ils apprirent que les fourrures de loutre de mer qu&rsquo;ils avaient achet&eacute;es &agrave; Yuquot pouvaient se vendre avec d&rsquo;&eacute;normes profits en Chine. Une belle fourrure se vendait 120 $, ce qui &eacute;quivaut &agrave; 3&nbsp;000&nbsp;$ aujourd&rsquo;hui.</p>
<p>(Une carte anim&eacute;e montre le trajet emprunt&eacute; par l&rsquo;&eacute;quipage, longeant la c&ocirc;te asiatique vers le nord &agrave; partir d&rsquo;Hawa&iuml;, puis revenant vers le sud jusqu&rsquo;en Chine.)</p>
<p>Narrateur&nbsp;: L&rsquo;histoire de la loutre de mer provoqua beaucoup d&rsquo;int&eacute;r&ecirc;t parmi les marins de la marine britannique. Plusieurs d&rsquo;entre eux ne recevaient que la moiti&eacute; de leur solde depuis la guerre d&rsquo;Ind&eacute;pendance am&eacute;ricaine qui s&rsquo;&eacute;tait termin&eacute;e en 1783. En 1785, le premier bateau britannique d&eacute;di&eacute; au commerce des fourrures arriva &agrave; Yuquot. L&rsquo;&eacute;t&eacute; suivant, sept commer&ccedil;ants de fourrures britanniques se trouvaient dans la r&eacute;gion. On y faisait des fortunes.</p>
<p>(Une carte montre Yuquot sur une grande &icirc;le de la c&ocirc;te nord-ouest du Pacifique, &agrave; environ 49 degr&eacute;s Nord.)</p>
<p>Narrateur&nbsp;: En 1787, le capitaine Nathaniel Portlock et George Dixon vendirent 2&nbsp;552 fourrures pour 54&nbsp;675&nbsp;$ &agrave; Canton. Cela &eacute;quivaut &agrave; environ 1,4&nbsp;M$ aujourd&rsquo;hui. Le r&eacute;seau commercial des communaut&eacute;s autochtones qui &eacute;tait d&eacute;j&agrave; bien &eacute;tabli a eu t&ocirc;t fait d&rsquo;y inclure les marchandises britanniques et am&eacute;ricaines. Plusieurs centres de traite ont donc &eacute;merg&eacute; au sein des communaut&eacute;s c&ocirc;ti&egrave;res.</p>
<p>(Sur une carte de la c&ocirc;te nord-ouest du Pacifique, les centres de traite voisins de Yuquot et de la baie Clayoquot apparaissent. Puis, ce sont ceux de Kiusta et de Kaigani, sur de grandes &icirc;les autour du 55<sup>&egrave;me</sup> degr&eacute; Nord.)</p>
<p>Narrateur&nbsp;: Le pouvoir et l&rsquo;influence de chaque chef augmentait avec leur richesse.</p>
<p>(Le chef Michael Maquinna de la Premi&egrave;re Nation Mowachaht/Muchalaht est interview&eacute; &agrave; l&rsquo;&eacute;cran, devant un gros plan d&rsquo;une esquisse d&rsquo;un village ancestral.)</p>
<p>Chef&nbsp;Michael Maquinna&nbsp;: &laquo;&nbsp;Au d&eacute;but, ce n&rsquo;&eacute;tait pas une mauvaise chose. Toutefois, avec le temps, nous avons r&eacute;alis&eacute; que les choses ont un peu mal tourn&eacute; pour les membres des Premi&egrave;res Nations.&nbsp;&raquo;</p>
<p>Narrateur&nbsp;: En 1788, financ&eacute; par un conglom&eacute;rat de compagnies de traite britanniques et asiatiques, John Meares, un ancien lieutenant de la Marine royale, est arriv&eacute; &agrave; Yuquot. Il y fit construire une go&eacute;lette et d&eacute;clara avoir achet&eacute; des terres au chef Mowachaht Maquinna pour y construire un poste de traite.</p>
<p>(On voit une peinture d&rsquo;une go&eacute;lette en construction sur la c&ocirc;te, superpos&eacute;e par deux dessins, un du chef Maquinna portant un couvre-chef tiss&eacute; c&eacute;r&eacute;moniel et l&rsquo;autre de John Meares.)</p>
<p>Narrateur&nbsp;: Au printemps 1789, plusieurs commer&ccedil;ants de fourrures am&eacute;ricains et britanniques avaient jet&eacute; l&rsquo;ancre &agrave; Yuquot. L&rsquo;Espagne &eacute;tait de plus en plus pr&eacute;occup&eacute;e &agrave; propos de ses revendications de souverainet&eacute; sur la r&eacute;gion. En plus de la pr&eacute;sence britannique grandissante, elle surveillait les activit&eacute;s de commerce des fourrures de la Russie dans les &icirc;les Al&eacute;outiennes. Une exp&eacute;dition effectu&eacute;e l&agrave;-bas en 1788 rapporta que les Russes avaient &eacute;tendu leur r&eacute;seau de fa&ccedil;on substantielle; ils avaient &eacute;tabli six nouveaux postes de traite ainsi qu&rsquo;une importante colonie sur l&rsquo;&icirc;le Kodiak.</p>
<p>(Une carte montre les &icirc;les Al&eacute;outiennes au sud de ce qui est aujourd&rsquo;hui l&rsquo;Alaska, et l&rsquo;&icirc;le Kodiak plus &agrave; l&rsquo;est.)&nbsp;</p>
<p>Narrateur&nbsp;: En mai 1789, deux fr&eacute;gates espagnoles sont arriv&eacute;es &agrave; Yuquot, sous le commandement du capitaine Esteban Jos&eacute; Mart&iacute;nez. Ils prirent officiellement possession de l&rsquo;anse et construisirent une batterie de tir &agrave; l&rsquo;entr&eacute;e du port.</p>
<p>(Un dessin montre un poste de traite avec un drapeau, dans l&rsquo;anse.)</p>
<p>Narrateur : Plus tard, le navire marchand <em>Argonaut</em> arriva, en juillet, avec &agrave; son bord des ouvriers chinois et des provisions pour le poste de traite de John Meares. Une dispute &eacute;clata entre Mart&iacute;nez et le capitaine du bateau, James Colnett. Accusant les commer&ccedil;ants de fourrures britanniques d&rsquo;empi&eacute;ter sur le territoire espagnol, Mart&iacute;nez saisit les bateaux et arr&ecirc;ta l&rsquo;&eacute;quipage. Au milieu de l&rsquo;escarmouche, le chef Callicum, beau-fr&egrave;re du chef Maquinna, fut tu&eacute; par les Espagnols. John Meares retourna en Angleterre, en passant par la Chine, en avril 1790, apportant les nouvelles des injustices subies par sa compagnie de traite et demandant l&rsquo;aide du gouvernement.</p>
<p>Mais comment les Britanniques allaient-ils r&eacute;pondre &agrave; ces offenses?</p>