<p>(Au début de la vidéo, on entend une musique méditative. Le texte «&nbsp;Passage du Nord-Ouest&nbsp;» apparait à l’écran.) </p>
<p>Un narrateur lit une inscription dans un journal de bord&nbsp; «&nbsp;Il fait peu de doutes qu’il existe une voie de communication nordique, par la mer, entre l’Ouest et l’Est de l’Amérique, en passant par la baie de Baffin.&nbsp;» Capitaine James Cook, îles Aléoutiennes, Octobre 1778.</p>
<p>(L’inscription du journal apparait en écriture cursive, superposée au dessin d’un bateau.)</p>
<p>Le narrateur dit&nbsp; La Bretagne rivalisait avec l’Espagne pour revendiquer la souveraineté de cette région à travers ses tentatives de trouver le passage du Nord-Ouest. Dès 1592, Juan de Fuca, un marin expérimenté à la solde de l’Espagne, croyait avoir trouvé une voie, ici.</p>
<p>(Une carte historique apparait. On y voit l’Asie, cartographiée en détails, mais l’Amérique du Nord est quant à elle grossièrement cartographiée, avec peu de détails. La carte montre le trajet de navigation emprunté par Juan de Fuca autour du 49ème parallèle.) </p>
<p>Narrateur&nbsp; Des rumeurs circulaient aussi selon lesquelles l’amiral espagnol Bartholomew de Fonte aurait trouvé une route possible, ici, en 1640. </p>
<p>(Sur la même carte, un second trajet se dessine à environ 53° Nord.)</p>
<p>Narrateur&nbsp; La Compagnie de la Baie d’Hudson employa Samuel Hearne et Matonabbee, un guide Déné, afin d’explorer les routes terrestres. Ils atteignirent l’océan Arctique, à l’embouchure de la rivière Coppermine, en 1771.</p>
<p>(Une carte animée montre un trajet en boucle que Samuel Hearne et Matonabbee ont emprunté, faisant un aller-retour à partir du fort Prince-de-Galles sur la côte ouest de la baie d’Hudson. Ensuite, un second trajet se dessine, partant du fort Prince-de-Galles et allant vers le nord jusqu’à l’océan Arctique, pour ensuite revenir à la baie d’Hudson.)</p>
<p>Narrateur&nbsp; Vers la même époque, des cartes illustrant les découvertes russes font jaillir l’idée d’un possible passage maritime par le nord, puis vers l’est, qui passerait au-dessus de l’Amérique. Existerait-il vraiment un passage aussi loin au nord?</p>
<p>(Sur la même carte, un trajet se dessine vers le nord, entre la Russie et ce qui est aujourd’hui l’Alaska, jusqu’à l’océan Arctique.</p>
<p>Narrateur&nbsp; Les Britanniques crurent en cette possibilité et envoyèrent le capitaine James Cook vérifier cette hypothèse. En janvier 1778, l’expédition atteignait Hawaï.</p>
<p>(Une carte animée du monde montre le trajet emprunté par le capitaine Cook, de la Nouvelle-Zélande vers le nord, jusqu’à Hawaï (connue sous le nom d’îles Sandwich par les Britanniques à l’époque).)</p>
<p>Narrateur&nbsp; Ils étaient les premiers Européens à visiter et à cartographier l’archipel. </p>
<p>(On voit un dessin des bateaux au large d’Hawaï et quelques cartes dessinées lors de ce voyage.)</p>
<p>Narrateur&nbsp; Cook fut accueilli comme un invité d’honneur par des centaines d’insulaires.</p>
<p>(Un dessin en noir et blanc d’Hawaïens ramant vers le bateau du capitaine Cook avec les montagnes hawaïennes à l’arrière-plan.)</p>
<p>Narrateur&nbsp; Certains croient que les Hawaïens auraient pris Cook pour une incarnation du dieu polynésien Lono. </p>
<p>(Un dessin du capitaine Cook et d’une partie de son équipage entourés par des Hawaïens assis sur le sol.)</p>
<p>Narrateur&nbsp; En mars, l’expédition approchait de la côte du Nord-Ouest lorsqu’elle fut frappée par des tempêtes.</p>
<p>(Une carte animée montre le trajet emprunté par le capitaine Cook à partir d’Hawaï, puis à travers l’océan Pacifique vers la côte du Nord-Ouest de l’Amérique du Nord.)</p>
<p>Narrateur&nbsp; Ils ratèrent donc le détroit de Juan de Fuca et avaient dérivés trop loin pour chercher le passage de l’amiral Fonte. Le journal de Cook révèle qu’il était septique à propos de ces voies.</p>
<p>Le narrateur lit une inscription du journal&nbsp; «&nbsp;quant à moi, je ne donne aucun crédit à ces vagues et improbables histoires.&nbsp;» Capitaine James Cook, mai 1778.</p>
<p>(Derrière la citation du journal en écriture cursive, une carte de la côte du Nord-Ouest reproduit le trajet zigzagant emprunté par Cook le long de la côte.)</p>
<p>Narrateur&nbsp; Les bateaux jetèrent l’ancre près du village de Yuquot. Cook appela erronément le village Nootka, ayant mal compris le peuple Mowachaht à son arrivé. </p>
<p>Le narrateur lit une inscription du journal&nbsp; «&nbsp;Ils ramaient… autour des deux bateaux. Un chef ou autre personne importante se tenant debout avec une lance à la main… ils nous ont accostés et ont commencé à négocier des échanges, sans plus de cérémonie… leurs articles consistaient en des peaux d’animaux, en particulier des castors de mer [loutre]…&nbsp;» Capitaine James Cook, avril 1778, Ship Cove.</p>
<p>(Derrière la citation en écriture cursive du journal il y a l’esquisse d’une loutre de mer dessinée lors du voyage de Cook.)</p>
<p>Narrateur&nbsp; Les marins et les Mowachaht échangèrent du bois, de l’eau, de l’huile, du poisson et des fourrures contre, principalement, des objets de métal, un matériau rare à Yuquot.</p>
<p>(Une série d’esquisses et de peintures des bateaux du capitaine Cook à l’ancre à Yuquot, entourés de montagnes recouvertes de forêt et des canots des Mowachaht.)</p>
<p>Narrateur&nbsp; Lors de leur séjour, John Webber et d’autres artistes présents à bord du bateau ont réalisé des dessins détaillés de la vie dans la communauté. Ceux-ci ont par la suite été publiés sous la forme de gravures dans le journal de l’expédition, qui devint de facto le livre de référence dans la région. </p>
<p>(Une série d’esquisses par John Webber et d’autres des tenues cérémonielles et des villages des Mowachaht.)</p>
<p>Narrateur&nbsp; Après près d’un mois à Yuquot, Cook avait terminé son exploration ainsi que l’attribution d’une nouvelle toponymie de la côte du Nord-Ouest. Ils se trouvaient ainsi dans le golfe du Prince William en mai, dans le golfe de Cook en juin, et au cap des Glaces en août.</p>
<p>(Une carte de la côte du Nord-Ouest montre le trajet emprunté par Cook le long de la côte. Les golfes du Prince William et de Cook sont tous les deux au sud de l’Alaska, tandis que le cap des Glaces se trouve dans l’Arctique à 70 degrés Nord.)</p>
<p>Narrateur&nbsp; Cook était convaincu que le passage se trouvait à 71 degrés Nord, mais la prise des glaces les empêcha d’aller plus loin. L’expédition est donc retournée à Hawaï en janvier 1779 pour effectuer des réparations et faire le plein de provisions. Bien qu’ils aient au départ été bien accueillis, un conflit éclata par la suite et Cook fut tué par les Hawaïens le 14 février.</p>
<p>(Une peinture de la bataille entre l’équipage de Cook et les Hawaïens. On entend des coups de feu.)</p>
<p>Narrateur&nbsp; L’équipage continua la mission. Sur le chemin du retour à la maison, ils apprirent que les fourrures de loutre de mer qu’ils avaient achetées à Yuquot pouvaient se vendre avec d’énormes profits en Chine. Une belle fourrure se vendait 120 $, ce qui équivaut à 3 000 $ aujourd’hui.</p>
<p>(Une carte animée montre le trajet emprunté par l’équipage, longeant la côte asiatique vers le nord à partir d’Hawaï, puis revenant vers le sud jusqu’en Chine.)</p>
<p>Narrateur&nbsp; L’histoire de la loutre de mer provoqua beaucoup d’intérêt parmi les marins de la marine britannique. Plusieurs d’entre eux ne recevaient que la moitié de leur solde depuis la guerre d’Indépendance américaine qui s’était terminée en 1783. En 1785, le premier bateau britannique dédié au commerce des fourrures arriva à Yuquot. L’été suivant, sept commerçants de fourrures britanniques se trouvaient dans la région. On y faisait des fortunes.</p>
<p>(Une carte montre Yuquot sur une grande île de la côte nord-ouest du Pacifique, à environ 49 degrés Nord.)</p>
<p>Narrateur&nbsp; En 1787, le capitaine Nathaniel Portlock et George Dixon vendirent 2 552 fourrures pour 54 675 $ à Canton. Cela équivaut à environ 1,4 M$ aujourd’hui. Le réseau commercial des communautés autochtones qui était déjà bien établi a eu tôt fait d’y inclure les marchandises britanniques et américaines. Plusieurs centres de traite ont donc émergé au sein des communautés côtières.</p>
<p>(Sur une carte de la côte nord-ouest du Pacifique, les centres de traite voisins de Yuquot et de la baie Clayoquot apparaissent. Puis, ce sont ceux de Kiusta et de Kaigani, sur de grandes îles autour du 55ème degré Nord.)</p>
<p>Narrateur&nbsp; Le pouvoir et l’influence de chaque chef augmentait avec leur richesse.</p>
<p>(Le chef Michael Maquinna de la Première Nation Mowachaht/Muchalaht est interviewé à l’écran, devant un gros plan d’une esquisse d’un village ancestral.)</p>
<p>Chef Michael Maquinna&nbsp; «&nbsp;Au début, ce n’était pas une mauvaise chose. Toutefois, avec le temps, nous avons réalisé que les choses ont un peu mal tourné pour les membres des Premières Nations.&nbsp;»</p>
<p>Narrateur&nbsp; En 1788, financé par un conglomérat de compagnies de traite britanniques et asiatiques, John Meares, un ancien lieutenant de la Marine royale, est arrivé à Yuquot. Il y fit construire une goélette et déclara avoir acheté des terres au chef Mowachaht Maquinna pour y construire un poste de traite.</p>
<p>(On voit une peinture d’une goélette en construction sur la côte, superposée par deux dessins, un du chef Maquinna portant un couvre-chef tissé cérémoniel et l’autre de John Meares.)</p>
<p>Narrateur&nbsp; Au printemps 1789, plusieurs commerçants de fourrures américains et britanniques avaient jeté l’ancre à Yuquot. L’Espagne était de plus en plus préoccupée à propos de ses revendications de souveraineté sur la région. En plus de la présence britannique grandissante, elle surveillait les activités de commerce des fourrures de la Russie dans les îles Aléoutiennes. Une expédition effectuée là-bas en 1788 rapporta que les Russes avaient étendu leur réseau de façon substantielle; ils avaient établi six nouveaux postes de traite ainsi qu’une importante colonie sur l’île Kodiak.</p>
<p>(Une carte montre les îles Aléoutiennes au sud de ce qui est aujourd’hui l’Alaska, et l’île Kodiak plus à l’est.) </p>
<p>Narrateur&nbsp; En mai 1789, deux frégates espagnoles sont arrivées à Yuquot, sous le commandement du capitaine Esteban José Martínez. Ils prirent officiellement possession de l’anse et construisirent une batterie de tir à l’entrée du port.</p>
<p>(Un dessin montre un poste de traite avec un drapeau, dans l’anse.)</p>
<p>Narrateur&nbsp; Plus tard, le navire marchand Argonaut arriva, en juillet, avec à son bord des ouvriers chinois et des provisions pour le poste de traite de John Meares. Une dispute éclata entre Martínez et le capitaine du bateau, James Colnett. Accusant les commerçants de fourrures britanniques d’empiéter sur le territoire espagnol, Martínez saisit les bateaux et arrêta l’équipage. Au milieu de l’escarmouche, le chef Callicum, beau-frère du chef Maquinna, fut tué par les Espagnols. John Meares retourna en Angleterre, en passant par la Chine, en avril 1790, apportant les nouvelles des injustices subies par sa compagnie de traite et demandant l’aide du gouvernement.</p>
<p>Mais comment les Britanniques allaient-ils répondre à ces offenses?</p>
