<p>(As the video begins, there is upbeat Celtic music with violin.)</p>
<p>A Narrator says: How did Captain Vancouver navigate the oceans? Well, he relied on a magnetic compass to know which direction the ship was sailing.</p>
<p>(Animation of a compass pointing north.)</p>
<p>Narrator: While the navigator knew the ship&rsquo;s general direction, the problem was figuring out how far the ship had travelled once he had lost sight of the land.</p>
<p>(Animation of a ship sailing far into the Atlantic Ocean, away from Great Britain.)</p>
<p>Narrator: North or south was easy to determine using latitude; a method developed by Arabian Navigators in the 9th century. They applied imaginary lines around the earth east to west, and numbered them from zero degrees at the equator to 90 degrees at each of the poles.</p>
<p>(Animation of the earth, with lines of latitude drawn horizontally around Earth every ten degrees north and south of the Equator. The Equator is labelled 0 degrees. The Artic is 90 degrees North, and Antarctica is 90 degrees South.)</p>
<p>Narrator: Explorers would then use math rules relating to triangles called trigonometry to measure the angle between the horizon and the North Star. The North Star- also called Polaris- is the perfect point to measure from because it barely changes its position &ndash; and is conveniently located right above the North Pole.</p>
<p>(The world is animated spinning. The North Star is drawn above the Arctic, and does not move.)</p>
<p>Narrator: With an instrument called a sextant, the sailing crew could measure the angle, and if it said, say, 50 degrees, that would mean their ship is located at 50 degrees south of the North Pole. 90 degrees minus 50 degrees equals 40 degrees. So the ship is located at latitude 40 degrees north of the equator. Pretty cool, right? Using this method, the crew could know exactly how far they&rsquo;ve travelled north or south, and keep perfectly positioned until they spotted land again.   (A sextant is shown. It is a triangular-shaped instrument, with mirrors and a telescope. A trigonometry calculation is drawn on the world. A line connects the ship to the North Star. Another line drawn away from the ship is labelled the &ldquo;horizon line&rdquo;. The angle between these two lines from the ship is 50 degrees. The line of latitude the ship is on is labelled 50 degrees North.)</p>
<p>Narrator: However, figuring out how far east or west the ship had travelled remained a big problem. To solve this, Captain Vancouver was able to use an innovative new method that had just been perfected by his predecessor, Captain Cook. The solution relied on the regular rotation of the earth in relation to the sun and a very accurate clock. Here&rsquo;s how it works. We know that the earth rotates from east to west 360 degrees every 24 hours. Just do the math, and 360 divides by 24 to make 15. So, in one hour the earth moves 15 degrees relative to the sun. Still with me? Just like latitude, degrees of longitude was established to mark new imaginary lines around the earth, but these lines run north to south. And because the British thought this idea up, they decided that the zero degrees longitude line - or the Prime Meridian - should run right through the Greenwich observatory, located in London England.</p>
<p>(Lines of longitude are drawn vertically on Earth, from the Arctic down to Antarctica. The Prime Meridian is marked as 0 degrees longitude.)</p>
<p>Narrator: If you have an accurate clock onboard your ship and set it to the time at Greenwich &ndash; Greenwich Mean Time - you can then compare Greenwich time against the ship&rsquo;s local time to determine how far you are east or west of Greenwich. Here&rsquo;s an example, First the navigator has to determine the local noon time where the ship is located. He does this with a sextant to measure when the sun is at its highest point in the sky. If at 12 noon local time our clock shows Greenwich Mean Time is 4 in the afternoon, then we can calculate that we are 4 hours behind Greenwich time. Knowing that one hour is 15 degrees - we must be 4 hours times 15 degrees behind Greenwich, So, 60 degrees west of England. Simple, right?</p>
<p>(A map of the world is shown. The time on the Prime Meridian is displayed by a clock as 16:00. The Prime Meridian is labelled GMT, standing for Greenwich Mean Time. The time at the line of longitude the ship is on is 12:00, labelled as GMT -4, or 60 degrees west.)</p>
<p>Narrator: While this method of determining longitude was fairly easy to understand, it still required a super reliable clock in order to do it. And a clock accurate enough for the job did not exist. In 1714 the British government offered a prize of 20,000 pounds to anyone who could pull this off. That&rsquo;s about $4 Million today! Well, in 1761 a clockmaker named John Harrison finally did it with his invention of the marine chronometer.</p>
<p>(A historic drawing of John Harrison sitting in a chair. He wears upper-class clothing, including a buttoned coat and a white wig. An animated H4 Marine Chronometer is shown. It looks like a pocket watch with a clock face.)</p>
<p>Narrator: Captain James Cook gave Harrison&rsquo;s chronometer its first long run test by using it on his second and third voyages exploring the Pacific Ocean over a number of years. Cook was delighted with it. Because explorers could now easily determine their exact location in terms of both latitude and longitude, it became possible for Cook and then later Captain Vancouver, to draw very accurate maps.</p>
<p>(World is shown. Lines of latitude are labelled as (y). Lines of longitude are labelled (x).)</p>
<p>Narrator: Previous attempts to create a map without knowing a ship's exact location was essentially guesswork. Look at this early Russian map of the Northwest coast, and now compare it to this one here created by Captain Vancouver.</p>
<p>(The Russian map shows a map of North America with little detail and inaccurate coastlines. Captain Vancouver&rsquo;s map is very detailed, including individual islands.)</p>
<p>Narrator: Landmarks and ocean depths along the coastline could be recorded in more detail than ever before by marking exact positions of longitude x and latitude y. And that&rsquo;s how Captain Vancouver navigated the oceans hundreds of years ago!</p>