<p>(As the video begins, there is upbeat Celtic music with violin. The background noise is waves crashing)</p>
<p>A Narrator says: What were the vessels like that Captain Vancouver sailed in?</p>
<p>(A three-dimensional side view of an animated HMS Discovery is shown. It’s an 18th-century ship with 3 masts and many sails. The bottom half of the ship has a rounded brown hull. Lining the front and bottom of the hull is a grey-brown keel, and on the bottom-back is a grey-brown rectangle, known as the rudder. Above the hull is the flat deck, with a lighter-brown wood. Attached to the hull, just below the deck, are lighter-brown horizontal pieces of wood called “spars”. Many vertical ropes and rope ladders connect the spars to the masts and sails above. At the back of the ship, is a cabin room with the only windows on the ship. </p>
<p>The ship has three masts perpendicular to the deck with sails.</p>
<p>At the front of the ship, there is a long piece of wood that looks like a mast, but it comes out of the nose of the ship at a 45-degree angle to the deck. This is called a bowsprit, and it has triangular sails attached.</p>
<p>Hanging off the back of the ship is a large flag of the Red Ensign, a flag flown by the British Navy. The flag is red, with a small Union Jack in the top left corner.)</p>
<p> Narrator: A European ship in the 1700s was made from a variety of different wood. The frame of the vessel was made from White Oak, because of its strength and resistance to rotting.</p>
<p>(The image of the ship is made semi-transparent. The grey-brown keel, rudder, and frame of the ship are opaque, highlighting them as being made of white oak wood). </p>
<p>Narrator: The decks and hull planking were made from cedar or fir.</p>
<p>(The ship is again made semi-transparent. This time, the brown hull and lighter-brown deck are made opaque, highlighting them as being made of cedar or fir wood.)</p>
<p>Narrator: And Sitka Spruce was preferred for the masts and spars as they could more easily bend without breaking in heavy winds.</p>
<p>(The ship is again made semi-transparent. This time, the masts, spars, and the bowsprit at the front of the vessel.)</p>
<p>Narrator: A mast would be “stepped” into the keel and then secured in place by shrouds and stays made from tar covered hemp rope.</p>
<p>(The side planks of the hull disappear, providing a view of the frame of the vessel. The vertical masts continue straight through the deck until they reach the bottom of the hull. It is unclear where the shrouds are, but a coil of black tar-covered hemp rope is shown as an example of the material.)</p>
<p>Narrator: Vessels like this needed a lot of looking after, so crew included a number of carpenters.</p>
<p>(A black and white drawing of five male carpenters appears on screen.)</p>
<p>Narrator: Masts and spars would frequently need to be replaced. Leaks were a constant concern. In Vancouver’s time the vessel’s bottom was also sheathed in copper to protect it against Teredo worm which is a saltwater clam that burrows into the timber. The copper bottom also helped a ship to slip faster through the water.</p>
<p>(A copper shell is seen covering the bottom half of the hull. Teredo worm is a small white worm, and a photograph shows the holes they make in a piece of wood.)</p>
<p>Narrator: European vessels were powered by the wind using a combination of four-sided “square” sails and triangular “Lateen” sails made from canvas.</p>
<p>(The square sails are attached to the three vertical masts (3 on the front mast, 3 on the middle mast, and 2 on the back mast), and two on the bottom of the bowsprit. There are 10 square sails total. There are four triangular lateen sails total. Two are located in between the bowsprit and front mast, and the other two between the front and middle mast.)</p>
<p>Narrator: The design of these vessels evolved from Venetian, Roman and Viking boats that originally sailed along the European coastline. </p>
<p>(A timeline of ships appears on the screen. The timeline of ships includes a Knarr, which has one mast and sail. The next ships in the timeline are: Koh (1180 CE), Kog (1250 CE), Carrack (1450 CE), Nao (1490 CE), Venetian Carrack (1500 CE), English Galleon (1550 CE), and Spanish Galleon (1550 CE). Over time, the ships increasingly have more sails, masts, and deeper hulls. The Galleons are reminiscent of the brig.) </p>
<p>Narrator: By the 16th century, bigger vessels with enclosed decks were developed to cross the ocean. Square sails were more commonly used for long ocean crossings because they captured more wind. On the downside, a square-rigged ship ideally needed to have the wind coming from behind or beside it.</p>
<p>(A graphic shows how the wind direction pushes into the rectangular sails to move the ship forward. The rectangular sails can be changed to turn slightly to the left or right to better catch the wind. For example, if the wind was coming from the back right of the ship, the sails would be turned slightly to the left, so that more of the backside of the sails is exposed to the oncoming wind.)</p>
<p>Narrator: Because sailors had to go aloft to change the sails, which means climbing up the rigging, these vessels required large crews. There was also a strong possibility of losing a seaman from falling off the rigging and going overboard. Sadly, it was not always possible to go back and find them. </p>
<p>(There is an animation of seamen climbing up a rope ladder to the crow’s nests high up on the masts. One seaman falls off into the water.)</p>
<p>Narrator: Captain Vancouver had two vessels for his expedition, His Majesty’s Ship Discovery (HMS Discovery for short) and HMS Chatham.</p>
<p>(A similar animated HMS Chatham ship is seen beside the HMS Discovery. The HMS Chatham is half the size, shorter, and has two masts instead of three. The Chatham’s sails are also half the size of the HMS Discovery’s.)</p>
<p>Narrator: Both vessels were ideal for survey work; they had shallow drafts which meant they could get in close to shore.</p>
<p>(The draft is identified as the vertical distance between the bottom of the hull and the waterline). </p>
<p>Narrator: They also had rounded nearly flat bottoms which meant they would be less likely to roll over if they did become grounded. That’s very handy when you’re sailing in unknown waters. The Discovery was about 100 feet long and 28 feet across. It was very similar to Captain Cook’s ship, HMS Endeavour. The design was based on a Collier, a ship that transports coal. Consequently, the hull was very strong and there was a large amount of space below the deck.</p>
<p>(A drawing of the inside of the hull shows multiple levels and big open spaces.)</p>
<p>Narrator: The Chatham was half the size, 53 feet long and 22 feet across. As a general rule, the bigger the sail area and the longer the vessel the faster it will go. The Discovery had a top speed of 8 nautical miles in one hour. That’s about 15 kilometres per hour. The Chatham was a “brig’ which meant it was rigged mostly with square sails on two masts. The Discovery was a “fully rigged ship” which meant it was rigged mostly with square sails on three masts. The British navy classified these vessels as “sloops of war” which meant they had less than 20 large guns. The Discovery had 10 guns and the Chatham had 4. By comparison, a first-rate British Navy warship from this period would have over 100 large guns and was roughly twice the size of the Discovery. </p>
<p>Narrator: The Discovery had a crew of 100 men which included 9 ship officers, 38 able seamen to sail the ship, a military force of 16 marines, and skilled tradesmen such as carpenters, sailmakers, cooks, servants, gunners and a surgeon.</p>
<p>(An infographic also shows icons of 8 carpenters, 6 cooks, 6 servants, and 10 gunners. The back of the HMS Discovery is also shown, with the word “Discovery” on the back in gold lettering.)</p>
<p>Narrator: The Chatham had a crew of 45 in a similar combination of officers, seaman, marines and tradesmen. Life onboard both vessels would have been very cramped.</p>
<p>(An infographic next to the HMS Chatham shows icons of 4 officers, 18 seamen, 6 marines, 3 carpenters, 3 sailmakers, 3 cooks, 3 servants, 4 gunners and 1 surgeon. The back of the HMS Chatham also has gold lettering spelling “Chatham”.)</p>
<p>Narrator: Why are square sails uncommon today? By the 1800s, multiple mast “schooners” were becoming popular, particularly for trading and fishing vessels. They employed a fore-and-aft rig. This meant that rather than having the sails positioned across the ship using spars the sail ran along the length of the ship using booms.</p>
<p>(An animated schooner appears. It looks very modern compared to the HMS Discovery. The black hull is long and thin, and the deck lies close to the water. There are four masts all of the same height. Each mast has one tall, while, rectangular sail and a smaller triangular sail near the top. Attached between the bowsprit and the first mast are five triangle sails. There is another white sail between each set of masts. A boom is labelled as a long wooden bar perpendicular to the bottom of the mast. It anchors the bottom of the large rectangular sails.)</p>
<p>Narrator: Less crew was needed on a schooner because the sails could be changed on deck, no crew was needed to go aloft. The fore-and-aft sails also allowed the vessel to sail closer to the wind, which means it could sail with the wind nearer to the bow of the ship. This ultimately shortened the length of the journey.</p>
<p>(The fore-and-aft sails are the 5 triangular sails at the front of the ship. A graphic shows the wind coming in the direction opposite of which the ship is sailing. The wind first contacts the triangular sails.)</p>
<p>Narrator: Modern sailing yachts today still use a fore and aft sail rig. They also have metal masts and deeper keels which can support much larger sails.</p>
<p>(An animated modern sailing yacht appears on the screen. It has a long hull with a very short vertical height. The deck is even closer to the water than the schooner’s deck was. There is one central mast with two large right triangular sails coming off of it. There are some diagonal ropes connecting the mast and deck.)</p>
<p>The Narrator says jokingly: Unlike vessels in Captain Vancouver’s time, ships today usually have a lot fewer cannons.</p> 