<p>A narrator reads a journal entry: “[At] two in the afternoon of Monday the 27th…we anchored in 12 fathoms of water…this way a fine sandy beach…by the felling of a few trees, a very good situation was obtained for the observatory and tents.” Captain George Vancouver, Restoration Bay, May 1793. </p>
<p>(A journal entry appears in cursive over an image of the ocean and mountains in Heiltsuk territory. Pensive music plays in the background.)</p>
<p>Dylan Burrows, an Anishinaabe Historian says: The Heiltsuk people witnessed the Vancouver expedition at the start of its second season as these uninvited guests remap their territory. Elroy White, invited us to Bella Bella to learn more about Vancouver's passage through his people's waters.</p>
<p>(Dylan is standing in a forest. His hair is tied back and he is wearing a beige short sleeved shirt.)  </p>
<p>Elroy is an archeologist, Potlatch historian, dancer and hereditary leader who combines land based and traditional research practices, including the use of historical journals kept by Captain Vancouver and his crew. He spoke with us in Bella Bella's big house about why he became an archeologist.</p>
<p>(Elroy sits in front of two-house posts inside the Big House. He has gray hair and glasses. He is wearing an orange t-shirt and jeans.)</p>
<p>Elroy: When I was a kid, I wanted to be an explorer, but I didn’t know how to do it at the time. As I started to learn my culture, I realized I didn’t have to go very far away, I could just do it around my territory. And so, I started using the tools of archaeology to help me become more familiar with the sites of my ancestry. And I became a teacher and singer, here, in these big houses. You know, these songs and dances are connected to these house posts, connected to the front of the Big House, they’re connected to the drum log, and each chief has their own set of songs and dances and histories. So, if somebody says ‘I have this kind of dance,’ they’re actually sharing a part of their history that goes back, and has been passed down through different generations. So, when I was trained as an archaeologist, I was trained to think of things as material culture; it’s a physical thing. For me though, I’m a potlatcher, I see family trees, I hear songs, and I feel their presence on the land – which is something you shouldn’t do as a scientist, but I’m not strictly a scientist. </p>
<p>(We see a docked open ocean cruiser.)</p>
<p>Dylan: Early the next morning, we travelled with Elroy on board the Northern Lights to learn more about his work. </p>
<p>Elroy: I still remember Vancouver’s journals; just not his, but any fur trader or any notable person who made notes. I’m trying to correlate their notes with the information that we know, our cultural history. </p>
<p>(Elroy is talking to Dylan while the boat travels. Sound of the engine in the background.)  </p>
<p>Dylan: Heiltsuk people had always traded furs with their neighbours, and they had been trading them with Europeans for several years before Vancouver’s arrival. More than 50 village dotted this territory when Vancouve visited the coast. </p>
<p>(Map of the Northwest coast showing Heiltsuk territory outlined.)  </p>
<p>Traditionally, Heiltsuk disassembled their big houses and moved with the seasons to different parts of the territory to trade, to hunt, or gather food according to the chiefs’ inherited right and strength, but also responsibility to care for their people and the lands they occupied.</p>
<p>In 1862, the smallpox epidemic killed as much as two-thirds of the Indigenous inhabitants of the Northwest Coast. Under pressure from missionaries and colonial officials, Heilstuk gradually evacuated many of these villages and gathered at Old Town and later at Bella Bella. Elroy has been studying these ancestral villages for nearly twenty years. Today, we’re going to visit some of them. </p>
<p>(A map of Heiltsuk territory shows the location of Old Town and Bella Bella.)</p>
<p>Elroy: Okay Dylan, we left Bella Bella. That’s where all our people amalgamated together, all our tribes after smallpox hit. And now we’re travelling south through Lama Pass. We’re going to go east towards King Island, and we’re going to make a quick visit to ‘Háƛ̓iğvis, or Port John.</p>
<p>(A map of Heiltsuk territory shows the route from Bella Bella to the first stop.) </p>
<p>Dylan: Elroy’s research locates and maps ancient stone fish traps located near these ancestral villages. He also works with the Heiltsuk Integrated Resource Management Department to map culturally significant sites. These stone wall structures near rivers and creeks were widespread along the Indigenous coast. Fish drifting inshore on a rising tide swim over the stone wall and then become trapped when the tide recedes. </p>
<p>(A graphic demonstrates how the fish traps work.)</p>
<p>Elroy: My father’s family, the White side, on his dad’s side, this is where they grew up. This was their village. Just to know that my family actually worked in these traps at one time, they walked these beaches, they went up the creek, they probably went over to the rock art when they had some time to go take a look, look at those paintings. </p>
<p>Dylan: Carved or painted rock art is often found near these ancestral villages. High on a cliff overlooking the village site. Elroy re-discovered a painting that may be connected to Vancouver’s visit. Some scholars believe this image represents a sea monster’s mouth, other popular interpretations think it is a UFO. Elroy has another interpretation.</p>
<p>Elroy: To me, the shape of the bottom resembles a gḷ́w̓a, a canoe. And the top part, to me that looks like the top of a canvas boat. And inside of it, you can see straight, they look like paddles sticking up. They’re not people, they’re paddles. That’s what I think they are. And the people below are the ones who are greeting the boat. And when I think of George Vancouver’s notes, the people went out to him. Vancouver didn’t go to the village. So, these people look like they’re going to surround the boat for trading purposes. </p>
<p>(Images of the rock art being described are shown.) </p>
<p>Dylan: Could he be correct? We know that Vancouver expedition completed their survey work on board small open sailing boats. Here’s what Archibald Menzies, Vancouver’s surgeon and naturalist noted in his journal: </p>
<p>Narrator reads a journal entry: “Our boats and people were much better fitted out for withstanding the inclemency of the weather than they were in the previous season…a large awning spread over the whole boat that equally screened the people & their provisions & clothing from getting wet in rainy weather which was…apt to [drain] their strength in their constant & fatiguing exercise on the oars.” May 29th, 1793. </p>
<p>(A journal entry appears in cursive over a painting of one of Vancouver’s small boats.) </p>
<p>Dylan: We left here to travel up Johnson’s Channel. </p>
<p>(A map of Heiltsuk territory shows the boat’s route north up the channel.)  </p>
<p>Elroy: We’re no longer in Y̓ísdáitx̌v territory, we’re now in W̓uíƛ̓itx̌v. Which means inland people, and we’re coming up to a village where Vancouver had travelled by and he noticed a village on a rock. He describes a rock, and he mentions it – I think it was only one house. And on that house there’s a form line or a design on the front, just like our Big House in Bella Bella. And I really believe that where we’re going to today, we are actually going to see which island that he passed along the way. And there’s the island right there. </p>
<p>Narrator reads a journal entry: “The village was situated on a bare rock about fifty yards from the main land…This Rock was covered with Houses built close to each other…it had more the appearance of one large House than many different ones, they were most curiously painted in all colours, with the most extravagant grotesque figures of Men, Beasts and Fishes…” Midshipman Edward Bell, June 13th, 1793.</p>
<p>(A journal entry appears in cursive over an image of a small island with large spruce trees.) </p>
<p>Dylan: Earlier, Elroy explained to us how to understand this house decoration known as form line art. </p>
<p>Elroy: Any kind of form line are designed to represent a supernatural being or a crest figure. So, we’re all part of crests. The main crests, so far, are Raven, Eagle, Killer Whale, and Wolf. And if that was their house, they would have been on the front of the big house, and they would be informing everybody you know who’s house you were going to. And they have their own stories, what we call núyṃ́, and it’s a story of creation or first generation meaning that they have old, old ancestry. </p>
<p>Dylan: Back on the boat, Elroy explains his archaeological methods for identifying village sites. </p>
<p>Elroy: There are certain criteria that we look for where a village would have been situated, and one of them would be tall spruce trees, bushes in the front, then it would have had a sloping side. And if we were able to inspect the ground, it would have had black, greasy shell midden. In this case, this one here has a rock carving in front of it, which lends further support that this is where Vancouver went by and noticed the house with the form line design. So, this island here, it looks small, but once you walk on it, it’s very big. And where these spruce trees are, they probably are growing on the old big house frames. They are less than 200 years old. Where all the water is rippling over the rocks, that’s where the rock carvings are. Yes, They’re under water now. The tide is way too high. </p>
<p>Dylan: At the next village site we learned more about Elroy’s work with Heiltsuk youth. </p>
<p>(A map of Heiltsuk territory shows the boat’s northwest route.) </p>
<p>Elroy: I’ve been to this village a number of times and I bring a lot of kids here. The head chief here was Wakas. There’s apparently ten to twelve, or maybe even twenty homes at one time. </p>
<p>Dylan: What are the youths’ reactions when they come to this place?</p>
<p>Elroy: They’re really excited because many of them are descended from the current, or the late Chief Wákas. So, they’re reconnecting to the place where their ancestry came from. And the other thing that they’re excited about is that they get to help my crew do some archaeology work so that we can understand the site a lot better through science and through oral history. </p>
<p>Dylan: When their work was completed, the boats returned to the observatory at Restoration Bay to board the HMS Discovery and HMS Chatham and sail back out to sea.</p>
<p>It is unclear what might have been their last stop in Heiltsuk territory – it could have been the winter village at this location or was it the summer village site at Cape Swaine? </p>
<p>Elroy tells us more about what these large villages were like.</p>
<p>(A map of Heiltsuk territory shows the boat’s route going west out to the open ocean.) </p>
<p>Elroy: This is the village of Qaba, and it was part of the Q̓úqvay̓áitx̌v tribe, and it was the winter village at one time up until 1890. There was a number of families here, and the biggest house here was right in the middle, and it belonged to a chief named Woyala – he was a big Killer Whale chief. Beside him would have been Chief Q̓ait and he was from the Eagle crest. And then there was other chiefs: Chief Q̓víɫtakv, Himasbat from the Raven, Hṃ́zit was also here because his ancestry was literally with every tribe of our territory. So, this is the place, I believe where when the Discovery in the Chatham came here and they anchored somewhere nearby and they kept referencing that there were activities going on in this winter village. </p>
<p>Narrator reads a journal entry: The Chiefs generally approached us with the ceremonial first rowing round the vessel and departed in the same manner, singing a song that was by no means unpleasing. This was sometimes continued until they had retired a considerable distance. They seemed a happy, cheerful people and to live in the strictest harmony and good fellowship with each other. They were well versed in commerce. About 180 of the sea otter pelts were purchased in the course of their several visits. Captain George Vancouver, June 1793.</p>
<p>(A journal entry appears in cursive over a painting of the HMS Discovery with a canoe nearby.) </p>
<p>Elroy: Wow, we sure made a journey. Holy cow! We went around three islands, and we went through three tribal groups too. And it shows that these big chiefs just didn’t stay in their own tribes. At that time, they were really looking for people to trade with, and then trading amongst themselves and doing their own seasonal gathering of food, and so on. It’s amazing how when we mind map these family trees, we can actually correlate these with the historical journals. </p>
<p>Dylan: Just mind blowing.</p>
<p>Elroy: Sharing the núyṃ́s and the songs. So, I’m putting those altogether. It’s an approach that I prefer to use, and I call it M̓ṇúxvit. That literally means to become one or unite. So, instead of using just one approach, it’s combining them all together. </p>
<p>Dylan: And, you know, that's what we're doing right now, bringing together oral histories, the written historical record to rewrite the history of this place or, you know recover the history of this place.</p>
<p>Elroy: Mm hmm. That's true.</p>
<p>(Elroy and Dylan talking together on the boat.)</p>
<p>(Drone footage shows the boat near the village site. Pensive music plays in the background as the image fades out to black.) </p>
