<p>(A journal entry appears in cursive.)</p>
<p>A narrator reads out a journal entry: “[At] two in the afternoon of Monday the 27th…we anchored in 12 fathoms of water…this way a fine sandy beach…by the felling of a few trees, a very good situation was obtained for the observatory and tents.” Captain George Vancouver, Restoration Bay, May 1793. </p>
<p>(Map showing Restoration Bay and an animation of two ships arriving.)</p>
<p>Dylan says: The Heiltsuk people witnessed the Vancouver expedition at the start of its second season, remapping the Indigenous lands the Europeans called the Pacific Northwest. Our team was invited to visit the Heiktsuk people to learn more about Vancouver’s time in their territory. We met Q̓íx̌itasu, also known as Elroy White, at the Heiltsuk community Big House in Bella Bella. Q̓íx̌itasu is an archaeologist. He has been using Vancouver’s journals as a part of his research. </p>
<p>(Q̓íx̌itasu, pronounced kee-at-soo, sits in front of two house posts inside the Big House. He has gray hair and glasses. He is wearing an orange t-shirt and jeans.)</p>
<p>Q̓íx̌itasu: When I was a kid, I wanted to be an explorer, but I didn’t know how to do it at the time. As I started to learn my culture, I realized I didn’t have to go very far away, I could just do it around my territory. And so I started using the tools of archaeology to help me become more familiar with the sites of my ancestry. And I became a teacher and singer, here, in these big houses. You know, these songs and dances are connected to these house posts, connected to the front of the Big House, they’re connected to the drum log, and each chief has their own set of songs and dances and histories. So, if somebody says ‘I have this kind of dance,’ they’re actually sharing a part of their history that goes back, and has been passed down through different generations. So, when I was trained as an archaeologist, I was trained to think of things as material culture; it’s a physical thing. For me though, I’m a potlatcher, I see not simply like other archaeologists who come in and record it just as a material thing – I see family trees, I hear songs, and I feel their presence on the land – which is something you shouldn’t do as a scientist, but I’m not strictly a scientist. </p>
<p>Dylan: Early the next morning, we travelled with Q̓íx̌itasu on board the Northern Lights to learn more about his work. </p>
<p>Q̓íx̌itasu: So I’ve literally been everywhere in our territory, and as I do go through the territory, I still remember Vancouver’s journals; just not his, but any fur trader or any notable person who made notes. I’m trying to correlate their notes with the information that we know, our cultural history. </p>
<p>Dylan: Heiltsuk peoples had always traded furs with their neighbours, and they had been trading them with Europeans for several years before Vancouver’s arrival. More than 50 ancient village sites doted this territory in Vancouver’s time here. Traditionally, Heiltsuk people disassembled the walls and roofs of their big houses and moved with the seasons to different parts of the territory to trade, hunt, or gather food according to the chiefs’ ɫáxvái, his inherited power and strength to occupy certain village sites at certain times of the year. Later in 1862, the smallpox epidemic killed as much as two-thirds of the Indigenous peoples living on the Northwest Coast. Under pressure from missionaries and colonial officials, the Heilstuk tribes gradually evacuated many of these villages and gathered at Old Town and later at Bella Bella. Q̓íx̌itasu has been studying these ancestral villages for nearly twenty years. Today, we’re going to visit some of them. </p>
<p>Q̓íx̌itasu: Okay Dylan, we left Bella Bella. That’s where all our people amalgamated together, all our tribes after smallpox hit. And so, now we’re travelling south through Lama  Pass. We’re going to go east towards King Island, and we’re going to make a quick visit to ‘Háƛ̓iğvis, or Port John.</p>
<p>Dylan: Q̓íx̌itasu’s research includes locating and mapping the ancient stone fish traps located near these ancestral villages. This work is on behalf of HIRMD, the Heiltsuk Integrated Resource Management Department. These stone wall structures near rivers and creeks were widespread along the Indigenous coast. Fish drifting inshore on a rising tide swim over the stone wall and then become trapped when the tide recedes. My father’s family, the White side, on his dad’s side, this is where they grew up. This was their village. Just to know that my family actually worked in these traps at one time, they walked these beaches, they went up the creek, they probably went over to the rock art when they had some time to go take a look, look at those paintings. </p>
<p>Dylan: Carved or painted rock art is often found near these ancestral villages. High on a cliff overlooking ‘Háƛ̓iğvis, Q̓íx̌itasu discovered a painting that may be connected to Vancouver’s visit. We climbed up the cliff face together to take a closer look. Some researchers think the painting is of a sea monster’s open mouth. Q̓íx̌itasu has another theory. </p>
<p>Q̓íx̌itasu: To me, the shape of the bottom resembles a gḷ́w̓a, a canoe or a boat. And the top part, to me that looks like the top of a canvas boat. Inside of it, you can see straight, they look like paddles sticking up. They’re not people, they’re paddles. That’s what I think they are. The people below are the ones who are greeting the boat. When I think of George Vancouver’s notes, the people went out to him. Vancouver didn’t go to the village. So, these people look like they’re going to surround the boat for trading purposes. </p>
<p>Dylan: Could Q̓íx̌itasu be correct? We know that Vancouver and his crew travelled on board small open sailing boats when doing their survey work. Archibald Menzies, the surgeon and naturalist that accompanied Vancouver, made this interesting entry in his journal: “Our boats and people were much better fitted out for withstanding the inclemency of the weather than they were in the previous season…a large awning spread over the whole boat that equally screened the people & their provisions & clothing from getting wet in rainy weather which was…apt to [drain] their strength in their constant & fatiguing exercise on the oars.” Archibald Menzies, May 29th, 1793. We left ‘Háƛ̓iğvis to travel up Johnson’s Channel. </p>
<p>Q̓íx̌itasu: We’re no longer in Y̓ísdáitx̌v tribe territory, we’re now W̓uíƛ̓itx̌v in tribe, and we’re coming up to a village where Vancouver had travelled by and he notices a village on a rock. He describes a rock, and he mentions it – I think it was only one house. On that house there’s a formline or a design on the front, just like our Big House in Bella Bella. I really believe that where we’re going to today, you’ll see which island that he passed along the way. </p>
<p>Dylan reads out a journal entry: “The village was situated on a bare rock about fifty yards from the main land…This Rock was covered with Houses built close to each other…I believe…it had more the appearance of one large House than many different ones, they were most curiously painted in all Colours, with the most extravagant grotesque figures of Men, Beasts and Fishes…” Midshipman Edward Bell, June 13th, 1793.</p>
<p>Dylan: Earlier, Q̓íx̌itasu explained to us how to understand this house decoration known as formline painting. </p>
<p>Q̓íx̌itasu: Any kind of formline are designed to represent a supernatural being or a crest figure. So we’re all part of crests. The main crests, so far, are Raven, Eagle, Killer Whale, and Wolf. If that was their house, they would have been on the front of the big house, and they would be informing everyone who’s house you were going to. That they have their own stories, what we call núyṃ́, and it’s a story of creation or first generation meaning that they have old, old ancestry. </p>
<p>Dylan: On board the Northern Lights, Q̓íx̌itasu explains his archaeological methods for identifying village sites. </p>
<p>Q̓íx̌itasu: There are certain criteria that we look for where a village would have been situated, and one of them is tall spruce trees, bushes in the front, then it would have had a sloping side. If we were able to inspect the ground, it would have had black, greasy shell midden. In this case, this one here has a rock carving in front of it, which lends further support that this is where Vancouver went by and noticed the house with the formline design. And there’s the island right there. So this island here, it looks small, but once you walk on it, it’s very big. Where these spruce trees are, they probably are growing on the old big house frames. Where all the water is rippling over the rocks, that’s where the rock carvings are. The rock carvings are under water. The tide is way to high. </p>
<p>Dylan: Our next stop was Xvnís, the winter village of Chief Wákas. Here we learned more about Q̓íx̌itasu’s work with Heiltsuk youth. </p>
<p>Q̓íx̌itasu: I’ve been to this village a number of times and I bring a lot of kids here. There were apparently ten to twelve, or maybe even twenty homes at one times. </p>
<p>Dylan: What are the youths’ reactions when they come to this place?</p>
<p>Q̓íx̌itasu: They’re really excited because many of them are descended from the current, or the late Chief Wákas. So they’re reconnecting to the place where their ancestry came from. The other thing that they’re excited about is that they get to help my crew do some archaeology work so that we can understand the site a lot better through science and through oral history. Then we sings here. XXX has a really beautiful song, and there’s other songs. We just reconnect them through the old stories and through those songs. Sometimes when we’re singing, some of the kids just feel like dancing. That feeling is just overwhelming. </p>
<p>Dylan: When their work was completed, the boats returned to the observatory at Restoration Bay to board the Discovery and Chatham and sail back out to sea. It is unclear from the journals what might have been their last stop in Heiltsuk territory – it could have been the winter village at Qábá or was it the summer village of Chief Wákas here at Cape Swain? At Qábá, ​​Q̓íx̌itasu tells us more about what those large villages were like.</p>
<p>Q̓íx̌itasu: It was part of the Q̓úqvay̓áitx̌v tribe, and it was the winter village at one time up until 1890. There was a number of families here, and the biggest house here was right in the middle, and it belonged to a chief named Woyala – he was a big Killer Whale chief. Beside him would have been Chief Q̓ait and he was from the Eagle crest. And then there was other chiefs: Chief Q̓víɫtakv, Himasbat from the Raven, Hṃ́zit was also here. </p>
<p>Dylan reads journal entry: “[We received] the compliments of chief Whacosh, with two other chiefs of consequence, one named Amzeet, the other Nestaw Daws. We were now visited by many of the inhabitants, who brought the skins of the sea otter and other animals for barter, but we could not obtain any supply of fish…The whole party, consisting of [a] hundred and upwards, conducted themselves with great good order.” Captain Vancouver, 15 June, 1793</p>
<p>Q̓íx̌itasu: Wow, we sure made a journey. Holy cow! We went around three islands, and we went through three tribal groups too. It shows that these big chiefs didn’t just stay in their own tribes. At that time, they were really looking for people to trade with, and then trading amongst themselves and doing their own seasonal gathering of food, and so on. It’s amazing how when we mind map these family trees, we can actually correlate these with the historical journals. It actually puts into perspective that for me I can’t just rely on one oral historical source. When I come out here with the kids, I’m always using either science, reading historical journals, sharing the núyṃ́s and the songs. I’m putting those all together. It’s an approach that I prefer to use, and I call it M̓ṇúxvit. That literally means to become one or unite. Instead of using just one approach, it’s combining them all together. </p>