<p>Un narrateur lit la transcription d’un journal de bord&nbsp; «&nbsp;[À] quatorze heures, lundi le 27… nous avons jeté l’ancre dans 12 brasses d’eau… où se trouvait une plage de sable fin… par l’abattage de quelques arbres, on obtint une très bonne situation pour l’observatoire et les tentes.&nbsp;» Capitaine George Vanvouver, baie Restoration, mai 1793. </p>
<p>(Une entrée de journal apparaît en écriture cursive sur une image de l’océan et des montagnes en territoire Heiltsuk. De la musique méditative joue en arrière-plan.)</p>
<p>Dylan Burrows, un historien Anishinaabe dit&nbsp; Le peuple Heiltsuk a été témoin de l’expédition de Vancouver au début de sa deuxième saison alors que ces invités non désirés étaient occupés à recartographier leur territoire. Elroy White nous invite à Bella-Bella afin de nous renseigner davantage sur le passage de Vancouver dans les eaux de son peuple. </p>
<p>(Dylan est debout en forêt. Il a les cheveux attachés et porte une chemise à manches courtes beige.)</p>
<p>Elroy est archéologue, historien du potlatch, danseur et chef héréditaire qui combine les recherches sur le terrain et les techniques de recherche traditionnelles, dont l’utilisation des journaux de bord historiques du capitaine Vancouver et de son équipage. Il nous parle, alors qu’il se trouve dans une grande maison Bella-Bella, des raisons qui l’ont amené à devenir archéologue. </p>
<p>(Elroy est assis devant deux piliers de maison sculptés à l’intérieur de la grande maison. Il a les cheveux gris et porte des lunettes. Il porte un t-shirt orange et des jeans.)</p>
<p>Elroy&nbsp; Quand j’étais enfant, je voulais être explorateur, mais je ne savais pas comment y arriver à l’époque. Quand j’ai commencé à étudier ma culture, j’ai réalisé que je n’avais pas à aller très loin, que je pouvais le faire sur mon territoire. Je me suis donc mis à utiliser les outils de l’archéologie pour m’aider à me familiariser avec les sites de mes ancêtres. Et je suis devenu professeur et chanteur, ici, dans ces grandes maisons. Vous savez, ces chansons et ces danses sont liées à ces piliers de maison sculptés, liées à la devanture de la grande maison, liées au tronc qui sert de tambour, et chaque chef à son propre répertoire de chansons, de danses et d’histoires. Alors si quelqu’un dit «&nbsp;j’ai ce type de danse&nbsp;», il partage en fait une partie de son histoire ancienne qui a été transmise à travers les générations. Donc, quand j’ai été formé comme archéologue, j’ai été formé pour penser aux choses en tant que culture matérielle, c’est quelque chose de physique. Moi, par contre, je pratique le potlatch, je vois les arbres généalogiques, j’entends des chansons, et je sens leur présence sur le territoire –, quelque chose qu’il est impossible de faire en tant que scientifique, mais je ne suis pas qu’un scientifique.</p>
<p>(On voit un croiseur de haute-mer amarré.)</p>
<p>Dylan&nbsp; Tôt le lendemain, nous avons voyagé avec Elroy à bord du Northern Lights afin d’en connaître davantage sur son travail.</p>
<p>Elroy&nbsp; Je me souviens encore des journaux de bord de Vancouver; pas seulement le sien, mais ceux de tous les marchands de fourrures ou notables qui ont pris des notes. J’essaie d’établir une corrélation entre leurs notes et l’information que nous possédons, notre histoire culturelle. </p>
<p>(Elroy parle à Dylan pendant que le bateau avance. On entend le bruit du moteur en arrière-plan.) </p>
<p>Dylan&nbsp; Les Heiltsuk ont toujours fait le commerce de la fourrure avec leurs voisins, et ils le faisaient avec des Européens depuis plusieurs années déjà avant l’arrivée de Vancouver. Il y avait plus de 50 villages sur ce territoire lorsque Vancouver a visité la côte. </p>
<p>(Carte de la côte du Nord-Ouest montrant les limites du territoire des Heiltsuk.)</p>
<p>Traditionnellement, les Heiltsuk défaisaient leurs grandes maisons et les déménageaient selon les saisons dans différentes parties du territoire pour commercer, chasser ou amasser de la nourriture, selon le droit et le pouvoir héréditaire des chefs mais aussi pour honorer leur responsabilité qui était de prendre soin de leur peuple et des terres qu’ils occupaient.</p>
<p>En 1862, l’épidémie de variole a tué les deux tiers des habitants autochtones de la côte du Nord-Ouest. Sous l’insistance des missionnaires et des agents coloniaux, les Heilstuk ont petit-à-petit évacué plusieurs de ces villages pour se regrouper à Old Town, et plus tard à Bella-Bella. Elroy étudie ces villages ancestraux depuis près de vingt ans. Aujourd’hui, nous allons en visiter quelques-uns. </p>
<p>(Une carte du territoire Heiltsuk montre la localisation de Old Town et de Bella-Bella.)</p>
<p>Elroy&nbsp; Ok Dylan, nous avons quitté Bella-Bella. C’est là que tout notre peuple s’est rassemblé, toutes nos tribus, après que la variole eut frappé. Et maintenant nous allons vers le sud à travers le passage Lama. Nous allons aller vers l’est vers l’île King et faire une visite rapide à ‘Háƛ̓iğvis, ou Port John.</p>
<p>(Une carte du territoire Heiltsuk montre la route entre Bella-Bella et le premier arrêt.)</p>
<p>Dylan&nbsp; Les recherches d’Elroy localisent et cartographies des anciens pièges à poisson en pierre près de ces villages ancestraux. Il travaille également avec le Département de gestion intégrée des ressources Heiltsuk afin de cartographier les sites culturellement significatifs. Ces murs de pierre construits près des rivières et des ruisseaux étaient très répandus le long de la côte autochtone. Les poissons ayant dérivé vers la rive à marée montante, passaient par-dessus le mur et y restaient coincés lorsque la marée se retirait. </p>
<p>(Un graphique démontre la façon dont les pièges à poissons fonctionnaient.)</p>
<p>Elroy: La famille de mon père, le côté Blanc, du côté de son père, c’est ici qu’ils ont grandi. Ceci était leur village. Il faut juste savoir que les membres de ma famille ont travaillé à ces pièges à un moment donné, qu’ils ont marché le long de ces plages, remonté le ruisseau, et sont probablement allés jusqu’à la roche peinte, lorsqu’ils avaient un peu de temps pour explorer, pour voir ces peintures.</p>
<p>Dylan&nbsp; Des pierres sculptées ou peintes sont souvent retrouvées près de ces villages ancestraux. En haut d’une falaise surplombant le village, Elroy a redécouvert une peinture qui pourrait être liée à la visite de Vancouver. Certains chercheurs croient que cette image représente la bouche d’un monstre marin, d’autres interprétations populaires pensent que c’est un OVNI. Elroy a quant à lui une autre interprétation. </p>
<p>Elroy&nbsp; Pour ma part, la forme du dessous ressemble à un gḷ́w̓a, un canot. Et la partie du haut, je trouve que ça ressemble au-dessus d’un bateau de toile. Et à l’intérieur, tu peux voir des lignes droites, comme des rames qui sortent. Ce ne sont pas des gens, ce sont des rames. C’est ce que je pense. Et les gens plus bas sont ceux accueillant les bateaux. Et quand je pense aux notes de George Vancouver, les gens sont venus à lui. Vancouver n’est pas allé dans le village. Alors, on dirait que ces gens s’en vont entourer le bateau pour faire de la traite. </p>
<p>(On voit des images des pétroglyphes qui sont décrits.)</p>
<p>Dylan&nbsp; Ce pourrait-il qu’il ait raison? Nous savons que les gens de l’expédition de Vancouver ont réalisé leurs relevés à bord de petits voiliers ouverts. Voici ce qu’Archibald Menzies, chirurgien et naturaliste pour Vancouver a noté dans son journal&nbsp;</p>
<p>Le narrateur lit l’entrée du journal&nbsp; «&nbsp;Nos bateaux et nos gens étaient beaucoup mieux équipés pour affronter le mauvais temps que lors de la saison passée… un grand auvent couvrant tout le bateau et qui permettaient tant aux passagers, aux provisions qu’aux vêtements de rester au sec lorsqu’il pleuvait… [le fait d’être mouillés] pouvait [drainer] leur force dans l’exercice constant et éreintant du maniement des rames.&nbsp;» 29 mai 1793.</p>
<p>(Une transcription d’un journal de bord apparait en écriture cursive sur une toile d’un des petits bateaux de Vancouver.)</p>
<p>Dylan&nbsp; Nous avons quitté notre position pour continuer notre voyage le long du canal de Johnson.</p>
<p>(Une carte du territoire Heiltsuk montre le trajet emprunté par le bateau le long du canal, vers le nord.)</p>
<p>Elroy&nbsp; Nous ne sommes plus en territoire Y̓ísdáitx̌v. Nous sommes maintenant en territoire W̓uíƛ̓itx̌v, ce qui signifie le peuple de l’intérieur des terres. Nous approchons d’un village près duquel Vancouver est passé et où il avait vu un village sur un rocher. Il décrit un rocher et il le mentionne – je crois qu’il n’y avait qu’une maison. Et sur cette maison il y a une ligne-forme ou un dessin sur la devanture, comme sur notre grande maison à Bella-Bella. Et je crois vraiment que là où nous allons aujourd’hui, nous allons voir l’île près de laquelle il est passé. C’est cette île, juste là. </p>
<p>Le narrateur lit une entrée de journal&nbsp; «&nbsp;Le village était situé sur un rocher dénudé à environ cinquante verges du continent… Ce rocher était couvert de maisons construites très près les unes des autres… ce qui donnait davantage l’impression d’une seule grande maison plutôt que de plusieurs maisons séparées. Elles étaient peintes d’une des plus curieuses façons, de toutes les couleurs, avec des figures des plus grotesques d’hommes, de bêtes et de poissons…&nbsp;» Edward Bell, aspirant de marine, 13 juin 1793. </p>
<p>(Une transcription d’un journal de bord apparaît en écriture cursive sur une image d’une petite île avec de grands épicéas dessus.) </p>
<p>Dylan&nbsp; Plus tôt, Elroy nous avait expliqué comment interpréter ces décorations de maison connues sous le nom de système de lignes-formes.</p>
<p>Elroy&nbsp; Tous les types de lignes-formes sont conçus pour représenter un être surnaturel ou une figure clanique. Nous faisons donc tous partis d’un clan. Les principaux clans, jusqu’à maintenant, sont le Corbeau, l’Aigle, l’Épaulard et le Loup. Et si c’était leur maison, ils auraient été sur la devanture de la grande maison pour ainsi informer tous ceux qui allait y entrer de l’identité du propriétaire. Et ils ont leurs propres histoires, ce que nous appelons núyṃ́; il s’agit d’une histoire de création ou de première génération, ce qui signifie qu’ils ont de très, très vieux ancêtres.</p>
<p>Dylan&nbsp; De retour sur le bateau, Elroy explique ses méthodes archéologiques pour identifier les sites villageois. </p>
<p>Elroy&nbsp; Il y a certains critères que nous recherchons pour trouver où un village pourrait avoir été situé, et l’un d’eux est la présence d’épicéas, d’arbres à l’avant, puis la présence d’un versant en pente. Et si nous pouvons inspecter le sol, nous pourrions y retrouver un amas de coquillage noir et graisseux. Dans ce cas-ci, il y a des incisions dans le rocher devant, ce qui vient appuyer l’hypothèse selon laquelle c’est ici que Vancouver serait passé et aurait remarqué la maison avec les lignes-formes. Donc, cette île, elle a l’air d’être très petite, mais quand tu marches dessus, elle est en fait très grande. Et là où se trouvent les épicéas, ils poussent probablement sur le cadre de l’ancienne grande maison. Ils ont moins de 200 ans. Là où l’eau clapote sur les rochers, c’est là où se trouvent les incisions dans le rocher. Oui, elles sont présentement sous l’eau. La marée est beaucoup trop haute.</p>
<p>Dylan&nbsp; Sur le site du prochain village, nous en apprenons davantage à propos du travail d’Elroy auprès de la jeunesse heiltsuk.</p>
<p>(Une carte du territoire des Heiltsuk montre le trajet du bateau en direction nord-ouest.)</p>
<p>Elroy&nbsp; Je suis venu dans ce village plusieurs fois et j’ai amené beaucoup d’enfants ici. Le chef principal ici était Wákas. Il y avait apparemment dix à douze, ou même peut-être vingt maisons à une certaine époque. </p>
<p>Dylan&nbsp; Quelles sont les réactions des jeunes quand ils viennent ici?</p>
<p>Elroy&nbsp; Ils sont très excités parce que plusieurs d’entre eux sont des descendants du chef actuel ou de l’ancien chef Wákas. Ils se reconnectent donc avec l’endroit d’où proviennent leurs ancêtres. Et l’autre chose qui les excite est qu’ils doivent aider mon équipe à faire des fouilles archéologiques, afin que nous puissions comprendre le site beaucoup mieux à travers la science et à travers l’histoire orale.</p>
<p>Dylan&nbsp; Leur travail complété, les bateaux retournaient à l’observatoire de la baie Restoration afin de remonter à bord du NSM Discovery et du NSM Chatham et repartir en mer.</p>
<p>Il n’est pas clair de savoir quel aurait été leur dernier arrêt en territoire Heiltsuk – serait-ce le village hivernal situé ici, ou plutôt le village estival au cap Swaine?</p>
<p>Elroy nous en dit davantage à propos de ce à quoi pouvaient ressembler ces grands villages.</p>
<p>(Une carte du territoire Heiltsuk montre le trajet emprunté par le bateau vers l’ouest puis vers le large.)</p>
<p>Elroy&nbsp; Ceci est le village de Qaba, qui faisait partie de la tribu Q̓úqvay̓áitx̌v. C’était le village hivernal à une époque, jusqu’en 1890. Il y avait plusieurs familles ici, et la plus grande maison était en plein au centre et elle appartenait au chef nommé Woyala – il était un grand chef Épaulard. À côté de lui il y avait le chef Q̓ait qui était du clan de l’Aigle. Puis il y avait d’autres chefs&nbsp; Le chef Q̓víɫtakv, Himasbat du clan du Corbeau, Hṃ́zit était ici aussi parce que ses ancêtres étaient littéralement avec chaque tribu sur notre territoire. Alors c’est ici, je crois, que le Discovery et le Chatham sont venus et qu’ils ont jetés l’ancre quelque part près d’ici, et qu’ils ont rapporté qu’il y avait des activités dans ce village hivernal.</p>
<p>Le narrateur lit une entrée de journal&nbsp; En général, les chefs s’approchaient à la rame de nous pour exécuter le premier tour cérémoniel du navire, puis repartaient de la même manière, en chantant une chanson qui n’était pas déplaisante. Ils continuaient parfois à chanter jusqu’à ce qu’ils soient rendus assez loin. Ils semblaient être des gens heureux et joyeux, vivant dans la plus stricte harmonie et en bons termes entre eux. Ils étaient bien versés dans le commerce. Environ 180 fourrures de loutres de mer ont été achetées au cours de leurs nombreuses visites. Capitaine George Vancouver, juin 1793.</p>
<p>(Une inscription d’un journal de bord apparait en écriture cursive sur une toile du NSM Discovery avec un canot près de lui.)</p>
<p>Elroy&nbsp; Wow, nous avons fait tout un voyage. Sacrebleu! Nous avons fait le tour de trois îles et croisé trois tribus. Et cela a démontré que ces grands chefs ne restaient pas dans leurs propres tribus. À l’époque, ils cherchaient vraiment des gens avec qui commercer, puis ils traitaient entre eux et faisaient leurs propres collectes saisonnières de nourriture, et ainsi de suite. C’est fascinant de voir comment, quand nous cartographions mentalement ces arbres généalogiques, nous pouvons vraiment arriver à faire des corrélations avec les journaux de bord historiques.</p>
<p>Dylan&nbsp; C’est tout simplement époustouflant.</p>
<p>Elroy&nbsp; Je partage les núyṃ́s et les chansons. Et je mets tout cela ensemble. C’est une approche que je préfère utiliser et que j’appelle M̓ṇúxvit. Littéralement, cela signifie devenir un seul ou s’unifier. Donc, plutôt que d’utiliser une seule approche, ça les combine toutes ensembles. </p>
<p>Dylan&nbsp; Et, tu sais, c’est ce que nous faisons en ce moment, de mettre ensemble les histoires orales et les archives historiques écrites pour réécrire l’histoire de cet endroit ou, tu sais, retrouver l’histoire de cet endroit.</p>
<p>Elroy&nbsp; Mm-hmm. C’est vrai.</p>
<p>(Elroy et Dylan parlent ensemble sur le bateau.)</p>
<p>(Des images filmées à partir d’un drone montrent le bateau près du site du village. De la musique méditative joue en arrière-plan pendant que l’image s’estompe jusqu’à ce que l’écran devienne noir.)</p>