<p>Un narrateur lit la transcription d&rsquo;un journal de bord : &laquo; [&Agrave;] quatorze heures, lundi le 27&hellip; nous avons jet&eacute; l&rsquo;ancre dans 12 brasses d&rsquo;eau&hellip; o&ugrave; se trouvait une plage de sable fin&hellip; par l&rsquo;abattage de quelques arbres, on obtint une tr&egrave;s bonne situation pour l&rsquo;observatoire et les tentes. &raquo; Capitaine George Vanvouver, baie Restoration, mai 1793.&nbsp;</p>
<p>(Une entr&eacute;e de journal appara&icirc;t en &eacute;criture cursive sur une image de l&rsquo;oc&eacute;an et des montagnes en territoire Heiltsuk. De la musique m&eacute;ditative joue en arri&egrave;re-plan.)</p>
<p>Dylan Burrows, un historien Anishinaabe dit : Le peuple Heiltsuk a &eacute;t&eacute; t&eacute;moin de l&rsquo;exp&eacute;dition de Vancouver au d&eacute;but de sa deuxi&egrave;me saison alors que ces invit&eacute;s non d&eacute;sir&eacute;s &eacute;taient occup&eacute;s &agrave; recartographier leur territoire. Elroy White nous invite &agrave; Bella-Bella afin de nous renseigner davantage sur le passage de Vancouver dans les eaux de son peuple.&nbsp;</p>
<p>(Dylan est debout en for&ecirc;t. Il a les cheveux attach&eacute;s et porte une chemise &agrave; manches courtes beige.)</p>
<p>Elroy est arch&eacute;ologue, historien du potlatch, danseur et chef h&eacute;r&eacute;ditaire qui combine les recherches sur le terrain et les techniques de recherche traditionnelles, dont l&rsquo;utilisation des journaux de bord historiques du capitaine Vancouver et de son &eacute;quipage. Il nous parle, alors qu&rsquo;il se trouve dans une grande maison Bella-Bella, des raisons qui l&rsquo;ont amen&eacute; &agrave; devenir arch&eacute;ologue.&nbsp;</p>
<p>(Elroy est assis devant deux piliers de maison sculpt&eacute;s &agrave; l&rsquo;int&eacute;rieur de la grande maison. Il a les cheveux gris et porte des lunettes. Il porte un t-shirt orange et des jeans.)</p>
<p>Elroy : Quand j&rsquo;&eacute;tais enfant, je voulais &ecirc;tre explorateur, mais je ne savais pas comment y arriver &agrave; l&rsquo;&eacute;poque. Quand j&rsquo;ai commenc&eacute; &agrave; &eacute;tudier ma culture, j&rsquo;ai r&eacute;alis&eacute; que je n&rsquo;avais pas &agrave; aller tr&egrave;s loin, que je pouvais le faire sur mon territoire. Je me suis donc mis &agrave; utiliser les outils de l&rsquo;arch&eacute;ologie pour m&rsquo;aider &agrave; me familiariser avec les sites de mes anc&ecirc;tres. Et je suis devenu professeur et chanteur, ici, dans ces grandes maisons. Vous savez, ces chansons et ces danses sont li&eacute;es &agrave; ces piliers de maison sculpt&eacute;s, li&eacute;es &agrave; la devanture de la grande maison, li&eacute;es au tronc qui sert de tambour, et chaque chef &agrave; son propre r&eacute;pertoire de chansons, de danses et d&rsquo;histoires. Alors si quelqu&rsquo;un dit &laquo; j&rsquo;ai ce type de danse &raquo;, il partage en fait une partie de son histoire ancienne qui a &eacute;t&eacute; transmise &agrave; travers les g&eacute;n&eacute;rations. Donc, quand j&rsquo;ai &eacute;t&eacute; form&eacute; comme arch&eacute;ologue, j&rsquo;ai &eacute;t&eacute; form&eacute; pour penser aux choses en tant que culture mat&eacute;rielle, c&rsquo;est quelque chose de physique. Moi, par contre, je pratique le potlatch, je vois les arbres g&eacute;n&eacute;alogiques, j&rsquo;entends des chansons, et je sens leur pr&eacute;sence sur le territoire &ndash;, quelque chose qu&rsquo;il est impossible de faire en tant que scientifique, mais je ne suis pas qu&rsquo;un scientifique.</p>
<p>(On voit un croiseur de haute-mer amarr&eacute;.)</p>
<p>Dylan : T&ocirc;t le lendemain, nous avons voyag&eacute; avec Elroy &agrave; bord du Northern Lights afin d&rsquo;en conna&icirc;tre davantage sur son travail.</p>
<p>Elroy : Je me souviens encore des journaux de bord de Vancouver; pas seulement le sien, mais ceux de tous les marchands de fourrures ou notables qui ont pris des notes. J&rsquo;essaie d&rsquo;&eacute;tablir une corr&eacute;lation entre leurs notes et l&rsquo;information que nous poss&eacute;dons, notre histoire culturelle.&nbsp;</p>
<p>(Elroy parle &agrave; Dylan pendant que le bateau avance. On entend le bruit du moteur en arri&egrave;re-plan.)&nbsp;</p>
<p>Dylan : Les Heiltsuk ont toujours fait le commerce de la fourrure avec leurs voisins, et ils le faisaient avec des Europ&eacute;ens depuis plusieurs ann&eacute;es d&eacute;j&agrave; avant l&rsquo;arriv&eacute;e de Vancouver. Il y avait plus de 50 villages sur ce territoire lorsque Vancouver a visit&eacute; la c&ocirc;te.&nbsp;</p>
<p>(Carte de la c&ocirc;te du Nord-Ouest montrant les limites du territoire des Heiltsuk.)</p>
<p>Traditionnellement, les Heiltsuk d&eacute;faisaient leurs grandes maisons et les d&eacute;m&eacute;nageaient selon les saisons dans diff&eacute;rentes parties du territoire pour commercer, chasser ou amasser de la nourriture, selon le droit et le pouvoir h&eacute;r&eacute;ditaire des chefs mais aussi pour honorer leur responsabilit&eacute; qui &eacute;tait de prendre soin de leur peuple et des terres qu&rsquo;ils occupaient.</p>
<p>En 1862, l&rsquo;&eacute;pid&eacute;mie de variole a tu&eacute; les deux tiers des habitants autochtones de la c&ocirc;te du Nord-Ouest. Sous l&rsquo;insistance des missionnaires et des agents coloniaux, les Heilstuk ont petit-&agrave;-petit &eacute;vacu&eacute; plusieurs de ces villages pour se regrouper &agrave; Old Town, et plus tard &agrave; Bella-Bella. Elroy &eacute;tudie ces villages ancestraux depuis pr&egrave;s de vingt ans. Aujourd&rsquo;hui, nous allons en visiter quelques-uns.&nbsp;</p>
<p>(Une carte du territoire Heiltsuk montre la localisation de Old Town et de Bella-Bella.)</p>
<p>Elroy : Ok Dylan, nous avons quitt&eacute; Bella-Bella. C&rsquo;est l&agrave; que tout notre peuple s&rsquo;est rassembl&eacute;, toutes nos tribus, apr&egrave;s que la variole eut frapp&eacute;. Et maintenant nous allons vers le sud &agrave; travers le passage Lama. Nous allons aller vers l&rsquo;est vers l&rsquo;&icirc;le King et faire une visite rapide &agrave; &lsquo;H&aacute;ƛ̓iğvis, ou Port John.</p>
<p>(Une carte du territoire Heiltsuk montre la route entre Bella-Bella et le premier arr&ecirc;t.)</p>
<p>Dylan : Les recherches d&rsquo;Elroy localisent et cartographies des anciens pi&egrave;ges &agrave; poisson en pierre pr&egrave;s de ces villages ancestraux. Il travaille &eacute;galement avec le D&eacute;partement de gestion int&eacute;gr&eacute;e des ressources Heiltsuk afin de cartographier les sites culturellement significatifs. Ces murs de pierre construits pr&egrave;s des rivi&egrave;res et des ruisseaux &eacute;taient tr&egrave;s r&eacute;pandus le long de la c&ocirc;te autochtone. Les poissons ayant d&eacute;riv&eacute; vers la rive &agrave; mar&eacute;e montante, passaient par-dessus le mur et y restaient coinc&eacute;s lorsque la mar&eacute;e se retirait.&nbsp;</p>
<p>(Un graphique d&eacute;montre la fa&ccedil;on dont les pi&egrave;ges &agrave; poissons fonctionnaient.)</p>
<p>Elroy: La famille de mon p&egrave;re, le c&ocirc;t&eacute; Blanc, du c&ocirc;t&eacute; de son p&egrave;re, c&rsquo;est ici qu&rsquo;ils ont grandi. Ceci &eacute;tait leur village. Il faut juste savoir que les membres de ma famille ont travaill&eacute; &agrave; ces pi&egrave;ges &agrave; un moment donn&eacute;, qu&rsquo;ils ont march&eacute; le long de ces plages, remont&eacute; le ruisseau, et sont probablement all&eacute;s jusqu&rsquo;&agrave; la roche peinte, lorsqu&rsquo;ils avaient un peu de temps pour explorer, pour voir ces peintures.</p>
<p>Dylan : Des pierres sculpt&eacute;es ou peintes sont souvent retrouv&eacute;es pr&egrave;s de ces villages ancestraux. En haut d&rsquo;une falaise surplombant le village, Elroy a red&eacute;couvert une peinture qui pourrait &ecirc;tre li&eacute;e &agrave; la visite de Vancouver. Certains chercheurs croient que cette image repr&eacute;sente la bouche d&rsquo;un monstre marin, d&rsquo;autres interpr&eacute;tations populaires pensent que c&rsquo;est un OVNI. Elroy a quant &agrave; lui une autre interpr&eacute;tation.&nbsp;</p>
<p>Elroy : Pour ma part, la forme du dessous ressemble &agrave; un gḷ́w̓a, un canot. Et la partie du haut, je trouve que &ccedil;a ressemble au-dessus d&rsquo;un bateau de toile. Et &agrave; l&rsquo;int&eacute;rieur, tu peux voir des lignes droites, comme des rames qui sortent. Ce ne sont pas des gens, ce sont des rames. C&rsquo;est ce que je pense. Et les gens plus bas sont ceux accueillant les bateaux. Et quand je pense aux notes de George Vancouver, les gens sont venus &agrave; lui. Vancouver n&rsquo;est pas all&eacute; dans le village. Alors, on dirait que ces gens s&rsquo;en vont entourer le bateau pour faire de la traite.&nbsp;</p>
<p>(On voit des images des p&eacute;troglyphes qui sont d&eacute;crits.)</p>
<p>Dylan : Ce pourrait-il qu&rsquo;il ait raison? Nous savons que les gens de l&rsquo;exp&eacute;dition de Vancouver ont r&eacute;alis&eacute; leurs relev&eacute;s &agrave; bord de petits voiliers ouverts. Voici ce qu&rsquo;Archibald Menzies, chirurgien et naturaliste pour Vancouver a not&eacute; dans son journal :</p>
<p>Le narrateur lit l&rsquo;entr&eacute;e du journal : &laquo; Nos bateaux et nos gens &eacute;taient beaucoup mieux &eacute;quip&eacute;s pour affronter le mauvais temps que lors de la saison pass&eacute;e&hellip; un grand auvent couvrant tout le bateau et qui permettaient tant aux passagers, aux provisions qu&rsquo;aux v&ecirc;tements de rester au sec lorsqu&rsquo;il pleuvait&hellip; [le fait d&rsquo;&ecirc;tre mouill&eacute;s] pouvait [drainer] leur force dans l&rsquo;exercice constant et &eacute;reintant du maniement des rames. &raquo; 29 mai 1793.</p>
<p>(Une transcription d&rsquo;un journal de bord apparait en &eacute;criture cursive sur une toile d&rsquo;un des petits bateaux de Vancouver.)</p>
<p>Dylan : Nous avons quitt&eacute; notre position pour continuer notre voyage le long du canal de Johnson.</p>
<p>(Une carte du territoire Heiltsuk montre le trajet emprunt&eacute; par le bateau le long du canal, vers le nord.)</p>
<p>Elroy : Nous ne sommes plus en territoire Y̓ísdáitx̌v. Nous sommes maintenant en territoire W̓uíƛ̓itx̌v, ce qui signifie le peuple de l&rsquo;int&eacute;rieur des terres. Nous approchons d&rsquo;un village pr&egrave;s duquel Vancouver est pass&eacute; et o&ugrave; il avait vu un village sur un rocher. Il d&eacute;crit un rocher et il le mentionne &ndash; je crois qu&rsquo;il n&rsquo;y avait qu&rsquo;une maison. Et sur cette maison il y a une ligne-forme ou un dessin sur la devanture, comme sur notre grande maison &agrave; Bella-Bella. Et je crois vraiment que l&agrave; o&ugrave; nous allons aujourd&rsquo;hui, nous allons voir l&rsquo;&icirc;le pr&egrave;s de laquelle il est pass&eacute;. C&rsquo;est cette &icirc;le, juste l&agrave;.&nbsp;</p>
<p>Le narrateur lit une entr&eacute;e de journal : &laquo; Le village &eacute;tait situ&eacute; sur un rocher d&eacute;nud&eacute; &agrave; environ cinquante verges du continent&hellip; Ce rocher &eacute;tait couvert de maisons construites tr&egrave;s pr&egrave;s les unes des autres&hellip; ce qui donnait davantage l&rsquo;impression d&rsquo;une seule grande maison plut&ocirc;t que de plusieurs maisons s&eacute;par&eacute;es. Elles &eacute;taient peintes d&rsquo;une des plus curieuses fa&ccedil;ons, de toutes les couleurs, avec des figures des plus grotesques d&rsquo;hommes, de b&ecirc;tes et de poissons&hellip; &raquo; Edward Bell, aspirant de marine, 13 juin 1793.&nbsp;</p>
<p>(Une transcription d&rsquo;un journal de bord appara&icirc;t en &eacute;criture cursive sur une image d&rsquo;une petite &icirc;le avec de grands &eacute;pic&eacute;as dessus.)&nbsp;</p>
<p>Dylan : Plus t&ocirc;t, Elroy nous avait expliqu&eacute; comment interpr&eacute;ter ces d&eacute;corations de maison connues sous le nom de syst&egrave;me de lignes-formes.</p>
<p>Elroy : Tous les types de lignes-formes sont con&ccedil;us pour repr&eacute;senter un &ecirc;tre surnaturel ou une figure clanique (&laquo; Crests &raquo;). Nous faisons donc tous partis d&rsquo;un clan. Les principaux clans, jusqu&rsquo;&agrave; maintenant, sont le Corbeau, l&rsquo;Aigle, l&rsquo;&Eacute;paulard et le Loup. Et si c&rsquo;&eacute;tait leur maison, ils auraient &eacute;t&eacute; sur la devanture de la grande maison pour ainsi informer tous ceux qui allait y entrer de l&rsquo;identit&eacute; du propri&eacute;taire. Et ils ont leurs propres histoires, ce que nous appelons núyṃ́; il s&rsquo;agit d&rsquo;une histoire de cr&eacute;ation ou de premi&egrave;re g&eacute;n&eacute;ration, ce qui signifie qu&rsquo;ils ont de tr&egrave;s, tr&egrave;s vieux anc&ecirc;tres.</p>
<p>Dylan : De retour sur le bateau, Elroy explique ses m&eacute;thodes arch&eacute;ologiques pour identifier les sites villageois.&nbsp;</p>
<p>Elroy : Il y a certains crit&egrave;res que nous recherchons pour trouver o&ugrave; un village pourrait avoir &eacute;t&eacute; situ&eacute;, et l&rsquo;un d&rsquo;eux est la pr&eacute;sence d&rsquo;&eacute;pic&eacute;as, d&rsquo;arbres &agrave; l&rsquo;avant, puis la pr&eacute;sence d&rsquo;un versant en pente. Et si nous pouvons inspecter le sol, nous pourrions y retrouver un amas de coquillage noir et graisseux. Dans ce cas-ci, il y a des incisions dans le rocher devant, ce qui vient appuyer l&rsquo;hypoth&egrave;se selon laquelle c&rsquo;est ici que Vancouver serait pass&eacute; et aurait remarqu&eacute; la maison avec les lignes-formes. Donc, cette &icirc;le, elle a l&rsquo;air d&rsquo;&ecirc;tre tr&egrave;s petite, mais quand tu marches dessus, elle est en fait tr&egrave;s grande. Et l&agrave; o&ugrave; se trouvent les &eacute;pic&eacute;as, ils poussent probablement sur le cadre de l&rsquo;ancienne grande maison. Ils ont moins de 200 ans. L&agrave; o&ugrave; l&rsquo;eau clapote sur les rochers, c&rsquo;est l&agrave; o&ugrave; se trouvent les incisions dans le rocher. Oui, elles sont pr&eacute;sentement sous l&rsquo;eau. La mar&eacute;e est beaucoup trop haute.</p>
<p>Dylan : Sur le site du prochain village, nous en apprenons davantage &agrave; propos du travail d&rsquo;Elroy aupr&egrave;s de la jeunesse heiltsuk.</p>
<p>(Une carte du territoire des Heiltsuk montre le trajet du bateau en direction nord-ouest.)</p>
<p>Elroy : Je suis venu dans ce village plusieurs fois et j&rsquo;ai amen&eacute; beaucoup d&rsquo;enfants ici. Le chef principal ici &eacute;tait Wákas. Il y avait apparemment dix &agrave; douze, ou m&ecirc;me peut-&ecirc;tre vingt maisons &agrave; une certaine &eacute;poque.&nbsp;</p>
<p>Dylan : Quelles sont les r&eacute;actions des jeunes quand ils viennent ici?</p>
<p>Elroy : Ils sont tr&egrave;s excit&eacute;s parce que plusieurs d&rsquo;entre eux sont des descendants du chef actuel ou de l&rsquo;ancien chef Wákas. Ils se reconnectent donc avec l&rsquo;endroit d&rsquo;o&ugrave; proviennent leurs anc&ecirc;tres. Et l&rsquo;autre chose qui les excite est qu&rsquo;ils doivent aider mon &eacute;quipe &agrave; faire des fouilles arch&eacute;ologiques, afin que nous puissions comprendre le site beaucoup mieux &agrave; travers la science et &agrave; travers l&rsquo;histoire orale.</p>
<p>Dylan : Leur travail compl&eacute;t&eacute;, les bateaux retournaient &agrave; l&rsquo;observatoire de la baie Restoration afin de remonter &agrave; bord du NSM Discovery et du NSM Chatham et repartir en mer.</p>
<p>Il n&rsquo;est pas clair de savoir quel aurait &eacute;t&eacute; leur dernier arr&ecirc;t en territoire Heiltsuk &ndash; serait-ce le village hivernal situ&eacute; ici, ou plut&ocirc;t le village estival au cap Swaine?</p>
<p>Elroy nous en dit davantage &agrave; propos de ce &agrave; quoi pouvaient ressembler ces grands villages.</p>
<p>(Une carte du territoire Heiltsuk montre le trajet emprunt&eacute; par le bateau vers l&rsquo;ouest puis vers le large.)</p>
<p>Elroy : Ceci est le village de Qaba, qui faisait partie de la tribu Q̓úqvay̓áitx̌v. C&rsquo;&eacute;tait le village hivernal &agrave; une &eacute;poque, jusqu&rsquo;en 1890. Il y avait plusieurs familles ici, et la plus grande maison &eacute;tait en plein au centre et elle appartenait au chef nomm&eacute; Woyala &ndash; il &eacute;tait un grand chef &Eacute;paulard. &Agrave; c&ocirc;t&eacute; de lui il y avait le chef Q̓ait qui &eacute;tait du clan de l&rsquo;Aigle. Puis il y avait d&rsquo;autres chefs : Le chef Q̓víɫtakv, Himasbat du clan du Corbeau, Hṃ́zit &eacute;tait ici aussi parce que ses anc&ecirc;tres &eacute;taient litt&eacute;ralement avec chaque tribu sur notre territoire. Alors c&rsquo;est ici, je crois, que le Discovery et le Chatham sont venus et qu&rsquo;ils ont jet&eacute;s l&rsquo;ancre quelque part pr&egrave;s d&rsquo;ici, et qu&rsquo;ils ont rapport&eacute; qu&rsquo;il y avait des activit&eacute;s dans ce village hivernal.</p>
<p>Le narrateur lit une entr&eacute;e de journal : En g&eacute;n&eacute;ral, les chefs s&rsquo;approchaient &agrave; la rame de nous pour ex&eacute;cuter le premier tour c&eacute;r&eacute;moniel du navire, puis repartaient de la m&ecirc;me mani&egrave;re, en chantant une chanson qui n&rsquo;&eacute;tait pas d&eacute;plaisante. Ils continuaient parfois &agrave; chanter jusqu&rsquo;&agrave; ce qu&rsquo;ils soient rendus assez loin. Ils semblaient &ecirc;tre des gens heureux et joyeux, vivant dans la plus stricte harmonie et en bons termes entre eux. Ils &eacute;taient bien vers&eacute;s dans le commerce. Environ 180 fourrures de loutres de mer ont &eacute;t&eacute; achet&eacute;es au cours de leurs nombreuses visites. Capitaine George Vancouver, juin 1793.</p>
<p>(Une inscription d&rsquo;un journal de bord apparait en &eacute;criture cursive sur une toile du NSM Discovery avec un canot pr&egrave;s de lui.)</p>
<p>Elroy : Wow, nous avons fait tout un voyage. Sacrebleu! Nous avons fait le tour de trois &icirc;les et crois&eacute; trois tribus. Et cela a d&eacute;montr&eacute; que ces grands chefs ne restaient pas dans leurs propres tribus. &Agrave; l&rsquo;&eacute;poque, ils cherchaient vraiment des gens avec qui commercer, puis ils traitaient entre eux et faisaient leurs propres collectes saisonni&egrave;res de nourriture, et ainsi de suite. C&rsquo;est fascinant de voir comment, quand nous cartographions mentalement ces arbres g&eacute;n&eacute;alogiques, nous pouvons vraiment arriver &agrave; faire des corr&eacute;lations avec les journaux de bord historiques.</p>
<p>Dylan : C&rsquo;est tout simplement &eacute;poustouflant.</p>
<p>Elroy : Je partage les núyṃ́s et les chansons. Et je mets tout cela ensemble. C&rsquo;est une approche que je pr&eacute;f&egrave;re utiliser et que j&rsquo;appelle M̓ṇ&uacute;xvit. Litt&eacute;ralement, cela signifie devenir un seul ou s&rsquo;unifier. Donc, plut&ocirc;t que d&rsquo;utiliser une seule approche, &ccedil;a les combine toutes ensembles.&nbsp;</p>
<p>Dylan : Et, tu sais, c&rsquo;est ce que nous faisons en ce moment, de mettre ensemble les histoires orales et les archives historiques &eacute;crites pour r&eacute;&eacute;crire l&rsquo;histoire de cet endroit ou, tu sais, retrouver l&rsquo;histoire de cet endroit.</p>
<p>Elroy : Mm-hmm. C&rsquo;est vrai.</p>
<p>(Elroy et Dylan parlent ensemble sur le bateau.)</p>
<p>(Des images film&eacute;es &agrave; partir d&rsquo;un drone montrent le bateau pr&egrave;s du site du village. De la musique m&eacute;ditative joue en arri&egrave;re-plan pendant que l&rsquo;image s&rsquo;estompe jusqu&rsquo;&agrave; ce que l&rsquo;&eacute;cran devienne noir.)</p>