<p>(On entend des tambours et des chants. On entend le vent souffler en arri&egrave;re-plan. Une photo couleur du chef Ambrose Maquinna avec les cheveux blancs et portant des lunettes carr&eacute;es et un t-shirt &agrave; l&rsquo;effigie du chef Maquinna de la fin des ann&eacute;es 1700. On peut lire le texte&nbsp;: &laquo;&nbsp;Ce film est inspir&eacute; des &eacute;crits de feu chef Ambrose Maquinna&nbsp;&raquo;.)</p>
<p>Une citation en texte &eacute;crit &agrave; la machine &agrave; &eacute;crire appara&icirc;t et se lit comme suit&nbsp;: &laquo;&nbsp;Nous sommes la Premi&egrave;re Nation de Mowachaht et Muchalaht, les gens de la baie Nootka sur la c&ocirc;te ouest de l&rsquo;&icirc;le de Vancouver. Cette r&eacute;gion a &eacute;t&eacute; le pays de nos anc&ecirc;tres depuis le d&eacute;but des temps. &hellip;. Nous sommes ici pour partager avec vous notre compr&eacute;hension de notre histoire et de notre culture, et en particulier de Yuquot, notre communaut&eacute; la plus importante.&nbsp;&raquo; Chef Ambrose Maquinna, Gold River, 1997</p>
<p>Narratrice&nbsp;: Yuquot signifie &laquo;&nbsp;l&agrave; o&ugrave; les vents viennent de toutes les directions.&nbsp;&raquo; Pour nous, Yuquot est le centre du monde et le meilleur endroit o&ugrave; &ecirc;tre, entre l&rsquo;abondance et l&rsquo;&eacute;nergie de l&rsquo;oc&eacute;an et la majest&eacute; et la richesse de la for&ecirc;t et des anses.</p>
<p>(Courts extraits vid&eacute;o de l&rsquo;anse de Yuquot et des collines bois&eacute;es et des plages autour. Prise de vue d&rsquo;un pilier de bienvenue sculpt&eacute;.)</p>
<p>Narratrice : C&rsquo;est un endroit de pouvoir et de changement. Un endroit qui regorge d&rsquo;histoires, dont celle du premier chef Maquinna rencontrant les Europ&eacute;ens lorsqu&rsquo;ils sont arriv&eacute;s ici sur leur &laquo;&nbsp;maisons flottantes&nbsp;&raquo;, il y a plus de 200 ans.&nbsp;</p>
<p>(Un dessin du chef Maquinna de la fin des ann&eacute;es 1700 portant les habits c&eacute;r&eacute;moniels traditionnels et un chapeau tiss&eacute;. Un tableau du navire NSM <em>Resolution</em>.&nbsp;</p>
<p>Narratrice : Nous &eacute;tions contents de la traite &ndash; l&rsquo;&eacute;change de quelques fourrures contre des biens auxquels nous attribuions une grande valeur, comme du fer et du tissu. Nous &eacute;tions attentifs &agrave; nous lier d&rsquo;amiti&eacute; avec tous nos visiteurs. Nos talents pour la diplomatie et pour le troc ont valu &agrave; Yuquot le nom d&rsquo;anse Amicale.</p>
<p>(Croquis de villageois traitant avec des commer&ccedil;ants de fourrures.)</p>
<p>Narratrice&nbsp;: Le commerce des fourrures a amen&eacute; Yuquot au centre de l&rsquo;histoire occidentale.&nbsp;</p>
<p>(Tableaux de navires britanniques et espagnols ancr&eacute;s &agrave; Yuquot.)</p>
<p>Citation &agrave; l&rsquo;&eacute;cran&nbsp;: &laquo;&nbsp;De nombreux navires se mirent &agrave; arriver &agrave; Yuquot. C&rsquo;&eacute;tait une bonne p&eacute;riode pour nous. Nous avons appris qu&rsquo;ils ne provenaient pas tous de la m&ecirc;me nation, ou ne parlaient pas tous la m&ecirc;me langue. Nous avons aussi appris que certains de nos visiteurs &eacute;taient de bonnes personnes alors que d&rsquo;autres &eacute;taient des sc&eacute;l&eacute;rats.&nbsp;&raquo; Chef Ambrose Maquinna, Gold River, 1997</p>
<p>(Le chef h&eacute;r&eacute;ditaire Michael Maquinna de la Premi&egrave;re Nation Mowachaht/Muchalaht est interview&eacute; &agrave; l&rsquo;&eacute;cran, devant un agrandissement d&rsquo;un dessin de leur village ancestral.)</p>
<p>Chef h&eacute;r&eacute;ditaire Michael Maquinna : &laquo;&nbsp;Au d&eacute;but, ce n&rsquo;&eacute;tait pas une mauvaise chose, mais avec le temps, nous avons r&eacute;alis&eacute; que les choses n&rsquo;avaient pas trop bien tourn&eacute;es pour les peuples des Premi&egrave;res Nations.&nbsp;&raquo;</p>
<p>Narratrice&nbsp;: Avec le d&eacute;clin de la population des loutres de mer, les bateaux ont cess&eacute; de venir &agrave; Yuquot. Bien que les marchands de fourrures aient quitt&eacute;s notre territoire, la maladie qu&rsquo;ils ont apport&eacute;e est rest&eacute;e, avec des cons&eacute;quences d&eacute;vastatrices.&nbsp;</p>
<p>(Le tambour et les chants en arri&egrave;re-plan se font entendre plus forts et plus puissants. Un tableau des navires de commerce des fourrures change pour une vid&eacute;o montrant l&rsquo;anse d&eacute;sormais vide.)&nbsp;</p>
<p>(Interview d&rsquo;archive datant de 1993 du chef Jerry Jack. Il a les cheveux noirs, porte de grosses lunettes et un coupe-vent bleu. Il s&rsquo;exprime beaucoup avec ses mains en parlant.)</p>
<p>Chef Jerry Jack&nbsp;: Certaines tribus de notre nation ont &eacute;t&eacute; compl&egrave;tement diss&eacute;min&eacute;es. Il n&rsquo;y a eu aucun survivant. Aucun.&nbsp;</p>
<p>Citation &agrave; l&rsquo;&eacute;cran&nbsp;: &laquo;&nbsp;Nous savons qu&rsquo;&agrave; une &eacute;poque, il y avait de nombreuses tribus, et que nous &eacute;tions plusieurs milliers&hellip; Au d&eacute;but du XX<sup>&egrave;me</sup> si&egrave;cle, nous &eacute;tions moins de 300. &raquo; Chef Ambrose Maquinna, Gold River, 1997.</p>
<p>Narratrice&nbsp;: Personne aujourd&rsquo;hui ne peut imaginer la souffrance qu&rsquo;a pu endurer les quelques survivants parmi notre peuple.</p>
<p>(Photo en noir et blanc de 1896 de vingt Muchalaht, certains plus &acirc;g&eacute;s et d&rsquo;autres jeunes enfants. Photo de E. Flemming.)</p>
<p>Citation &agrave; l&rsquo;&eacute;cran&nbsp;: &laquo;&nbsp;Depuis cette triste &eacute;poque, nous avons v&eacute;cu d&rsquo;autres situations humiliantes aux mains du gouvernement canadien&nbsp;: la perte de nos territoires, la perte de contr&ocirc;le sur nos propres affaires, la perte de nos enfants &ndash; notre avenir &ndash; dans les pensionnats.&nbsp;&raquo; Chef Ambrose Maquinna, Gold River, 1997.</p>
<p>(Ghoo-Noom-Tuuk-Tomith est interview&eacute;. Il est &acirc;g&eacute; et a les cheveux gris. Il porte une casquette de l&rsquo;&eacute;quipe de baseball des Rodgers et un manteau &agrave; carreaux rouges et noirs. Il est assis pr&egrave;s d&rsquo;un gros arbre.)</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;: Et je m&rsquo;appelle Ghoo-Noom-Tuuk-Tomith. C&rsquo;est mon vrai nom, et cela signifie &laquo;&nbsp;l&rsquo;esprit du loup&nbsp;&raquo;, et ce nom m&rsquo;a &eacute;t&eacute; enlev&eacute; lorsque j&rsquo;ai &eacute;t&eacute; au pensionnat.&nbsp;</p>
<p>(Musique m&eacute;lancolique. Photos de pensionnats.)</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;: L&rsquo;&Eacute;glise catholique m&rsquo;a donn&eacute; des noms catholiques, comme Joseph Peter; c&rsquo;est pourquoi mon nom est Raymond Joseph Peter. Raymond &eacute;tait un pr&eacute;nom, Joseph Peter m&rsquo;a &eacute;t&eacute; donn&eacute; par l&rsquo;&eacute;v&ecirc;que sans le consentement de mes parents, ou sans la permission de mes parents. Il y avait 12, 14 enfants ici. Ils ont &eacute;t&eacute; emmen&eacute;s et mis sur un bateau &agrave; vapeur pour aller au pensionnat &agrave; Kakawis Tofino.&nbsp;</p>
<p>(S&eacute;ries de photos en noir et blanc de jeunes gar&ccedil;ons travaillant avec des pelles et des b&ecirc;ches, portant des bambins et posant en uniforme scolaire pour une photo de classe.)</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;: Et nous savions peu de chose de l&rsquo;endroit o&ugrave; nous allions&hellip; Nous ne savions pas que nous allions en prison.</p>
<p>(Image en noir et blanc d&rsquo;un pensionnat et de religieux. Une autre photo avec un pr&ecirc;tre et de jeunes pensionnaires.)</p>
<p>Narratrice&nbsp;: Lorsque le gouvernement a pris les enfants, tout le monde a &eacute;t&eacute; d&eacute;vast&eacute;. Les enfants ne pouvaient pas apprendre leur langue, leurs traditions et leurs histoires.&nbsp;</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;: Tout le temps pass&eacute; l&agrave;-bas &eacute;tait pass&eacute; &agrave; travailler, travailler, travailler, avec tr&egrave;s peu d&rsquo;&eacute;cole. Nous passions la plupart du temps &agrave; construire des routes, &agrave; entreposer du charbon ou du bois pour le feu dans la fournaise.&nbsp;</p>
<p>(Photos en noir et blanc de gar&ccedil;ons et de filles dans diff&eacute;rentes poses au pensionnat.)</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;: Nous, les enfants, nous &eacute;tions forc&eacute;s &agrave; faire ce genre de travail, et c&rsquo;&eacute;tait tr&egrave;s dur pour nous, les enfants. C&rsquo;&eacute;tait terrible! Et on nous fouettait si on d&eacute;sob&eacute;issait. Nous recevions des coups de ceinture sur les mains ou sur les fesses. Les enfants, lorsqu&rsquo;ils mourraient, les parents n&rsquo;&eacute;taient pas inform&eacute;s. Ils &eacute;taient enterr&eacute;s &agrave; l&rsquo;&eacute;cole, sans que les parents ne sachent comment ou de quoi leurs enfants &eacute;taient morts.&nbsp;</p>
<p>Narratrice&nbsp;: En 1917, la compagnie d&rsquo;emballage Nootka a &eacute;tabli une conserverie pr&egrave;s de Yuquot.&nbsp;</p>
<p>(Photo en noir et blanc des &eacute;difices de la conserverie construits sur un quai avec plusieurs bateaux de p&ecirc;che ancr&eacute;s le long du quai. Photos de femmes portant un tablier avec les cheveux attach&eacute;s.)</p>
<p>Narratrice&nbsp;: Presque tout le monde travaillait l&agrave;. Alors que les femmes travaillaient dans la conserverie, les hommes s&rsquo;engageaient sur des bateaux lou&eacute;s ou achet&eacute;s avec des pr&ecirc;ts de la compagnie.</p>
<p>(Photo en noir et blanc de huit bateaux de p&ecirc;che align&eacute;s devant la conserverie.)</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;: Nous r&eacute;ussissions tr&egrave;s bien, nous &eacute;tions autonomes. Nous n&rsquo;&eacute;tions pas riches, mais nous gagnions notre vie dans l&rsquo;industrie de la p&ecirc;che. Il n&rsquo;y avait que des Autochtones, des Japonais et des Chinois. Tous les g&eacute;rants et les patrons &eacute;taient des Blancs.</p>
<p>(Photos en noir et blanc de femmes employ&eacute;es &agrave; la conserverie et de propri&eacute;taires blancs de la conserverie.)</p>
<p>Narratrice&nbsp;: &Agrave; une &eacute;poque, il y avait des conserveries tout le long de la c&ocirc;te de la C.-B., mais pour augmenter leurs profits, les compagnies ont ferm&eacute; les conserveries les plus &eacute;loign&eacute;es pour en construire de plus grosses dans les villes.&nbsp;</p>
<p>(Carte anim&eacute;e des conserveries le long de la c&ocirc;te de la C.-B.. Avec le temps, il y a eu de moins en moins de conserveries.)</p>
<p>Narratrice&nbsp;: La conserverie de Nootka a ferm&eacute; en 1945. Nous avons alors tent&eacute; d&rsquo;&eacute;tablir notre propre coop&eacute;rative de p&ecirc;che.</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;:&nbsp;&nbsp;Et cela a &eacute;t&eacute; r&eacute;duit &agrave; rien. Ils ont d&eacute;truit le camp de p&ecirc;che, ils ont tout pris. Et cela nous a fait vraiment mal. C&rsquo;&eacute;tait notre gagne-pain. Comme je l&rsquo;ai dit, pas pour devenir riches, mais pour gagner notre vie, hein.&nbsp;</p>
<p>Narratrice&nbsp;: Plut&ocirc;t que de nous aider &agrave; soutenir notre communaut&eacute;, le gouvernement voulait nous forcer &agrave; quitter Yuquot.&nbsp;</p>
<p>Ghoo-Noom-Tuuk-Tomith&nbsp;: Nous avions 26 bateaux de p&ecirc;che &agrave; la traine ici. Ils les ont incendi&eacute;s; ils en ont emport&eacute; certains sur la plage et les ont br&ucirc;l&eacute;s en pr&eacute;sence de la GRC. Nos gens avaient peur; nos gens &eacute;taient terroris&eacute;s devant les Affaires indiennes, le commissaire et la GRC.&nbsp;</p>
<p>Narratrice&nbsp;: La fermeture de l&rsquo;&eacute;cole primaire de Yuquot a &eacute;t&eacute; la goutte qui a fait d&eacute;border le vase. Cela signifiait que nous devions envoyer nos enfants dans un pensionnat &eacute;loign&eacute; &agrave; un &acirc;ge encore plus pr&eacute;coce. Des familles se sont mises &agrave; partir.</p>
<p>(Photo en noir et blanc d&rsquo;une petite &eacute;cole &agrave; un &eacute;tage. Photo d&rsquo;une fillette tenant son petit fr&egrave;re.)</p>
<p>Chef Michael Maquinna&nbsp;: J&rsquo;ai quitt&eacute; Yuquot quand j&rsquo;&eacute;tait jeune. J&rsquo;y ai v&eacute;cu jusqu&rsquo;&agrave; l&rsquo;&acirc;ge de quatre ou cinq ans. J&rsquo;y ai pass&eacute; du temps extraordinaire, tr&egrave;s centr&eacute; sur la famille, j&rsquo;ai un souvenir d&rsquo;une communaut&eacute; tr&egrave;s saine. Nous avions une &eacute;conomie dynamique et certainement de bons moyens de subsistance gr&acirc;ce &agrave; certaines de nos ressources et surtout &agrave; l&rsquo;industrie de la p&ecirc;che.</p>
<p>(S&eacute;ries de photos en noir et blanc de villageois souriants et posant pour la cam&eacute;ra.)</p>
<p>Narratrice&nbsp;: Le gouvernement a permis aux compagnies foresti&egrave;res de commencer &agrave; couper notre for&ecirc;t mature dans les ann&eacute;es 1930.</p>
<p>(Images contemporaines de douzaines de souches sur les rives d&rsquo;une anse.)</p>
<p>Narratrice&nbsp;: Un grand barrage hydro&eacute;lectrique a &eacute;t&eacute; construit sur notre territoire dans les ann&eacute;es 1950.&nbsp;</p>
<p>(Une photo en noir et blanc du site de construction du grand barrage.)</p>
<p>Narratrice&nbsp;: La mine de Myra Falls a &eacute;t&eacute; ouverte ici en 1966. Nous n&rsquo;avons jamais &eacute;t&eacute; consult&eacute;s ou n&rsquo;avons jamais re&ccedil;u de compensations ad&eacute;quates pour le d&eacute;veloppement de ces ressources.</p>
<p>(Photo couleur d&rsquo;une mine avec la colline excav&eacute;e derri&egrave;re.)</p>
<p>Chef Michael Maquinna&nbsp;: Nous avons &eacute;t&eacute; colonis&eacute;s &agrave; fond et nous souhaitons nous d&eacute;coloniser. En esp&eacute;rant r&eacute;ussir &agrave; nous d&eacute;coloniser avec le temps.</p>
<p>Narratrice&nbsp;: En 1964, la compagnie Tahsis a ouvert une usine de p&acirc;tes et papiers &agrave; Ahaminaquus, pr&egrave;s de Gold River. Les Affaires indiennes ont offert de construire une nouvelle r&eacute;serve pour la bande, &agrave; 100 m&egrave;tres de l&rsquo;usine.</p>
<p>(Vid&eacute;os de l&rsquo;int&eacute;rieur de l&rsquo;usine de p&acirc;tes et papiers, avec de grosses machines.)</p>
<p>Narratrice&nbsp;: La bande accepta de d&eacute;m&eacute;nager sous promesse d&rsquo;obtenir de nouveaux emplois offerts par l&rsquo;usine. Tout le monde &eacute;tait confiant que cela marquerait le d&eacute;but d&rsquo;un temps nouveau. Mais seulement une poign&eacute;e d&rsquo;entre nous a travaill&eacute; &agrave; l&rsquo;usine.</p>
<p>(Extrait de film du d&eacute;veloppement r&eacute;sidentiel &agrave; Ahaminaquus dans les ann&eacute;es 1990.)</p>
<p>Margarita James est interview&eacute;e. Elle porte un chandail &agrave; fleurs, des lunettes mauves et ses cheveux gris sont tir&eacute;s vers l&rsquo;arri&egrave;re. Elle est assise en face d&rsquo;une biblioth&egrave;que.)</p>
<p>Margarita James&nbsp;: Mon fils Jordan &eacute;tait b&eacute;b&eacute; et je l&rsquo;avais pos&eacute; dans un porte-b&eacute;b&eacute; sur notre balcon, comme nous le faisions, quand il faisait beau. Je croyais que c&rsquo;&eacute;tait une belle journ&eacute;e jusqu&rsquo;&agrave; ce que je me retourne pour le regarder et que je le vois recouvert de fines. C&rsquo;&eacute;tait comme de la farine ou du sucre en poudre, partout sur lui. J&rsquo;ai dit &agrave; son p&egrave;re&nbsp;: &laquo;&nbsp;C&rsquo;est horrible&nbsp;&raquo;. Et il a dit&nbsp;: &laquo;&nbsp;H&eacute; bien, c&rsquo;est cette usine.&nbsp;&raquo;</p>
<p>(Vid&eacute;o d&rsquo;archive du chef Jerry Jack pointant une photo a&eacute;rienne de la r&eacute;serve pr&egrave;s de l&rsquo;usine.)</p>
<p>Chef Jerry Jack&nbsp;: En raison des conditions de vie de nos gens, la vie sur la r&eacute;serve a &eacute;t&eacute; une autre histoire d&rsquo;horreur. Nous vivons sur seulement 9 acres! C&rsquo;est le seul bout de terre qui nous reste, ici, et l&rsquo;usine loue tout le reste. Et plusieurs d&rsquo;entre nous vivent dans la pauvret&eacute;, bien que nous ayons une usine en plein dans notre r&eacute;serve. Le smog et l&rsquo;odeur et le bruit. C&rsquo;est tout simplement vraiment&hellip; C&rsquo;est tout simplement horrible, c&rsquo;est tout simplement horrible.</p>
<p>Margarita James&nbsp;: L&rsquo;usine &agrave; cette &eacute;poque &eacute;tait horrible, comme l&rsquo;a dit Jerry Jack, &laquo;&nbsp;c&rsquo;&eacute;tait une histoire d&rsquo;horreur.&nbsp;&raquo; Elle crachait des fines. La rivi&egrave;re et le poisson &eacute;taient affect&eacute;s &ndash; les stocks en &eacute;taient affect&eacute;s, r&eacute;duits &agrave; une poign&eacute;e.&nbsp;</p>
<p>(Vid&eacute;o d&rsquo;un petit bateau &agrave; moteur qui passe devant l&rsquo;usine de p&acirc;tes et papiers alors qu&rsquo;elle lib&egrave;re une grosse quantit&eacute; d&rsquo;&eacute;missions.)</p>
<p>Margarita James&nbsp;: Seulement les conditions, la machinerie lourde sur le chemin&hellip; et l&rsquo;eau de la rivi&egrave;re que nous buvions. Il n&rsquo;y avait pas de syst&egrave;me d&rsquo;&eacute;gouts proprement dit dans le village de Gold River. C&rsquo;&eacute;tait tout simplement horrible, tout simplement horrible.</p>
<p>Chef Jerry Jack&nbsp;: Et cela a eu un impact psychologique important sur nos gens, un tr&egrave;s gros impact psychologique. Et quand on a commenc&eacute; &agrave; revenir ici, ce n&rsquo;&eacute;tait plus pareil. Nos gens n&rsquo;&eacute;taient plus les m&ecirc;mes.&nbsp;</p>
<p>Narratrice&nbsp;: Dans les ann&eacute;es 1970, la conseill&egrave;re de la bande du chef &eacute;lu Mary Johnson et le chef h&eacute;r&eacute;ditaire Jerry Jack ont men&eacute; une campagne pour fermer l&rsquo;usine et compenser la bande. L&rsquo;affaire a pris 20 ans &agrave; se r&eacute;gler.</p>
<p>Margarita James&nbsp;: Je suis arriv&eacute;e en 1982 comme directrice g&eacute;n&eacute;rale de la bande par int&eacute;rim. Une opportunit&eacute; de faire un projet de recherche en archives s&rsquo;est pr&eacute;sent&eacute;e et ce qui est ressorti de ce projet, ce sont les dossiers sur le contrat de location de l&rsquo;usine, son histoire.</p>
<p>Narratrice&nbsp;: Les recherches ont d&eacute;montr&eacute; que le gouvernement avait faussement d&eacute;clar&eacute; avoir consult&eacute; les membres de la bande &agrave; propos du contrat de location de l&rsquo;usine. Une inspection de l&rsquo;hygi&egrave;ne environnementale a aussi d&eacute;clar&eacute; que certaines maisons &agrave; Ahaminaquus &eacute;taient &laquo;&nbsp;impropres &agrave; l&rsquo;habitation humaine&nbsp;&raquo;.</p>
<p>Margarita James&nbsp;: Nos avocats ont dit que ce n&rsquo;&eacute;tait pas juste, alors nous, les Mowachaht/Muchalaht, avons entrepris une poursuite contre le gouvernement du Canada. Et nous avons d&ucirc; attendre 10 ans avant de pouvoir se pr&eacute;senter en cour. Le conseil des chefs a sign&eacute; l&rsquo;offre des gouvernements f&eacute;d&eacute;ral et provincial de 9,6 millions de dollars pour relocaliser les 28 m&eacute;nages existants sur la r&eacute;serve d&rsquo;Ahaminaquus #12. &laquo;&nbsp;O&ugrave; voulez-vous aller?&nbsp;&raquo; Tout le monde a dit, la majorit&eacute; des gens ont dit, Yuquot. Mais 9,6&nbsp;millions n&rsquo;&eacute;taient pas assez pour relocaliser 28 maisons, et pour fournir des &eacute;coles et des services de sant&eacute;. Nous avons alors d&ucirc; faire marche arri&egrave;re et nous demander&nbsp;: quelles sont nos autres options?</p>
<p>(Une carte anim&eacute;e avec des fl&egrave;ches et des lignes pointill&eacute;es montre le long trajet en mer &agrave; faire d&rsquo;Ahaminaquus &agrave; Yuquot.)</p>
<p>Narratrice&nbsp;: En 1996, la bande accepta de d&eacute;m&eacute;nager sur une nouvelle r&eacute;serve &agrave; TsaXana, au nord de Gold River. L&rsquo;usine a ferm&eacute; en 1999 &agrave; la suite de plusieurs violations environnementales. Mais qu&rsquo;allait devenir Yuquot?</p>
<p>Margarita James&nbsp;: C&rsquo;est vraiment gr&acirc;ce &agrave; Ambrose, c&rsquo;est lui qui a reconnu l&rsquo;importance de l&rsquo;histoire globale, de l&rsquo;histoire mondiale &agrave; Yuquot. Tout le monde appr&eacute;ciait l&rsquo;histoire europ&eacute;enne car elle mettait vraiment l&rsquo;emphase sur l&rsquo;importance du chef Maquinna et de son importance pour l&rsquo;histoire du Canada. Maquinna a &eacute;t&eacute; le premier &agrave; dire&nbsp;: &laquo;&nbsp;Nous voulons partager Yuquot avec le reste du monde.&nbsp;&raquo; Alors, comment allons-nous faire &ccedil;a?&nbsp;</p>
<p>(Musique enjou&eacute;e et vid&eacute;os contemporaines de familles montant &agrave; bord d&rsquo;un bateau.)</p>
<p>Margarita James&nbsp;: On a d&eacute;cid&eacute; de faire une c&eacute;l&eacute;bration estivale annuelle. Une journ&eacute;e. Et quand nous avons eu une discussion avec les a&icirc;n&eacute;s, il a &eacute;t&eacute; d&eacute;cid&eacute; que nous allions c&eacute;l&eacute;brer l&rsquo;histoire de tout le monde &agrave; Yuquot ce jour-l&agrave;. La premi&egrave;re f&ecirc;te d&rsquo;&eacute;t&eacute; a eu lieu le 28 ao&ucirc;t 1992. Et ce jour-l&agrave; a &eacute;t&eacute; une c&eacute;l&eacute;bration de la rencontre entre le capitaine Vancouver, le chef Maquinna et le capitaine espagnol Bodega y Quadra.</p>
<p>(Vid&eacute;oclips des f&ecirc;tes estivales des ann&eacute;es 1990 &agrave; aujourd&rsquo;hui.)</p>
<p>Narratrice&nbsp;:&nbsp;&nbsp;D&rsquo;autres mesures pour encourager davantage de touristes &agrave; visiter Yuquot ont suivi&nbsp;: en 1993, le chef Max Savey a &eacute;tabli un service de bateau-taxi pour aller &agrave; Yuquot et &agrave; la baie Nootka. Plus tard, six cabines pour touristes ont &eacute;t&eacute; construites. En collaboration avec Parcs Canada, les a&icirc;n&eacute;s ont &eacute;labor&eacute; un plan pour Nis&rsquo;Maas, un centre d&rsquo;interpr&eacute;tation. Au centre, nous voulons que ce soit nos gens qui racontent les histoires, afin d&rsquo;enlever la lunette du colonisateur et d&rsquo;offrir aux visiteurs une perspective autochtone de notre histoire.</p>
<p>(Des croquis de plans du Nis&rsquo;Maas. Les &eacute;difices ressemblent &agrave; des maisons longues, avec des cases &agrave; l&rsquo;int&eacute;rieur pour y mettre des biens culturels.)</p>
<p>Margarita James&nbsp;: Ce sont donc les plans que nous avons au Nis&rsquo;Maas. Je trouve que c&rsquo;est tr&egrave;s int&eacute;ressant, merveilleux, et fabuleux d&rsquo;avoir l&rsquo;opportunit&eacute; de faire cela et j&rsquo;esp&egrave;re que &ccedil;a se concr&eacute;tisera de mon vivant.</p>
<p>(Margarita sourit et regarde au loin.)</p>
<p>Narratrice&nbsp;: En 1923, la Commission des lieux et monuments historiques du Canada a reconnu la baie Nootka comme un site historique. Mais la plaque qu&rsquo;ils ont produite ne dit rien &agrave; propos du chef Maquinna ou du peuple Mowachaht, ou de Yuquot. Lors de la f&ecirc;te d&rsquo;&eacute;t&eacute; de 2021, nous avons c&eacute;l&eacute;br&eacute; avec Parcs Canada l&rsquo;arriv&eacute;e d&rsquo;une nouvelle plaque qui raconte notre histoire selon notre perspective, et qui parle de Yuquot, le centre de notre monde &ndash; l&agrave; o&ugrave; l&rsquo;abondance et l&rsquo;&eacute;nergie de l&rsquo;oc&eacute;an rencontre la majest&eacute; et la richesse de la for&ecirc;t et des anses.</p>
<p>(Extraits de vid&eacute;os contemporaines de la f&ecirc;te d&rsquo;&eacute;t&eacute; avec des tentes mont&eacute;es sur la plage. Quelques images montrent les nouvelles plaques. La vid&eacute;o se termine avec un balayage panoramique sur le pilier de bienvenue de Yuquot et la plage. On entend des tambours et des chants.)</p>