<p>(On entend des tambours et des chants. On entend le vent souffler en arrière-plan. Une photo couleur du chef Ambrose Maquinna avec les cheveux blancs et portant des lunettes carrées et un t-shirt à l’effigie du chef Maquinna de la fin des années 1700. On peut lire le texte : « Ce film est inspiré des écrits de feu chef Ambrose Maquinna ».)</p>
<p>Une citation en texte écrit à la machine à écrire apparaît et se lit comme suit : « Nous sommes la Première Nation de Mowachaht et Muchalaht, les gens de la baie Nootka sur la côte ouest de l’île de Vancouver. Cette région a été le pays de nos ancêtres depuis le début des temps. …. Nous sommes ici pour partager avec vous notre compréhension de notre histoire et de notre culture, et en particulier de Yuquot, notre communauté la plus importante. » Chef Ambrose Maquinna, Gold River, 1997</p>
<p>Narratrice : Yuquot signifie « là où les vents viennent de toutes les directions. » Pour nous, Yuquot est le centre du monde et le meilleur endroit où être, entre l’abondance et l’énergie de l’océan et la majesté et la richesse de la forêt et des anses.</p>
<p>(Courts extraits vidéo de l’anse de Yuquot et des collines boisées et des plages autour. Prise de vue d’un pilier de bienvenue sculpté.)</p>
<p>Narratrice : C’est un endroit de pouvoir et de changement. Un endroit qui regorge d’histoires, dont celle du premier chef Maquinna rencontrant les Européens lorsqu’ils sont arrivés ici sur leur « maisons flottantes », il y a plus de 200 ans. </p>
<p>(Un dessin du chef Maquinna de la fin des années 1700 portant les habits cérémoniels traditionnels et un chapeau tissé. Un tableau du navire NSM Resolution. </p>
<p>Narratrice : Nous étions contents de la traite – l’échange de quelques fourrures contre des biens auxquels nous attribuions une grande valeur, comme du fer et du tissu. Nous étions attentifs à nous lier d’amitié avec tous nos visiteurs. Nos talents pour la diplomatie et pour le troc ont valu à Yuquot le nom d’anse Amicale.</p>
<p>(Croquis de villageois traitant avec des commerçants de fourrures.)</p>
<p>Narratrice : Le commerce des fourrures a amené Yuquot au centre de l’histoire occidentale. </p>
<p>(Tableaux de navires britanniques et espagnols ancrés à Yuquot.)</p>
<p>Citation à l’écran : « De nombreux navires se mirent à arriver à Yuquot. C’était une bonne période pour nous. Nous avons appris qu’ils ne provenaient pas tous de la même nation, ou ne parlaient pas tous la même langue. Nous avons aussi appris que certains de nos visiteurs étaient de bonnes personnes alors que d’autres étaient des scélérats. » Chef Ambrose Maquinna, Gold River, 1997 (missing in the English version)</p>
<p>(Le chef héréditaire Michael Maquinna de la Première Nation Mowachaht/Muchalaht est interviewé à l’écran, devant un agrandissement d’un dessin de leur village ancestral.)</p>
<p>Chef héréditaire Michael Maquinna : « Au début, ce n’était pas une mauvaise chose, mais avec le temps, nous avons réalisé que les choses n’avaient pas trop bien tournées pour les peuples des Premières Nations. »</p>
<p>Narratrice : Avec le déclin de la population des loutres de mer, les bateaux ont cessé de venir à Yuquot. Bien que les marchands de fourrures aient quittés notre territoire, la maladie qu’ils ont apportée est restée, avec des conséquences dévastatrices. </p>
<p>(Le tambour et les chants en arrière-plan se font entendre plus forts et plus puissants. Un tableau des navires de commerce des fourrures change pour une vidéo montrant l’anse désormais vide.) </p>
<p>(Interview d’archive datant de 1993 du chef Jerry Jack. Il a les cheveux noirs, porte de grosses lunettes et un coupe-vent bleu. Il s’exprime beaucoup avec ses mains en parlant.)</p>
<p>Chef Jerry Jack : Certaines tribus de notre nation ont été complètement disséminées. Il n’y a eu aucun survivant. Aucun. </p>
<p>Citation à l’écran : « Nous savons qu’à une époque, il y avait de nombreuses tribus, et que nous étions plusieurs milliers… Au début du XXème siècle, nous étions moins de 300. » Chef Ambrose Maquinna, Gold River, 1997.</p>
<p>Narratrice : Personne aujourd’hui ne peut imaginer la souffrance qu’a pu endurer les quelques survivants parmi notre peuple.</p>
<p>(Photo en noir et blanc de 1896 de vingt Muchalaht, certains plus âgés et d’autres jeunes enfants. Photo de E. Flemming.)</p>
<p>Citation à l’écran : « Depuis cette triste époque, nous avons vécu d’autres situations humiliantes aux mains du gouvernement canadien : la perte de nos territoires, la perte de contrôle sur nos propres affaires, la perte de nos enfants – notre avenir – dans les pensionnats. » Chef Ambrose Maquinna, Gold River, 1997.</p>
<p>(Ghoo-Noom-Tuuk-Tomith est interviewé. Il est âgé et a les cheveux gris. Il porte une casquette de l’équipe de baseball des Rodgers et un manteau à carreaux rouges et noirs. Il est assis près d’un gros arbre.)</p>
<p>Ghoo-Noom-Tuuk-Tomith : Et je m’appelle Ghoo-Noom-Tuuk-Tomith. C’est mon vrai nom, et cela signifie « l’esprit du loup », et ce nom m’a été enlevé lorsque j’ai été au pensionnat. </p>
<p>(Musique mélancolique. Photos de pensionnats.)</p>
<p>Ghoo-Noom-Tuuk-Tomith : L’Église catholique m’a donné des noms catholiques, comme Joseph Peter; c’est pourquoi mon nom est Raymond Joseph Peter. Raymond était un prénom, Joseph Peter m’a été donné par l’évêque sans le consentement de mes parents, ou sans la permission de mes parents. Il y avait 12, 14 enfants ici. Ils ont été emmenés et mis sur un bateau à vapeur pour aller au pensionnat à Kakawis Tofino. </p>
<p>(Séries de photos en noir et blanc de jeunes garçons soulevant des pelles et des bêches, portant des bambins et posant en uniforme scolaire pour une photo de classe.)</p>
<p>(Series of black and white photographs of small boys pulling a rope by the beach, holding toddlers, and posing in school uniform for a class photo.) – the picture shows boys hanging shovels and spades, not pulling a rope by the beach.</p>
<p>Ghoo-Noom-Tuuk-Tomith : Et nous savions peu de chose de l’endroit où nous allions… Nous ne savions pas que nous allions en prison.</p>
<p>(Image en noir et blanc d’un pensionnat et de religieux. Une autre photo avec un prêtre et de jeunes pensionnaires.)</p>
<p>Narratrice : Lorsque le gouvernement a pris les enfants, tout le monde a été dévasté. Les enfants ne pouvaient pas apprendre leur langue, leurs traditions et leurs histoires. </p>
<p>Ghoo-Noom-Tuuk-Tomith : Tout le temps passé là-bas était passé à travailler, travailler, travailler, avec très peu d’école. Nous passions la plupart du temps à construire des routes, à entreposer du charbon ou du bois pour le feu dans la fournaise. </p>
<p>(Photos en noir et blanc de garçons et de filles dans différentes poses au pensionnat.)</p>
<p>Ghoo-Noom-Tuuk-Tomith : Nous, les enfants, nous étions forcés à faire ce genre de travail, et c’était très dur pour nous, les enfants. C’était terrible! Et on nous fouettait si on désobéissait. Nous recevions des coups de ceinture sur les mains ou sur les fesses. Les enfants, lorsqu’ils mourraient, les parents n’étaient pas informés. Ils étaient enterrés à l’école, sans que les parents ne sachent comment ou de quoi leurs enfants étaient morts. </p>
<p>Narratrice : En 1917, la compagnie d’emballage Nootka a établi une conserverie près de Yuquot. </p>
<p>(Photo en noir et blanc des édifices de la conserverie construits sur un quai avec plusieurs bateaux de pêche ancrés le long du quai. Photos de femmes portant un tablier avec les cheveux attachés.)</p>
<p>Narratrice : Presque tout le monde travaillait là. Alors que les femmes travaillaient dans la conserverie, les hommes s’engageaient sur des bateaux loués ou achetés avec des prêts de la compagnie.</p>
<p>(Photo en noir et blanc de huit bateaux de pêche alignés devant la conserverie.)</p>
<p>(Black and white photograph of eight fishing boats lined up by the cannery in the snow.) There is no snow on that picture.</p>
<p>Ghoo-Noom-Tuuk-Tomith : Nous réussissions très bien, nous étions autonomes. Nous n’étions pas riches, mais nous gagnions notre vie dans l’industrie de la pêche. Il n’y avait que des Autochtones, des Japonais et des Chinois. Tous les gérants et les patrons étaient des Blancs.</p>
<p>(Photos en noir et blanc de femmes employées à la conserverie et de propriétaires blancs de la conserverie.)</p>
<p>Narratrice : À une époque, il y avait des conserveries tout le long de la côte de la C.-B., mais pour augmenter leurs profits, les compagnies ont fermé les conserveries les plus éloignées pour en construire de plus grosses dans les villes. </p>
<p>(Carte animée des conserveries le long de la côte de la C.-B.. Avec le temps, il y a eu de moins en moins de conserveries.)</p>
<p>Narratrice : La conserverie de Nootka a fermé en 1945. Nous avons alors tenté d’établir notre propre coopérative de pêche.</p>
<p>Ghoo-Noom-Tuuk-Tomith :  Et cela a été réduit à rien. Ils ont détruit le camp de pêche, ils ont tout pris. Et cela nous a fait vraiment mal. C’était notre gagne-pain. Comme je l’ai dit, pas pour devenir riches, mais pour gagner notre vie, hein. </p>
<p>Narratrice : Plutôt que de nous aider à soutenir notre communauté, le gouvernement voulait nous forcer à quitter Yuquot. </p>
<p>Ghoo-Noom-Tuuk-Tomith : Nous avions 26 bateaux de pêche à la traine ici. Ils les ont incendiés; ils en ont emporté certains sur la plage et les ont brûlés en présence de la GRC. Nos gens avaient peur; nos gens étaient terrorisés devant les Affaires indiennes, le commissaire et la GRC. </p>
<p>Narratrice : La fermeture de l’école primaire de Yuquot a été la goutte qui a fait déborder le vase. Cela signifiait que nous devions envoyer nos enfants dans un pensionnat éloigné à un âge encore plus précoce. Des familles se sont mises à partir.</p>
<p>(Photo en noir et blanc d’une petite école à un étage. Photo d’une fillette tenant son petit frère.)</p>
<p>Chef Michael Maquinna : J’ai quitté Yuquot quand j’était jeune. J’y ai vécu jusqu’à l’âge de quatre ou cinq ans. J’y ai passé du temps extraordinaire, très centré sur la famille, j’ai un souvenir d’une communauté très saine. Nous avions une économie dynamique et certainement de bons moyens de subsistance grâce à certaines de nos ressources et surtout à l’industrie de la pêche.</p>
<p>(Séries de photos en noir et blanc de villageois souriants et posant pour la caméra.)</p>
<p>Narratrice : Le gouvernement a permis aux compagnies forestières de commencer à couper notre forêt mature dans les années 1930.</p>
<p>(Images contemporaines de douzaines de souches sur les rives d’une anse.)</p>
<p>Narratrice : Un grand barrage hydroélectrique a été construit sur notre territoire dans les années 1950. </p>
<p>(Une photo en noir et blanc du site de construction du grand barrage.)</p>
<p>Narratrice : La mine de Myra Falls a été ouverte ici en 1966. Nous n’avons jamais été consultés ou n’avons jamais reçu de compensations adéquates pour le développement de ces ressources.</p>
<p>(Photo couleur d’une mine avec la colline excavée derrière.)</p>
<p>Chef Michael Maquinna : Nous avons été colonisés à fond et nous souhaitons nous décoloniser. En espérant réussir à nous décoloniser avec le temps.</p>
<p>Narratrice : En 1964, la compagnie Tahsis a ouvert une usine de pâtes et papiers à Ahaminaquus, près de Gold River. Les Affaires indiennes ont offert de construire une nouvelle réserve pour la bande, à 100 mètres de l’usine.</p>
<p>(Vidéos de l’intérieur de l’usine de pâtes et papiers, avec de grosses machines.)</p>
<p>Narratrice : La bande accepta de déménager sous promesse d’obtenir de nouveaux emplois offerts par l’usine. Tout le monde était confiant que cela marquerait le début d’un temps nouveau. Mais seulement une poignée d’entre nous a travaillé à l’usine.</p>
<p>(Extrait de film du développement résidentiel à Ahaminaquus dans les années 1990.)</p>
<p>Margarita James est interviewée. Elle porte un chandail à fleurs, des lunettes mauves et ses cheveux gris sont tirés vers l’arrière. Elle est assise en face d’une bibliothèque.)</p>
<p>Margarita James : Mon fils Jordan était bébé et je l’avais posé dans un porte-bébé sur notre balcon, comme nous le faisions, quand il faisait beau. Je croyais que c’était une belle journée jusqu’à ce que je me retourne pour le regarder et que je le vois recouvert de fines. C’était comme de la farine ou du sucre en poudre, partout sur lui. J’ai dit à son père : « C’est horrible ». Et il a dit : « Hé bien, c’est cette usine. »</p>
<p>(Vidéo d’archive du chef Jerry Jack pointant une photo aérienne de la réserve près de l’usine.)</p>
<p>Chef Jerry Jack : En raison des conditions de vie de nos gens, la vie sur la réserve a été une autre histoire d’horreur. Nous vivons sur seulement 9 acres! C’est le seul bout de terre qui nous reste, ici, et l’usine loue tout le reste. Et plusieurs d’entre nous vivent dans la pauvreté, bien que nous ayons une usine en plein dans notre réserve. Le smog et l’odeur et le bruit. C’est tout simplement vraiment… C’est tout simplement horrible, c’est tout simplement horrible.</p>
<p>Margarita James : L’usine à cette époque était horrible, comme l’a dit Jerry Jack, « c’était une histoire d’horreur. » Elle crachait des fines. La rivière et le poisson étaient affectés – les stocks en étaient affectés, réduits à une poignée. </p>
<p>(Vidéo d’un petit bateau à moteur qui passe devant l’usine de pâtes et papiers alors qu’elle libère une grosse quantité d’émissions.)</p>
<p>Margarita James : Seulement les conditions, la machinerie lourde sur le chemin… et l’eau de la rivière que nous buvions. Il n’y avait pas de système d’égouts proprement dit dans le village de Gold River. C’était tout simplement horrible, tout simplement horrible.</p>
<p>Chef Jerry Jack : Et cela a eu un impact psychologique important sur nos gens, un très gros impact psychologique. Et quand on a commencé à revenir ici, ce n’était plus pareil. Nos gens n’étaient plus les mêmes. </p>
<p>Narratrice : Dans les années 1970, la conseillère de la bande du chef élu Mary Johnson et le chef héréditaire Jerry Jack ont mené une campagne pour fermer l’usine et compenser la bande. L’affaire a pris 20 ans à se régler.</p>
<p>Margarita James : Je suis arrivée en 1982 comme directrice générale de la bande par intérim. Une opportunité de faire un projet de recherche en archives s’est présentée et ce qui est ressorti de ce projet, ce sont les dossiers sur le contrat de location de l’usine, son histoire.</p>
<p>Narratrice : Les recherches ont démontré que le gouvernement avait faussement déclaré avoir consulté les membres de la bande à propos du contrat de location de l’usine. Une inspection de l’hygiène environnementale a aussi déclaré que certaines maisons à Ahaminaquus étaient « impropres à l’habitation humaine ».</p>
<p>Margarita James : Nos avocats ont dit que ce n’était pas juste, alors nous, les Mowachaht/Muchalaht, avons entrepris une poursuite contre le gouvernement du Canada. Et nous avons dû attendre 10 ans avant de pouvoir se présenter en cour. Le conseil des chefs a signé l’offre des gouvernements fédéral et provincial de 9,6 millions de dollars pour relocaliser les 28 ménages existants sur la réserve d’Ahaminaquus #12. « Où voulez-vous aller? » Tout le monde a dit, la majorité des gens ont dit, Yuquot. Mais 9,6 millions n’étaient pas assez pour relocaliser 28 maisons, et pour fournir des écoles et des services de santé. Nous avons alors dû faire marche arrière et nous demander : quelles sont nos autres options?</p>
<p>(Une carte animée avec des flèches et des lignes pointillées montre le long trajet en mer à faire d’Ahaminaquus à Yuquot.)</p>
<p>Narratrice : En 1996, la bande accepta de déménager sur une nouvelle réserve à TsaXana, au nord de Gold River. L’usine a fermé en 1999 à la suite de plusieurs violations environnementales. Mais qu’allait devenir Yuquot?</p>
<p>Margarita James : C’est vraiment grâce à Ambrose, c’est lui qui a reconnu l’importance de l’histoire globale, de l’histoire mondiale à Yuquot. Tout le monde appréciait l’histoire européenne car elle mettait vraiment l’emphase sur l’importance du chef Maquinna et de son importance pour l’histoire du Canada. Maquinna a été le premier à dire : « Nous voulons partager Yuquot avec le reste du monde. » Alors, comment allons-nous faire ça? </p>
<p>(Musique enjouée et vidéos contemporaines de familles montant à bord d’un bateau.)</p>
<p>Margarita James : On a décidé de faire une célébration estivale annuelle. Une journée. Et quand nous avons eu une discussion avec les aînés, il a été décidé que nous allions célébrer l’histoire de tout le monde à Yuquot ce jour-là. La première fête d’été a eu lieu le 28 août 1992. Et ce jour-là a été une célébration de la rencontre entre le capitaine Vancouver, le chef Maquinna et le capitaine espagnol Bodega y Quadra.</p>
<p>(Vidéoclips des fêtes estivales des années 1990 à aujourd’hui.)</p>
<p>Narratrice :  D’autres mesures pour encourager davantage de touristes à visiter Yuquot ont suivi : en 1993, le chef Max Savey a établi un service de bateau-taxi pour aller à Yuquot et à la baie Nootka. Plus tard, six cabines pour touristes ont été construites. En collaboration avec Parcs Canada, les aînés ont élaboré un plan pour Nis’Maas, un centre d’interprétation. Au centre, nous voulons que ce soit nos gens qui racontent les histoires, afin d’enlever la lunette du colonisateur et d’offrir aux visiteurs une perspective autochtone de notre histoire.</p>
<p>(Des croquis de plans du Nis’Maas. Les édifices ressemblent à des maisons longues, avec des cases à l’intérieur pour y mettre des biens culturels.)</p>
<p>Margarita James : Ce sont donc les plans que nous avons au Nis’Maas. Je trouve que c’est très intéressant, merveilleux, et fabuleux d’avoir l’opportunité de faire cela et j’espère que ça se concrétisera de mon vivant.</p>
<p>(Margarita sourit et regarde au loin.)</p>
<p>Narratrice : En 1923, la Commission des lieux et monuments historiques du Canada a reconnu la baie Nootka comme un site historique. Mais la plaque qu’ils ont produite ne dit rien à propos du chef Maquinna ou du peuple Mowachaht, ou de Yuquot. Lors de la fête d’été de 2021, nous avons célébré avec Parcs Canada l’arrivée d’une nouvelle plaque qui raconte notre histoire selon notre perspective, et qui parle de Yuquot, le centre de notre monde – là où l’abondance et l’énergie de l’océan rencontre la majesté et la richesse de la forêt et des anses.</p>
<p>(Extraits de vidéos contemporaines de la fête d’été avec des tentes montées sur la plage. Quelques images montrent les nouvelles plaques. La vidéo se termine avec un balayage panoramique sur le pilier de bienvenue de Yuquot et la plage. On entend des tambours et des chants.)</p>